USE SIMEXPRO
GO

INSERT INTO Adua.tbAranceles(aran_Codigo, aran_Descripcion, usua_UsuarioCreacion, aran_FechaCreacion)
VALUES	
		('01.01',			'CABALLOS, ASNOS, MULOS Y BURDEGANOS, VIVOS',	1,	GETDATE()),
		('0101.2',			'- Caballos:',									1,	GETDATE()),
		('0101.21.00.00',	'-- Reproductores de raza pura',				1,	GETDATE()),
		('0101.29.00.00',	'-- Los demás',									1,	GETDATE()),
		('0101.30.00.00',	'- Asnos',										1,	GETDATE()),
		('0101.90.00.00',	'- Los demás',									1,	GETDATE()),
		
		('01.02',			'ANIMALES VIVOS DE LA ESPECIE BOVINA',		1,	GETDATE()),
		('0102.2',			'- Bovinos doméasticos:',					1,	GETDATE()),
		('0102.21.00.00',	'- Reproductores de raza pura',				1,	GETDATE()),
		('0102.29.00.00',	'- Los demás',								1,	GETDATE()),

		('0102.3',			'- Búfalos:', 								1, 	GETDATE()),
		('0102.31.00.00',	'- - Reproductores de raza pura', 			1, 	GETDATE()),
		('0102.39.00.00',	'- - Los demás', 							1, 	GETDATE()),
		('0102.90',			'- Los demás:', 							1, 	GETDATE()),
		('0102.90.10.00',	'- - Reproductores de raza pura', 			1, 	GETDATE()),
		('0102.90.90.00',	'- - Otros', 								1, 	GETDATE()),

		('01.03',			'ANIMALES VIVOS DE LA ESPECIE PORCINA', 	1, 	GETDATE()),
		('0103.10.00.00',	'- Reproductores de raza pura', 			1, 	GETDATE()),
		('0103.9',				'- Los demás:', 									1, 		GETDATE()),
		('0103.91.00.00',		'- - De peso inferior a 50 kg', 					1, 		GETDATE()),
		('0103.92.00.00',		'- - De peso superior o igual a 50 kg', 			1, 		GETDATE()),

		('01.04',				'ANIMALES VIVOS DE LAS ESPECIES OVINA O CAPRINA', 	1, 		GETDATE()),
		('0104.10',				'- De la especie ovina:', 							1, 		GETDATE()),
		('0104.10.10.00',		'- - Reproductores de raza pura', 					1, 		GETDATE()),
		('0104.10.90.00',		'- - Otros', 										1, 		GETDATE()),
		('0104.20',				'- De la especie caprina:', 						1, 		GETDATE()),
		('0104.20.10.00',		'- - Reproductores de raza pura', 					1, 		GETDATE()),
		('0104.20.90.00',		'- - Otros', 										1, 		GETDATE()),
		
		('01.05',				'GALLOS, GALLINAS, PATOS, GANSOS, PAVOS (GALLIPAVOS) Y PINTADAS, DE LAS ESPECIES DOMESTICAS, VIVOS', 	1, 		GETDATE()),
		('0105.1',				'- De peso inferior o igual a 185 g:', 			1, 		GETDATE()),
		('0105.11.00.00',		'- - Aves de la especie Gallus domesticus', 	1, 		GETDATE()),
		('0105.12.00.00',		'- - Pavos (gallipavos)', 						1, 		GETDATE()),
		('0105.13.00.00',		'- - Patos', 									1, 		GETDATE()),
		('0105.14.00.00',		'- - Gansos', 									1, 		GETDATE()),
		('0105.15.00.00',		'- - Pintadas', 								1, 		GETDATE()),
		('0105.9',				'- Los demás:', 								1, 		GETDATE()),
		('0105.94.00.00',		'- - Aves de la especie Gallus domesticus', 	1, 		GETDATE()),
		('0105.99.00.00',		'- - Los demás', 								1, 		GETDATE()),

		('01.06',				'LOS DEMÁS ANIMALES VIVOS', 									1, 		GETDATE()),
		('0106.1',				'- Mamíferos:', 												1, 		GETDATE()),
		('0106.11.00.00',		'- - Primates', 												1, 		GETDATE()),
		('0106.12.00.00',		'- - Ballenas, delfines y marsopas (mamíferos del orden Cetácea); manatíes y dugones o dugongos (mamíferos del orden Sirenia); otarios y focas, leones marinos y morsas (mamíferos del suborden Pinnipedia)', 		1, 		GETDATE()),
		('0106.13.00.00',		'- - Camellos y demás camélidos (Camelidae)', 					1, 		GETDATE()),
		('0106.14.00.00',		'- - Conejos y liebres', 										1, 		GETDATE()),
		('0106.19.00.00',		'- - Los demás', 												1, 		GETDATE()),
		('0106.20.00.00',		'- Reptiles (incluidas las serpientes y tortugas de mar)', 		1, 		GETDATE()),
		('0106.3',				'- Aves:', 																				1, 		GETDATE()),
		('0106.31.00.00',		'- - Aves de rapiña', 																	1, 		GETDATE()),
		('0106.32.00.00',		'- - Psitaciformes (incluidos los loros, guacamayos, cacatúas y demás papagayos)', 		1, 		GETDATE()),
		('0106.33.00.00',		'- - Avestruces; emúes (Dromaius novaehollandiae)', 									1, 		GETDATE()),
		('0106.39.00.00',		'- - Las demás', 																		1, 		GETDATE()),
		('0106.4',				'- Insectos:', 																			1, 		GETDATE()),
		('0106.41.00.00',		'- - Abejas', 																			1, 		GETDATE()),
		('0106.49.00.00',		'- - Los demás', 																		1, 		GETDATE()),
		('0106.90.00.00',		'- Los demás', 																			1, 		GETDATE()),

		('02.01',				'CARNE DE ANIMALES DE LA ESPECIE BOVINA, FRESCA O REFRIGERADA', 																																											1, 		GETDATE()),
		('0201.10.00.00',		'- En canales o medias canales', 																																																			1, 		GETDATE()),
		('0201.20.00.00',		'- Los demás cortes (trozos) sin deshuesar', 																																																1, 		GETDATE()),
		('0201.20.00.00.02',	'- Cortes Especiales Frescos o Refrigerados tales como: Rib-eye, Delmonico. T-bone, New York, Picaña, Filet Migñon, Brisket Boneless, entre- cort, cortes especiales para fajitas, Prime & Choice, carnes marinadas y/o condimentadas', 	1, 		GETDATE()),
		('0201.30.00.00',		'- Deshuesada', 																																																							1, 		GETDATE()),
		('0201.30.00.00.02',	'- Cortes Especiales Frescos o Refrigerados tales como: Rib-eye, Delmonico. T-bone, New York, Picaña, Filet Migñon, Brisket Boneless, entre- cort, cortes especiales para fajitas, Prime & Choice, carnes marinadas y/o condimentadas', 	1, 		GETDATE()),
		
		('02.02',				'CARNE DE ANIMALES DE LA ESPECIE BOVINA, CONGELADA', 																																														1, 		GETDATE()),
		('0202.10.00.00',		'- En canales o medias canales', 																																																			1, 		GETDATE()),
		('0202.20.00.00',		'- Los demás cortes (trozos) sin deshuesar', 																																																1, 		GETDATE()),
		('0202.20.00.00.02',	'- Cortes Especiales Frescos o Refrigerados tales como: Rib-eye, Delmonico. T-bone, New York, Picaña, Filet Migñon, Brisket Boneless, entre- cort, cortes especiales para fajitas, Prime & Choice, carnes marinadas y/o condimentadas', 	1, 		GETDATE()),
		('0202.30.00.00',		'- Deshuesada', 																																																																1, 		GETDATE()),
		('0202.30.00.00.02',	'- Cortes Especiales Frescos o Refrigerados tales como: Rib-eye, Delmonico. T-bone, New York, Picaña, Filet Migñon, Brisket Boneless, entre- cort, cortes especiales para fajitas, Prime & Choice, carnes marinadas y/o condimentadas', 										1, 		GETDATE()),
		
		('02.03',				'CARNE DE ANIMALES DE LA ESPECIE PORCINA, FRESCA, REFRIGERADA O CONGELADA', 																																																	1, 		GETDATE()),
		('0203.1',				'- Fresca o refrigerada:', 																																																														1, 		GETDATE()),
		('0203.11.00.00',		'- - En canales o medias canales', 																																																												1, 		GETDATE()),
		('0203.12.00.00',		'- - Jamones, paletas y sus trozos, sin deshuesar', 																																																							1, 		GETDATE()),
		('0203.12.00.00.01',	'- Cortes Especiales Frescos o Refrigerados tales como: pork brisket, bones narrow, pork bostonbutt, pork brisket abones cut, pork riblets, pork light, spare ribs, pork ribs ends, pork ham ends, pork cushion meat, pork blade meat, carnes marinadas y/o condimentadas', 	1, 		GETDATE()),
		('0203.19.00.00',		'- - Las demás', 																																																																1, 		GETDATE()),
		('0203.19.00.00.01',	'- Cortes Especiales Frescos o Refrigerados tales como: pork brisket, bones narrow, pork bostonbutt, pork brisket abones cut, pork riblets, pork light, spare ribs, pork ribs ends, pork ham ends, pork cushion meat, pork blade meat, carnes marinadas y/o condimentadas', 	1, 		GETDATE()),
		('0203.2',				'- Congelada:', 																																																																1, 		GETDATE()),
		('0203.21.00.00',		'- - En canales o medias canales', 																																																												1, 		GETDATE()),
		('0203.22.00.00',		'- - Jamones, paletas y sus trozos, sin deshuesar', 																																																							1, 		GETDATE()),
		('0203.22.00.00.01',	'- Cortes Especiales Frescos o Refrigerados tales como: pork brisket, bones narrow, pork bostonbutt, pork brisket abones cut, pork riblets, pork light, spare ribs, pork ribs ends, pork ham ends, pork cushion meat, pork blade meat, carnes marinadas y/o condimentadas', 	1, 		GETDATE()),
		('0203.29.00.00',		'- - Las demás', 																																																																1, 		GETDATE()),
		('0203.29.00.00.01',	'- Cortes Especiales Frescos o Refrigerados tales como: pork brisket, bones narrow, pork bostonbutt, pork brisket abones cut, pork riblets, pork light, spare ribs, pork ribs ends, pork ham ends, pork cushion meat, pork blade meat, carnes marinadas y/o condimentadas', 	1, 		GETDATE()),
		
		('02.04',				'CARNE DE ANIMALES DE LAS ESPECIES OVINA O CAPRINA, FRESCA, REFRIGERADA O CONGELADA', 																																															1, 		GETDATE()),
		('0204.10.00.00',		'- Canales o medias canales, de cordero, frescas o refrigeradas', 																																																				1, 		GETDATE()),
		('0204.21.00.00',	'- Las demás carnes de animales de la especie ovina, frescas o refrigeradas:', 																		1, 		GETDATE()),
		('0204.2',			'- - En canales o medias canales', 																													1, 		GETDATE()),
		('0204.22.00.00',	'- - Los demás cortes (trozos) sin deshuesar', 																										1, 		GETDATE()),
		('0204.23.00.00',	'- - Deshuesadas', 																																	1, 		GETDATE()),
		('0204.30.00.00',	'- Canales o medias canales, de cordero, congeladas', 																								1, 		GETDATE()),
		('0204.4',			'- Las demás carnes de animales de la especie ovina, congeladas:', 																					1, 		GETDATE()),
		('0204.41.00.00',	'- - En canales o medias canales', 																													1, 		GETDATE()),
		('0204.42.00.00',	'- - Los demás cortes (trozos) sin deshuesar', 																										1, 		GETDATE()),
		('0204.43.00.00',	'- - Deshuesadas', 																																	1, 		GETDATE()),
		('0204.50.00.00',	'- Carne de animales de la especie caprina', 																										1, 		GETDATE()),
		('0205.00.00.00',	'CARNE DE ANIMALES DE LAS ESPECIES CABALLAR, ASNAL O MULAR, FRESCA, REFRIGERADA O CONGELADA ', 														1, 		GETDATE()),
		
		('02.06',			'DESPOJOS COMESTIBLES DE ANIMALES DE LAS ESPECIES BOVINA, PORCINA, OVINA, CAPRINA, CABALLAR, ASNAL O MULAR, FRESCOS, REFRIGERADOS O CONGELADOS', 	1, 		GETDATE()),
		('0206.10.00.00',	'- De la especie bovina, frescos o refrigerados', 																									1, 		GETDATE()),
		('0206.2',			'- De la especie bovina, congelados:', 																												1, 		GETDATE()),
		('0206.21.00.00',	'- - Lenguas', 																																		1, 		GETDATE()),
		('0206.22.00.00',	'- - Hígados', 																																		1, 		GETDATE()),
		('0206.29.00.00',	'- - Los demás', 																																	1, 		GETDATE()),
		('0206.30',			'- De la especie porcina, frescos o refrigerados:', 																								1, 		GETDATE()),
		('0206.30.10.00',	'- - Piel', 																																		1, 		GETDATE()),
		('0206.30.90.00',	'- - Otros', 																																		1, 		GETDATE()),
		('0206.4',			'- De la especie porcina, congelados:', 																											1, 		GETDATE()),
		('0206.41.00.00',	'- - Hígados', 																																		1, 		GETDATE()),
		('0206.49',			'- - Los demás:', 																																	1, 		GETDATE()),
		('0206.49.10.00',	'- - - Piel', 																																		1, 		GETDATE()),
		('0206.49.90.00',	'- - - Otros', 																																		1, 		GETDATE()),
		('0206.80.00.00',	'- Los demás, frescos o refrigerados', 																												1, 		GETDATE()),
		('0206.90.00.00',	'- Los demás, congelados', 																															1, 		GETDATE()),
		
		('02.07',				'CARNE Y DESPOJOS COMESTIBLES, DE AVES DE LA PARTIDA 01.05, FRESCOS, REFRIGERADOS O CONGELADOS', 																											1, 		GETDATE()),
		('0207.1',				'- De aves de la especie Gallus domesticus:', 																																								1, 		GETDATE()),
		('0207.11.00.00',		'- - Sin trocear, frescos o refrigerados', 																																									1, 		GETDATE()),
		('0207.11.00.00.01',	'- - Marinadas y/o condimentadas', 																																											1, 		GETDATE()),
		('0207.12.00.00',		'- - Sin trocear, congelados', 																																												1, 		GETDATE()),
		('0207.12.00.00.01',	'- - Marinadas y/o condimentadas', 																																											1, 		GETDATE()),
		('0207.13',				'- - Trozos y despojos, frescos o refrigerados:', 																																							1, 		GETDATE()),
		('0207.13.10.00',		'- - - En pasta, deshuesados mecánicamente', 																																								1, 		GETDATE()),
		('0207.13.9',			'- - - Otros:', 																																															1, 		GETDATE()),
		('0207.13.91.00',		'- - - - Pechugas', 																																														1, 		GETDATE()),
		('0207.13.91.00.01',	'- - - - Marinadas y/o condimentadas', 																																										1, 		GETDATE()),
		('0207.13.92.00',		'- - - - Alas', 																																															1, 		GETDATE()),
		('0207.13.92.00.01',	'- - - - Marinadas y/o condimentadas', 																																										1, 		GETDATE()),
		('0207.13.93.00',		'- - - - Muslos, piernas, incluso unidos', 																																									1, 		GETDATE()),
		('0207.13.93.00.01',	'- - - - Marinadas y/o condimentadas', 																																										1, 		GETDATE()),
		('0207.13.94.00',		'- - - - Muslos, piernas, que incluyan en su presentación otros trozos, incluso unidos', 																													1, 		GETDATE()),
		('0207.13.94.00.01',	'- - - - Marinadas y/o condimentadas', 																																										1, 		GETDATE()),
		('0207.13.99.00',		'- - - - Los demás', 																																														1, 		GETDATE()),
		('0207.13.99.00.01',	'- - - - Marinadas y/o condimentadas', 																																										1, 		GETDATE()),
		('0207.14',				'- - Trozos y despojos, congelados:', 																																										1, 		GETDATE()),
		('0207.14.10.00',		'- - - En pasta, deshuesados mecánicamente', 																																								1, 		GETDATE()),
		('0207.14.10.00.01',	'- - - Carne de pollo mecánicamente deshuesada (pasta de pollo) únicamente para la elaboración de embutidos y no acondicionada para la venta al por menor de 25 Kg ( Art. 2, Acuerdo N° 440- 2016)', 		1, 		GETDATE()),
		('0207.14.9',			'- - - Otros:', 																																															1, 		GETDATE()),
		('0207.14.91.00',		'- - - - Pechugas', 																																														1, 		GETDATE()),
		('0207.14.91.00.01',	'- - - - Marinadas y/o condimentadas', 																																										1, 		GETDATE()),
		('0207.14.92.00',		'- - - - Alas', 																																															1, 		GETDATE()),
		('0207.14.92.00.01',	'- - - - Marinadas y/o condimentadas', 																																										1, 		GETDATE()),
		('0207.14.93.00',		'- - - - Muslos, piernas, incluso unidos', 													1, 		GETDATE()),
		('0207.14.93.00.01',	'- - - - Marinadas y/o condimentadas', 														1, 		GETDATE()),
		('0207.14.94.00',		'- - - - Muslos, piernas, que incluyan en su presentación otros trozos, incluso unidos', 	1, 		GETDATE()),
		('0207.14.94.00.01',	'- - - - Marinadas y/o condimentadas', 														1, 		GETDATE()),
		('0207.14.99.00',		'- - - - Los demás', 																		1, 		GETDATE()),
		('0207.14.99.00.01',	'- - - - Marinadas y/o condimentadas', 														1, 		GETDATE()),
		('0207.2',				'- De pavo (gallipavo):', 																	1, 		GETDATE()),
		('0207.24.00.00',		'- - Sin trocear, frescos o refrigerados', 													1, 		GETDATE()),
		('0207.25.00.00',		'- - Sin trocear, congelados', 																1, 		GETDATE()),
		('0207.26',				'- - Trozos y despojos, frescos o refrigerados:', 											1, 		GETDATE()),
		('0207.26.10.00',		'- - - En pasta, deshuesados mecánicamente', 												1, 		GETDATE()),
		('0207.26.90.00',		'- - - Otros', 																				1, 		GETDATE()),
		('0207.27',				'- - Trozos y despojos, congelados:', 														1, 		GETDATE()),
		('0207.27.10.00',		'- - - En pasta, deshuesados mecánicamente', 												1, 		GETDATE()),
		('0207.27.90.00',		'- - - Otros', 																				1, 		GETDATE()),
		('0207.4',				'- De pato:', 																				1, 		GETDATE()),
		('0207.41.00.00',		'- - Sin trocear, frescos o refrigerados', 													1, 		GETDATE()),
		('0207.42.00.00',		'- - Sin trocear, congelados', 																1, 		GETDATE()),
		('0207.43.00.00',		'- - Hígados grasos, frescos o refrigerados', 												1, 		GETDATE()),
		('0207.44',				'- - Los demás, frescos o refrigerados:', 													1, 		GETDATE()),
		('0207.44.10.00',		'- - - En pasta, deshuesados mecánicamente', 												1, 		GETDATE()),
		('0207.44.90.00',		'- - - Otros', 																				1, 		GETDATE()),
		('0207.45',				'- - Los demás, congelados:', 																1, 		GETDATE()),
		('0207.45.10.00',		'- - - En pasta, deshuesados mecánicamente', 												1, 		GETDATE()),
		('0207.45.90.00',		'- - - Otros', 																				1, 		GETDATE()),
		('0207.5',				'- De ganso:', 																				1, 		GETDATE()),
		('0207.51.00.00',		'- - Sin trocear, frescos o refrigerados', 													1, 		GETDATE()),
		('0207.52.00.00',		'- - Sin trocear, congelados', 																1, 		GETDATE()),
		('0207.53.00.00',		'- - Hígados grasos, frescos o refrigerados', 												1, 		GETDATE()),
		('0207.54',			'- - Los demás, frescos o refrigerados:', 																																												1, 		GETDATE()),
		('0207.54.10.00',	'- - - En pasta, deshuesados mecánicamente', 																																											1, 		GETDATE()),
		('0207.54.90.00',	'- - - Otros', 																																																			1, 		GETDATE()),
		('0207.55',			'- - Los demás, congelados:', 																																															1, 		GETDATE()),
		('0207.55.10.00',	'- - - En pasta, deshuesados mecánicamente', 																																											1, 		GETDATE()),
		('0207.55.90.00',	'- - - Otros', 																																																			1, 		GETDATE()),
		('0207.60',			'- De pintada:', 																																																		1, 		GETDATE()),
		('0207.60.10.00',	'- - Sin trocear, frescos o refrigerados', 																																												1, 		GETDATE()),
		('0207.60.20.00',	'- - Sin trocear, congelados', 																																															1, 		GETDATE()),
		('0207.60.30.00',	'- - Hígados grasos, frescos o refrigerados', 																																											1, 		GETDATE()),
		('0207.60.4',		'- - Los demás, frescos o refrigerados:', 																																												1, 		GETDATE()),
		('0207.60.41.00',	'- - - En pasta, deshuesados mecánicamente', 																																											1, 		GETDATE()),
		('0207.60.49.00',	'- - - Otros', 																																																			1, 		GETDATE()),
		('0207.60.5',		'- - Los demás, congelados:', 																																															1, 		GETDATE()),
		('0207.60.51.00',	'- - - En pasta, deshuesados mecánicamente', 																																											1, 		GETDATE()),
		('0207.60.59.00',	'- - - Otros', 																																																			1, 		GETDATE()),
		
		('02.08',			'LAS DEMAS CARNES Y DESPOJOS COMESTIBLES, FRESCOS, REFRIGERADOS O CONGELADOS', 																																			1, 		GETDATE()),
		('0208.10.00.00',	'- De conejo o liebre', 																																																1, 		GETDATE()),
		('0208.30.00.00',	'- De primates', 																																																		1, 		GETDATE()),
		('0208.40.00.00',	'- De ballenas, delfines y marsopas (mamíferos del orden Cetácea); de manatíes y dugones o dugongos (mamíferos del orden Sirenia); de otarios y focas, leones marinos y morsas (mamíferos del suborden Pinnipedia)',	1, 		GETDATE()),
		('0208.50.00.00',	'- De reptiles (incluidas las serpientes y tortugas de mar)', 																																							1, 		GETDATE()),
		('0208.60.00.00',	'- De camellos y demás camélidos (Camelidae)', 																																											1, 		GETDATE()),
		('0208.90',			'- Los demás:', 																																																		1, 		GETDATE()),
		('0208.90.10.00',	'- - Ancas (patas) de rana', 																																															1, 		GETDATE()),
		('0208.90.90.00',	'- - Otros', 																																																			1, 		GETDATE()),
		
		('02.09',			'TOCINO SIN PARTES MAGRAS Y GRASA DE CERDO O DE AVE SIN FUNDIR NI EXTRAER DE OTRO MODO, FRESCOS, REFRIGERADOS, CONGELADOS, SALADOS O EN SALMUERA, SECOS O AHUMADOS', 													1, 		GETDATE()),
		('0209.10',			'- De cerdo:', 																																																				1, 		GETDATE()),
		('0209.10.10.00',	'- - Tocino', 																																																				1, 		GETDATE()),
		('0209.10.20.00',	'- - Grasa de cerdo', 																																																		1, 		GETDATE()),
		('0209.90.00.00',	'- Los demás', 																																																				1, 		GETDATE()),
		
		('02.10',			'CARNE Y DESPOJOS COMESTIBLES, SALADOS O EN SALMUERA, SECOS O AHUMADOS; HARINA Y POLVO COMESTIBLES, DE CARNE O DE DESPOJOS', 																								1, 		GETDATE()),
		('0210.1',			'- Carne de la especie porcina:', 																																															1, 		GETDATE()),
		('0210.11.00.00',	'- - Jamones, paletas y sus trozos, sin deshuesar', 																																										1, 		GETDATE()),
		('0210.12.00.00',	'- - Tocino entreverado de panza (panceta) y sus trozos', 																																									1, 		GETDATE()),
		('0210.19.00.00',	'- - Las demás', 																																																			1, 		GETDATE()),
		('0210.20.00.00',	'- Carne de la especie bovina', 																																															1, 		GETDATE()),
		('0210.9',			'- Los demás, incluso la harina y polvo comestibles, de carne o de despojos:', 																																				1, 		GETDATE()),
		('0210.91.00.00',	'- - De primates', 																																																			1, 		GETDATE()),
		('0210.92',			'- - De ballenas, delfines y marsopas (mamíferos del orden Cetácea); de manatíes y dugones o dugongos (mamíferos del orden Sirenia); de otarios y focas, leones marinos y morsas (mamíferos del suborden Pinnipedia):', 	1, 		GETDATE()),
		('0210.92.10.00',	'- - - De otarios y focas, leones marinos y morsas (mamíferos del suborden Pinnipedia)', 																																	1, 		GETDATE()),
		('0210.92.90.00',	'- - - De otros animales', 																																																	1, 		GETDATE()),
		('0210.93.00.00',	'- - De reptiles (incluidas las serpientes y tortugas de mar)', 																																							1, 		GETDATE()),
		('0210.99',			'- - Los demás:', 																																																			1, 		GETDATE()),
		('0210.99.10.00',	'- - - Hígados de ave salados o en salmuera', 																																												1, 		GETDATE()),
		('0210.99.20.00',	'- - - Hígados de ave secos o ahumados', 																																													1, 		GETDATE()),
		('0210.99.30.00',	'- - - Harina y polvo, de carne o de despojos', 																																											1, 		GETDATE()),
		('0210.99.90.00',	'- - - Otros',																																																			1, 		GETDATE()),



		/*AQUI VAN LOS ARANCELES DEL CAPITULO 3 (Asignado: Jafet)*/


		--ARANCELES CAPITULO 4 (Asignado: Isaac)
		('04.01',				'LECHE Y NATA (CREMA), SIN CONCENTRAR, SIN ADICION DE AZUCAR NI OTRO EDULCORANTE', 																						1, 		GETDATE()),
		('0401.10.00.00',		'- Con un contenido de materias grasas inferior o igual al 1% en peso', 																								1, 		GETDATE()),
		('0401.10.00.00.01',	'- Leche pasteurizada entera, fluida en bolsa', 																														1, 		GETDATE()),
		('0401.10.00.00.02',	'- Leche pasteurizada entera en cartón', 																																1, 		GETDATE()),
		('0401.10.00.00.03',	'- Leche entera de larga duración (UHT)', 																																1, 		GETDATE()),
		('0401.10.00.00.04',	'- Leche semidescremada fluida en bolsa, en cartón y en empaques UHT', 																									1, 		GETDATE()),
		('0401.10.00.00.05',	'- Leche descremada fluida en bolsa, en cartón y en empaques UHT', 																										1, 		GETDATE()),
		('0401.10.00.00.06',	'- Leche deslactosada fluida', 																																			1, 		GETDATE()),
		('0401.20.00.00',		'- Con un contenido de materias grasas superior al 1% pero inferior o igual al 6%, en peso', 																			1, 		GETDATE()),
		('0401.40.00.00',		'- Con un contenido de materias grasas superior al 6% pero inferior o igual al 10%, en peso', 																			1, 		GETDATE()),
		('0401.50.00.00',		'- Con un contenido de materias grasas superior al 10% en peso', 																										1, 		GETDATE()),
		
		('04.02',				'LECHE Y NATA (CREMA), CONCENTRADAS O CON ADICION DE AZUCAR U OTRO EDULCORANTE', 																						1, 		GETDATE()),
		('0402.10.00.00',		'- En polvo, gránulos o demás formas sólidas, con un contenido de materias grasas inferior o igual al 1.5 % en peso', 													1, 		GETDATE()),
		('0402.10.00.00.01',	'- Leche descremada y leche deslactosada en polvo para transformación agroindustrial superior a 25 kg (Art. 2, Acuerdo N° 440-2016, Adenda Acuerdo N° 469-A-2016)', 	1, 		GETDATE()),
		('0402.2',				'- En polvo, gránulos o demás formas sólidas, con un contenido de materias grasas superior al 1.5 % en peso:', 															1, 		GETDATE()),
		('0402.21',				'- - Sin adición de azúcar ni otro edulcorante:', 																														1, 		GETDATE()),
		('0402.21.1',			'- - - Leche semidescremada (con un contenido de materias grasas inferior al 26 % en peso):', 																			1, 		GETDATE()),
		('0402.21.11.00',		'- - - - En envases de contenido neto inferior a 3kg', 																													1, 		GETDATE()),
		('0402.21.12.00',		'- - - - En envases de contenido neto superior o igual a 3kg', 																											1, 		GETDATE()),
		('0402.21.2',			'- - - Leche íntegra (con un contenido de materias grasas superior o igual al 26 % en peso):', 																																						1, 		GETDATE()),
		('0402.21.21.00',		'- - - - En envases de contenido neto inferior a 5 kg', 																																															1, 		GETDATE()),
		('0402.21.22.00',		'- - - - En envases de contenido neto superior o igual a 5 kg', 																																													1, 		GETDATE()),
		('0402.21.22.00.01',	'- - - - Leche integra en polvo para transformación agroindustrial, superior a 25 Kg (Art. 2, Acuerdo N° 440-2016, Adenda Acuerdo N° 469-A-2016)', 																									1, 		GETDATE()),
		('0402.29.00.00',		'- - Las demás', 																																																									1, 		GETDATE()),
		('0402.29.00.00.01',	'- - Leche entera en polvo para transformación agroindustrial superior a 25 Kg (Art. 2, Acuerdo N° 440-2016, Adenda Acuerdo N° 469-A-2016)', 																										1, 		GETDATE()),
		('0402.9',				'- Las demás:', 																																																									1, 		GETDATE()),
		('0402.91',				'- - Sin adición de azúcar ni otro edulcorante:', 																																																	1, 		GETDATE()),
		('0402.91.10.00',		'- - - Leche evaporada', 																																																							1, 		GETDATE()),
		('0402.91.20.00',		'- - - Crema de leche', 																																																							1, 		GETDATE()),
		('0402.91.90.00',		'- - - Otras', 																																																										1, 		GETDATE()),
		('0402.99',				'- - Las demás:', 																																																									1, 		GETDATE()),
		('0402.99.10.00',		'- - - Leche condensada', 																																																							1, 		GETDATE()),
		('0402.99.90.00',		'- - - Otras', 																																																										1, 		GETDATE()),
		
		('04.03',				'SUERO DE MANTEQUILLA, LECHE Y NATA (CREMA) CUAJADAS, YOGUR, KEFIR Y DEMAS LECHES Y NATAS (CREMAS) FERMENTADAS O ACIDIFICADAS, INCLUSO CONCENTRADOS, CON ADICION DE AZUCAR U OTRO EDULCORANTE, AROMATIZADOS O CON FRUTAS U OTROS FRUTOS O CACAO', 	1, 		GETDATE()),
		('0403.10',				'- Yogur:', 																																																										1, 		GETDATE()),
		('0403.10.10.00',		'- - Leche fermentada tratada térmicamente, en polvo', 																																																1, 		GETDATE()),
		('0403.10.90.00',		'- - Otros', 																																																										1, 		GETDATE()),
		('0403.90',				'- Los demás:', 																																																									1, 		GETDATE()),
		('0403.90.10.00',		'- - Suero de mantequilla', 																																																						1, 		GETDATE()),
		('0403.90.90.00',		'- - Otros', 																																																										1, 		GETDATE()),

		('04.04',				'LACTOSUERO, INCLUSO CONCENTRADO O CON ADICION DE AZUCAR U OTRO EDULCORANTE; PRODUCTOS CONSTITUIDOS POR LOS COMPONENTES NATURALES DE LA LECHE, INCLUSO CON ADICION DE AZUCAR U OTRO EDULCORANTE, NO EXPRESADOS NI COMPRENDIDOS EN OTRA PARTE', 	1, 		GETDATE()),
		('0404.10.00.00',		'- Lactosuero, aunque esté modificado, incluso concentrado o con adición de azúcar u otro edulcorante', 																																		1, 		GETDATE()),
		('0404.10.00.00.01',	'- Suero en polvo (Art. 2, Acuerdo N° 440-2016)', 																																																1, 		GETDATE()),
		('0404.10.00.00.02',	'- Suero modificado (Art. 2, Acuerdo N° 440-2016)', 																																															1, 		GETDATE()),
		('0404.90.00.00',		'- Los demás', 																																																									1, 		GETDATE()),
		
		('04.05',				'MANTEQUILLA Y DEMAS MATERIAS GRASAS DE LA LECHE; PASTAS LACTEAS PARA UNTAR', 																																									1, 		GETDATE()),
		('0405.10.00.00',		'- Mantequilla', 																																																								1, 		GETDATE()),
		('0405.10.00.00.01',	'- Crema de leche (mantequilla procesada en bolsa)', 																																															1, 		GETDATE()),
		('0405.20.00.00',		'- Pastas lácteas para untar', 																																																					1, 		GETDATE()),
		('0405.90',				'- Las demás:', 																																																								1, 		GETDATE()),
		('0405.90.10.00',		'- - Grasa butírica (“Butter oíl”)', 																																																			1, 		GETDATE()),
		('0405.90.10.00.01',	'- - Grasa butírica para transformación agroindustrial (Art. 2, Acuerdo N° 440-2016)', 																																							1, 		GETDATE()),
		('0405.90.90.00',		'- - Otras', 																																																									1, 		GETDATE()),
		
		('04.06',				'QUESOS Y REQUESON', 																																																							1, 		GETDATE()),
		('0406.10',				'- Queso fresco (sin madurar), incluido el del lactosuero, y requesón:', 																																										1, 		GETDATE()),
		('0406.10.10.00',		'- - Queso mozzarella', 																																																						1, 		GETDATE()),
		('0406.10.90.00',		'- - Otros', 																																																									1, 		GETDATE()),
		('0406.10.90.00.01',	'- - Quesillo', 																																																								1, 		GETDATE()),
		('0406.10.90.00.02',	'- - Queso blanco fresco', 																																																						1, 		GETDATE()),
		('0406.10.90.00.03',	'- - Queso crema', 																																																								1, 		GETDATE()),
		('0406.10.90.00.04',	'- - Queso de producción artesanal', 																																																			1, 		GETDATE()),
		('0406.10.90.00.05',	'- - Requesón', 																																																								1, 		GETDATE()),
		('0406.20',            	'- Queso de cualquier tipo, rallado o en polvo:',         											1,         GETDATE()),
		('0406.20.10.00',       '- - Tipo “Cheddar”, deshidratado',         														1,         GETDATE()),
		('0406.20.20.00',       '- - Queso mozzarella',         																	1,         GETDATE()),
		('0406.20.90.00',       '- - Otros',         																				1,         GETDATE()),
		('0406.30.00.00',       '- Queso fundido, excepto el rallado o en polvo',         											1,         GETDATE()),
		('0406.40.00.00',       '- Queso de pasta azul y demás quesos que presenten vetas producidas por Penicillium roqueforti',   1,         GETDATE()),
		('0406.90',            	'- Los demás quesos:',         																		1,         GETDATE()),
		('0406.90.20.00',       '- - Tipo cheddar, en bloques o en barras',         												1,         GETDATE()),
		('0406.90.90.00',       '- - Otros',         																				1,         GETDATE()),
		('0406.90.90.00.01',    '- - Cuajada',         																				1,         GETDATE()),
		('0406.90.90.00.02',    '- - Queso blanco seco y semiseco',         														1,         GETDATE()),
		
		('04.07',            	'HUEVOS DE AVE CON CASCARA (CASCARON), FRESCOS, CONSERVADOS O COCIDOS',         					1,         GETDATE()),
		('0407.1',           	'- Huevos fecundados para incubación:',         													1,         GETDATE()),
		('0407.11.00.00',       '- - De gallina de la especie Gallus domesticus',         											1,         GETDATE()),
		('0407.11.00.00.01',    '- - Huevo fértil de gallina para incubación (Art. 8, Acuerdo N° 440-2016)',         				1,         GETDATE()),
		('0407.19.00.00',       '- - Los demás',         																			1,         GETDATE()),
		('0407.19.00.00.01',    '- - Huevo fértil de cualquier otra ave para incubación (Art. 8, Acuerdo N° 440-2016)',         	1,         GETDATE()),
		('0407.2',            	'- Los demás huevos frescos:',         																1,         GETDATE()),
		('0407.21.00.00',       '- - De gallina de la especie Gallus domesticus',         											1,         GETDATE()),
		('0407.29',            	'- - Los demás:',         																			1,         GETDATE()),
		('0407.29.10.00',       '- - - De avestruz',         																		1,         GETDATE()),
		('0407.29.90.00',       '- - - Otros',         																				1,         GETDATE()),
		('0407.90',            	'- Los demás:',         																			1,         GETDATE()),
		('0407.90.10.00',       '- - De avestruz',         																			1,         GETDATE()),
		('0407.90.90.00',       '- - Otros',         																				1,         GETDATE()),

		('04.08',          		'HUEVOS DE AVE SIN CASCARA (CASCARON) Y YEMAS DE HUEVO, FRESCOS, SECOS, COCIDOS EN AGUA O VAPOR, MOLDEADOS, CONGELADOS O CONSERVADOS DE OTRO MODO, INCLUSO CON ADICION DE AZUCAR U OTRO EDULCORANTE',   1,         GETDATE()),
		('0408.1',          	'- Yemas de huevo:',         																																											1,         GETDATE()),
		('0408.11.00.00',   	'- - Secas',         																																													1,         GETDATE()),
		('0408.19.00.00',   	'- - Las demás',         																																												1,         GETDATE()),
		('0408.9',          	'- Los demás:',         																																												1,         GETDATE()),
		('0408.91.00.00',   	'- - Secos',         																																													1,         GETDATE()),
		('0408.99.00.00',   	'- - Los demás',         																																												1,         GETDATE()),
		('0409.00.00.00',   	'MIEL NATURAL (Art.2, Acuerdo N° 440-2016)',         																																					1,         GETDATE()),
		('0410.00.00.00',   	'PRODUCTOS COMESTIBLES DE ORIGEN ANIMAL NO EXPRESADOS NI COMPRENDIDOS EN OTRA PARTE',         																											1,         GETDATE()),


		--ARANCELES CAPITULO 5 (Asignado: Isaac)
		('0501.00.00.00',    	'CABELLO EN BRUTO, INCLUSO LAVADO O DESGRASADO; DESPERDICIOS DE CABELLO ',         																						1,         GETDATE()),
		('05.02',            	'CERDAS DE CERDO O DE JABALI; PELO DE TEJON Y DEMAS PELOS DE CEPILLERIA; DESPERDICIOS DE DICHAS CERDAS O PELOS',         												1,         GETDATE()),
		('0502.10.00.00',    	'- Cerdas de cerdo o de jabalí y sus desperdicios',         																											1,         GETDATE()),
		('0502.90.00.00',   	'- Los demás',         																																					1,         GETDATE()),
		('05.04',            	'TRIPAS, VEJIGAS Y ESTOMAGOS DE ANIMALES, EXCEPTO LOS DE PESCADO, ENTEROS O EN TROZOS, FRESCOS, REFRIGERADOS, CONGELADOS, SALADOS O EN SALMUERA, SECOS O AHUMADOS',		1,         GETDATE()),
		('0504.00.10.00',       '- De bovinos',         																																				1,         GETDATE()),
		('0504.00.10.00.01',    '- Mondongo',         																																					1,         GETDATE()),
		('0504.00.20.00',       '- De porcinos o de ovinos',         																																	1,         GETDATE()),
		('0504.00.20.00.01',    '- Tripas naturales (Art. 2, Acuerdo N° 440-2016)',         																											1,         GETDATE()),
		('0504.00.90.00',       '- Otros',         																																						1,         GETDATE()),

		('05.05',            	'PIELES Y DEMAS PARTES DE AVE, CON SUS PLUMAS O SU PLUMON, PLUMAS Y PARTES DE PLUMAS (INCLUSO RECORTADAS) Y PLUMON, EN BRUTO O SIMPLEMENTE LIMPIADOS, DESINFECTADOS O PREPARADOS PARA SU CONSERVACION; POLVO Y DESPERDICIOS DE PLUMAS O DE PARTES DE PLUMAS',				1,         GETDATE()),
		('0505.10.00.00',       '- Plumas de las utilizadas para relleno; plumón',         																																																					1,         GETDATE()),
		('0505.90.00.00',       '- Los demás',         																																																														1,         GETDATE()),
		('0505.90.00.00.01',    '- Harina de pluma hidrolizada (Art. 10, Acuerdo N° 440-2016)',         																																																	1,         GETDATE()),
		
		('05.06',            	'HUESOS Y NUCLEOS CORNEOS, EN BRUTO, DESGRASADOS, SIMPLEMENTE PREPARADOS (PERO SIN CORTAR EN FORMA DETERMINADA), ACIDULADOS O DESGELATINIZADOS; POLVO Y DESPERDICIOS DE ESTAS MATERIAS',         																			1,         GETDATE()),
		('0506.10.00.00',       '- Oseína y huesos acidulados',         																																																									1,         GETDATE()),
		('0506.90.00.00',       '- Los demás',         																																																														1,         GETDATE()),
		
		('05.07',            	'MARFIL, CONCHA (CAPARAZÓN) DE TORTUGA, BALLENAS DE MAMIFEROS MARINOS (INCLUIDAS LAS BARBAS), CUERNOS, ASTAS, CASCOS, PEZUÑAS, UÑAS, GARRAS Y PICOS, EN BRUTO O SIMPLEMENTE PREPARADOS, PERO SIN CORTAR EN FORMA DETERMINADA; POLVO Y DESPERDICIOS DE ESTAS MATERIAS',      1,         GETDATE()),
		('0507.10.00.00',       '- Marfil; polvo y desperdicios de marfil',         																																																						1,         GETDATE()),
		('0507.90.00.00',       '- Los demás',         																																																														1,         GETDATE()),
		('0508.00.00.00',       'CORAL Y MATERIAS SIMILARES, EN BRUTO O SIMPLEMENTE PREPARADOS, PERO SIN OTRO TRABAJO; VALVAS Y CAPARAZONES DE MOLUSCOS, CRUSTACEOS O EQUINODERMOS, Y JIBIONES, EN BRUTO O SIMPLEMENTE PREPARADOS, PERO SIN CORTAR EN FORMA DETERMINADA, INCLUSO EN POLVO Y DESPERDICIOS',  1,         GETDATE()),
		('0510.00.00.00',       'AMBAR GRIS, CASTOREO, ALGALIA Y ALMIZCLE; CANTARIDAS; BILIS, INCLUSO DESECADA; GLANDULAS Y DEMAS SUSTANCIAS DE ORIGEN ANIMAL UTILIZADAS PARA LA PREPARACION DE PRODUCTOS FARMACEUTICOS, FRESCAS, REFRIGERADAS, CONGELADAS O CONSERVADAS PROVISIONALMENTE DE OTRA FORMA',  	1,         GETDATE()),
		
		('05.11',            	'PRODUCTOS DE ORIGEN ANIMAL NO EXPRESADOS NI COMPRENDIDOS EN OTRA PARTE; ANIMALES MUERTOS DE LOS CAPITULOS 1 o 3, IMPROPIOS PARA LA ALIMENTACION HUMANA',         																											1,         GETDATE()),
		('0511.10.00.00',       '- Semen de bovinos',         																								1,         GETDATE()),
		('0511.10.00.00.01',    '- Semen de bovino fresco, refrigerado o congelado (Art. 8, Acuerdo N° 440-2016)',         									1,         GETDATE()),
		('0511.9',            	'- Los demás:',         																									1,         GETDATE()),
		('0511.91',            	'- - Productos de pescado o de crustáceos, moluscos o demás invertebrados acuáticos; animales muertos del Capítulo 3:',     1,         GETDATE()),
		('0511.91.10.00',       '- - - Huevas y lechas',         																							1,         GETDATE()),
		('0511.91.90.00',       '- - - Otros',         																										1,         GETDATE()),
		('0511.91.90.00.01',    '- - - Cabeza de pescado (Tilapia, Bagre, Pargo, Corvina, Róbalo)',         												1,         GETDATE()),
		('0511.99',            	'- - Los demás:',         																									1,         GETDATE()),
		('0511.99.10.00',       '- - - Óvulos fecundados',         																							1,         GETDATE()),
		('0511.99.10.00.01',    '- - - Embriones (Art. 8, Acuerdo N° 440-2016)',         																	1,         GETDATE()),
		('0511.99.20.00',       '- - - Esponjas naturales de origen animal',         																		1,         GETDATE()),
		('0511.99.90.00',       '- - - Otros',         																										1,         GETDATE()),
		('0511.99.90.00.01',    '- - - Semen fresco de origen animal, fresco refrigerado o congelado (Art. 8, Acuerdo N° 440-2016)',						1,         GETDATE()),