-----------------INSERTS GENERAL

--**********CARGOS**********--
INSERT INTO [Gral].[tbCargos] ([carg_Nombre], usua_UsuarioCreacion, [carg_FechaCreacion])
VALUES ('Operario', 1, GETDATE()),
	   ('Supervisor de módulo', 1, GETDATE()),
	   ('Coordinador de logística', 1, GETDATE()),
	   ('Gerente de RRHH', 1, GETDATE())


--**********ESTADOS CIVILES**********--
INSERT INTO [Gral].[tbEstadosCiviles] (escv_Nombre, usua_UsuarioCreacion, escv_FechaCreacion)
VALUES ('Soltero(a)', 1, GETDATE()),
	   ('Casado(a)', 1, GETDATE()),
	   ('Divorciado(a)', 1, GETDATE()),
	   ('Viudo(a)', 1, GETDATE()),
	   ('Unión Libre', 1, GETDATE())
	   

--**********OFICINAS**********--
INSERT INTO [Gral].[tbOficinas] ([ofic_Nombre], usua_UsuarioCreacion, [ofic_FechaCreacion])
VALUES ('TEGUCIGALPA, M.D.C.', 1, GETDATE()),
	   ('SAN PEDRO SULA, CORTÉS', 1, GETDATE())


--**********OFICIO/PROFESIÓN**********--
INSERT INTO [Gral].[tbOficio_Profesiones] ([ofpr_Nombre], usua_UsuarioCreacion, [ofpr_FechaCreacion])
VALUES ('OFICIALES DE LAS FUERZAS ARMADAS', 1, GETDATE()),
	   ('SUBOFICIALES DE LAS FUERZAS ARMADAS', 1, GETDATE()),
	   ('OTROS MIEMBROS DE LAS FUERZAS ARMADAS', 1, GETDATE()),
	   ('MIEMBROS DEL PODER EJECUTIVO Y DE LOS CUERPOS LEGISLATIVOS', 1, GETDATE())


--**********PAISES**********--
INSERT INTO [Gral].[tbPaises] ([pais_Codigo], [pais_Nombre], [usua_UsuarioCreacion], [pais_FechaCreacion])
VALUES	('AD', 'ANDORRA', 1, GETDATE()),
		('AE', 'EMIRATOS ARABES UNIDOS', 1, GETDATE()),
		('AF', 'AFGANISTAN', 1, GETDATE()),
		('AG', 'ANTIGUA Y BARBUDA', 1, GETDATE()),
		('AI', 'ANGUILLA', 1, GETDATE()),
		('AL', 'ALBANIA', 1, GETDATE()),
		('AM', 'ARMENIA', 1, GETDATE()),
		('AN', 'ANTILLAS HOLANDESAS', 1, GETDATE()),
		('AO', 'ANGOLA', 1, GETDATE()),
		('AQ', 'ANTARTIDA', 1, GETDATE()),
		('AR', 'ARGENTINA', 1, GETDATE()),
		('AS', 'SAMOA AMERICANA', 1, GETDATE()),
		('AT', 'AUSTRIA', 1, GETDATE()),
		('AU', 'AUSTRALIA', 1, GETDATE()),
		('AW', 'ARUBA', 1, GETDATE()),
		('AX', 'ALAND, ISLAS', 1, GETDATE()),
		('AZ', 'AZERBALIAN', 1, GETDATE()),
		('BA', 'BOSNIA Y HERZSEGOVINA', 1, GETDATE()),
		('BB', 'BARBADOS', 1, GETDATE()),
		('BD', 'BANGLADESH', 1, GETDATE()),
		('BE', 'BELGICA', 1, GETDATE()),
		('BF', 'BURKINA FASO', 1, GETDATE()),
		('BG', 'BULGARIA', 1, GETDATE()),
		('BH', 'BAHREIN', 1, GETDATE()),
		('BI', 'BURUNDI', 1, GETDATE()),
		('BJ', 'BENIN', 1, GETDATE()),
		('BL', 'SAINT BARTHELEMY', 1, GETDATE()),
		('BM', 'BERMUDA', 1, GETDATE()),
		('BN', 'BRUNEI DARUSSALAM', 1, GETDATE()),
		('BO', 'BOLIVIA', 1, GETDATE()),
		('BQ', 'BONAIRE, SINT EUSTATIUS AND SABA', 1, GETDATE()),
		('BR', 'BRASIL', 1, GETDATE()),
		('BS', 'BAHAMAS', 1, GETDATE()),
		('BT', 'BUTAN', 1, GETDATE()),
		('BV', 'BOUVET, ISLA', 1, GETDATE()),
		('BW', 'BOTSWANA', 1, GETDATE()),
		('BY', 'BIELORRUSIA', 1, GETDATE()),
		('BZ', 'BELICE', 1, GETDATE()),
		('CA', 'CANADA', 1, GETDATE()),
		('CC', 'COCOS (KEELING) ISLAS', 1, GETDATE()),
		('CD', 'CONGO, REPUBLICA DEMOCRATICA', 1, GETDATE()),
		('CF', 'CENTROAFRICANA, REPUBLICA', 1, GETDATE()),
		('CG', 'CONGO, REP. POPULAR DEL', 1, GETDATE()),
		('CH', 'SUIZA', 1, GETDATE()),
		('CI', 'COSTA DE MARFIL (COTE D''IVOIRE)', 1, GETDATE()),
		('CK', 'COOK ISLAS', 1, GETDATE()),
		('CL', 'CHILE', 1, GETDATE()),
		('CM', 'CAMERUN', 1, GETDATE()),
		('CN', 'CHINA', 1, GETDATE()),
		('CO', 'COLOMBIA', 1, GETDATE()),
		('CR', 'COSTA RICA', 1, GETDATE()),
		('CU', 'CUBA', 1, GETDATE()),
		('CV', 'CABO VERDE', 1, GETDATE()),
		('CW', 'CURAZAO', 1, GETDATE()),
		('CX', 'NAVIDAD, ISLAS', 1, GETDATE()),
		('CY', 'CHIPRE', 1, GETDATE()),
		('CZ', 'CHECA, REPUBLICA', 1, GETDATE()),
		('DE', 'ALEMANIA, REPUBLICA FEDERAL', 1, GETDATE()),
		('DJ', 'DJIBOUTH', 1, GETDATE()),
		('DK', 'DINAMARCA', 1, GETDATE()),
		('DM', 'DOMINICA', 1, GETDATE()),
		('DO', 'DOMINICANA, REPUBLICA', 1, GETDATE()),
		('DZ', 'ARGELIA', 1, GETDATE()),
		('EC', 'ECUADOR', 1, GETDATE()),
		('EE', 'ESTONIA', 1, GETDATE()),
		('EG', 'EGIPTO', 1, GETDATE()),
		('EH', 'SAHARA DEL OESTE', 1, GETDATE()),
		('ER', 'ERITREA', 1, GETDATE()),
		('ES', 'ESPAÑA', 1, GETDATE()),
		('ET', 'ETIOPIA', 1, GETDATE()),
		('FI', 'FINLANDIA', 1, GETDATE()),
		('FJ', 'FIJI', 1, GETDATE()),
		('FK', 'FALKLAND ISLAS (MALVINAS)', 1, GETDATE()),
		('FM', 'MICRONESIA,ESTADO FEDERAL DE', 1, GETDATE()),
		('FO', 'FAROE, ISLAS', 1, GETDATE()),
		('FR', 'FRANCIA', 1, GETDATE()),
		('GA', 'GABON', 1, GETDATE()),
		('GB', 'REINO UNIDO (INGLATERRA, IRLANDA NORTE, ESCOCIA, GALES)', 1, GETDATE()),
		('GD', 'GRENADA', 1, GETDATE()),
		('GE', 'GEORGIA', 1, GETDATE()),
		('GF', 'FRANCESA, GUINEA', 1, GETDATE()),
		('GH', 'GHANA', 1, GETDATE()),
		('GI', 'GIBRALTAR', 1, GETDATE()),
		('GL', 'GROENLANDIA', 1, GETDATE()),
		('GM', 'GAMBIA', 1, GETDATE()),
		('GN', 'GUINEA', 1, GETDATE()),
		('GP', 'GUADALUPE', 1, GETDATE()),
		('GQ', 'ECUATORIAL, GUINEA', 1, GETDATE()),
		('GR', 'GRECIA', 1, GETDATE()),
		('GS', 'GEORGIA DEL SUR E ISLAS SAND', 1, GETDATE()),
		('GT', 'GUATEMALA', 1, GETDATE()),
		('GU', 'GUAN', 1, GETDATE()),
		('GW', 'GUINEA-BISSAU', 1, GETDATE()),
		('GY', 'GUYANA (ANTIGUA GUYANA INGLESA', 1, GETDATE()),
		('HK', 'HONG KONG', 1, GETDATE()),
		('HM', 'HEARD Y MC DONALD ISLAS', 1, GETDATE()),
		('HN', 'HONDURAS', 1, GETDATE()),
		('HR', 'CROACIA', 1, GETDATE()),
		('HT', 'HAITI', 1, GETDATE()),
		('HU', 'HUNGRIA', 1, GETDATE()),
		('ID', 'INDONESIA', 1, GETDATE()),
		('IE', 'IRLANDA', 1, GETDATE()),
		('IL', 'ISRAEL', 1, GETDATE()),
		('IN', 'INDIA', 1, GETDATE()),
		('IO', 'TERRITORIO BRITANICO DEL OCEANO INDICO', 1, GETDATE()),
		('IQ', 'IRAQ', 1, GETDATE()),
		('IR', 'IRAN, REPUBLICA ISLAMICA', 1, GETDATE()),
		('IS', 'ISLANDIA', 1, GETDATE()),
		('IT', 'ITALIA', 1, GETDATE()),
		('JM', 'JAMAICA', 1, GETDATE()),
		('JO', 'JORDANIA', 1, GETDATE()),
		('JP', 'JAPON', 1, GETDATE()),
		('KE', 'KENIA', 1, GETDATE()),
		('KG', 'KIRGHIZISTAN', 1, GETDATE()),
		('KH', 'CAMBOYA', 1, GETDATE()),
		('KI', 'KIRIBATI', 1, GETDATE()),
		('KM', 'COMORES', 1, GETDATE()),
		('KN', 'SAINT KITTS AND NEVIS', 1, GETDATE()),
		('KP', 'KOREA, REP. POPULAR DEMOCRATICA', 1, GETDATE()),
		('KR', 'KOREA, REP. DE (KOREA DEL SUR)', 1, GETDATE()),
		('KW', 'KUWAIT', 1, GETDATE()),
		('KY', 'CAIMAN ISLAS', 1, GETDATE()),
		('KZ', 'KAZAKSTAN', 1, GETDATE()),
		('LA', 'LAOS, REPUBLICA POPULAR DEMOCRATICA', 1, GETDATE()),
		('LB', 'LIBANO', 1, GETDATE()),
		('LC', 'SANTA LUCIA', 1, GETDATE()),
		('LI', 'LIECHTENSTEIN', 1, GETDATE()),
		('LK', 'SRI LANKA (CEILAN)', 1, GETDATE()),
		('LR', 'LIBERIA', 1, GETDATE()),
		('LS', 'LESOTHO', 1, GETDATE()),
		('LT', 'LITUANIA', 1, GETDATE()),
		('LU', 'LUXEMBURGO', 1, GETDATE()),
		('LV', 'LETONIA', 1, GETDATE()),
		('LY', 'LIBIA ARABE JAMAHIRIYA', 1, GETDATE()),
		('MA', 'MARRUECOS', 1, GETDATE()),
		('MC', 'MONACO', 1, GETDATE()),
		('MD', 'MOLDAVIA, REPUBLICA DE', 1, GETDATE()),
		('ME', 'MONTENEGRO', 1, GETDATE()),
		('MF', 'SAINT MARTIN (FRENCH PART)', 1, GETDATE()),
		('MG', 'MADAGASCAR', 1, GETDATE()),
		('MH', 'MARSHALL, ISLAS', 1, GETDATE()),
		('MK', 'MACEDONIA, LA ANT.REP.DE YUGOS', 1, GETDATE()),
		('ML', 'MALI', 1, GETDATE()),
		('MM', 'MYANMAR (ANTIGUA REP. DE BIRMANIA)', 1, GETDATE()),
		('MN', 'MONGOLIA', 1, GETDATE()),
		('MO', 'MACAU', 1, GETDATE()),
		('MP', 'MARIANAS SEPTENTRIONALES, ISLAS', 1, GETDATE()),
		('MQ', 'MARTINICA', 1, GETDATE()),
		('MR', 'MAURITANIA', 1, GETDATE()),
		('MS', 'MONTSERRAT', 1, GETDATE()),
		('MT', 'MALTA', 1, GETDATE()),
		('MU', 'MAURICIOS', 1, GETDATE()),
		('MV', 'MALDIVAS', 1, GETDATE()),
		('MW', 'MALAWI', 1, GETDATE()),
		('MX', 'MEXICO', 1, GETDATE()),
		('MY', 'MALASIA', 1, GETDATE()),
		('MZ', 'MOZAMBIQUE', 1, GETDATE()),
		('NA', 'NAMIBIA', 1, GETDATE()),
		('NC', 'NUEVA CALEDONIA', 1, GETDATE()),
		('NE', 'NIGER', 1, GETDATE()),
		('NF', 'NORFOLK, ISLAS', 1, GETDATE()),
		('NG', 'NIGERIA', 1, GETDATE()),
		('NI', 'NICARAGUA', 1, GETDATE()),
		('NL', 'PAISES BAJOS', 1, GETDATE()),
		('NO', 'NORUEGA', 1, GETDATE()),
		('NP', 'NEPAL', 1, GETDATE()),
		('NR', 'NAURO', 1, GETDATE()),
		('NU', 'NIUE', 1, GETDATE()),
		('NZ', 'NUEVA ZELANDA', 1, GETDATE()),
		('OM', 'OMAN', 1, GETDATE()),
		('PA', 'PANAMA', 1, GETDATE()),
		('PE', 'PERU', 1, GETDATE()),
		('PF', 'FRANCESA POLINESIA', 1, GETDATE()),
		('PG', 'PAPUA NUEVA GUINEA', 1, GETDATE()),
		('PH', 'FILIPINAS', 1, GETDATE()),
		('PK', 'PAKISTAN', 1, GETDATE()),
		('PL', 'POLONIA', 1, GETDATE()),
		('PM', 'SAN PEDRO Y MIGUELON', 1, GETDATE()),
		('PN', 'PITCAIRN', 1, GETDATE()),
		('PR', 'PUERTO RICO', 1, GETDATE()),
		('PS', 'TERRITORIO PALESTINO OCUPADO', 1, GETDATE()),
		('PT', 'PORTUGAL', 1, GETDATE()),
		('PW', 'PALAU', 1, GETDATE()),
		('PY', 'PARAGUAY', 1, GETDATE()),
		('QA', 'QATAR', 1, GETDATE()),
		('RE', 'REUNION', 1, GETDATE()),
		('RO', 'RUMANIA', 1, GETDATE()),
		('RS', 'SERBIA', 1, GETDATE()),
		('RU', 'RUSA, FEDERACION', 1, GETDATE()),
		('RW', 'RUANDA', 1, GETDATE()),
		('SA', 'SAUDITA ARABIA', 1, GETDATE()),
		('SB', 'SOLOMON, ISLAS', 1, GETDATE()),
		('SC', 'SEYCHELLES, ISLAS', 1, GETDATE()),
		('SD', 'SUDAN', 1, GETDATE()),
		('SE', 'SUECIA', 1, GETDATE()),
		('SG', 'SINGAPUR', 1, GETDATE()),
		('SH', 'SANTA HELENA', 1, GETDATE()),
		('SI', 'ESLOVENIA', 1, GETDATE()),
		('SJ', 'SVALBARD AND JAN MAYEN ISLAS', 1, GETDATE()),
		('SK', 'ESLOVAKIA', 1, GETDATE()),
		('SL', 'SIERRA LEONA', 1, GETDATE()),
		('SM', 'SAN MARINO', 1, GETDATE()),
		('SN', 'SENEGAL', 1, GETDATE()),
		('SO', 'SOMALIA', 1, GETDATE()),
		('SR', 'SURINAM (GUAYANA HOLANDESAS)', 1, GETDATE()),
		('SS', 'SUDAN DEL SUR', 1, GETDATE()),
		('ST', 'SAO TOME Y PRINCIPE', 1, GETDATE()),
		('SV', 'EL SALVADOR', 1, GETDATE()),
		('SX', 'SINT MAARTEN (DUTCH PART)', 1, GETDATE()),
		('SY', 'SIRIA, REPUBLICA ARABE', 1, GETDATE()),
		('SZ', 'SUAZILANDIA', 1, GETDATE()),
		('TC', 'TURCOS Y CAICOS ISLAS', 1, GETDATE()),
		('TD', 'CHAD', 1, GETDATE()),
		('TF', 'FRANCESES, TERRITORIOS DEL SURESTE', 1, GETDATE()),
		('TG', 'TOGO', 1, GETDATE()),
		('TH', 'TAILANDIA', 1, GETDATE()),
		('TJ', 'TADJIKISTAN', 1, GETDATE()),
		('TK', 'TOKELAU', 1, GETDATE()),
		('TL', 'TIMOR DEL ESTE', 1, GETDATE()),
		('TM', 'TURKMENISTAN', 1, GETDATE()),
		('TN', 'TUNISIA', 1, GETDATE()),
		('TO', 'TONGA', 1, GETDATE()),
		('TR', 'TURQUIA', 1, GETDATE()),
		('TT', 'TRINIDAD Y TOBAGO', 1, GETDATE()),
		('TV', 'TUVALU', 1, GETDATE()),
		('TW', 'TAIWAN, PROVINCIA CHINA DE', 1, GETDATE()),
		('TZ', 'TANZANIA, REPUBLICA UNIDA DE', 1, GETDATE()),
		('UA', 'UCRANIA', 1, GETDATE()),
		('UG', 'UGANDA', 1, GETDATE()),
		('UM', 'ISLAS ULTRAMARINAS MENORES (EEUU)', 1, GETDATE()),
		('US', 'ESTADOS UNIDOS', 1, GETDATE()),
		('UY', 'URUGUAY', 1, GETDATE()),
		('UZ', 'UZBEKISTAN', 1, GETDATE()),
		('VA', 'SANTA SEDE (CIUDAD DEL VATICANO)', 1, GETDATE()),
		('VC', 'SAN VICENTE Y LAS GRANADINAS', 1, GETDATE()),
		('VE', 'VENEZUELA', 1, GETDATE()),
		('VG', 'VIRGENES, ISLAS (BRITANICAS)', 1, GETDATE()),
		('VI', 'VIRGENES, ISLAS (ESTADOS UNIDOS)', 1, GETDATE()),
		('VN', 'VIETNAM', 1, GETDATE()),
		('VU', 'VANUATU', 1, GETDATE()),
		('WF', 'WALLIS Y FUTUNA, ISLAS', 1, GETDATE()),
		('WS', 'SAMOA', 1, GETDATE()),
		('YE', 'YEMEN', 1, GETDATE()),
		('YT', 'MAYOTTE', 1, GETDATE()),
		('ZA', 'SURAFRICA', 1, GETDATE()),
		('ZM', 'ZAMBIA', 1, GETDATE()),
		('ZW', 'ZIMBABWE', 1, GETDATE());


INSERT INTO [Gral].[tbProvincias] ([pvin_Nombre], [pvin_Codigo], [pais_Id], [usua_UsuarioCreacion], [pvin_FechaCreacion])
VALUES	-- Provinces for Argentina (AR)
		('Buenos Aires', 'BA', 11, 1, GETDATE()),
		('Córdoba', 'CO', 11, 1, GETDATE()),
		('Santa Fe', 'SF', 11, 1, GETDATE()),
		('Mendoza', 'MZ', 11, 1, GETDATE()),
		('Tucumán', 'TU', 11, 1, GETDATE()),
		
		-- Provinces for Brazil (BR)
		('São Paulo', 'SP', 32, 1, GETDATE()),
		('Rio de Janeiro', 'RJ', 32, 1, GETDATE()),
		('Minas Gerais', 'MG', 32, 1, GETDATE()),
		('Bahia', 'BA', 32, 1, GETDATE()),
		('Rio Grande do Sul', 'RS', 32, 1, GETDATE()),
		
		-- Provinces for Canada (CA)
		('Ontario', 'ON', 39, 1, GETDATE()),
		('Quebec', 'QC', 39, 1, GETDATE()),
		('British Columbia', 'BC', 39, 1, GETDATE()),
		('Alberta', 'AB', 39, 1, GETDATE()),
		('Manitoba', 'MB', 39, 1, GETDATE()),
		
		-- Provinces for United States (US)
		('California', 'CA', 231, 1, GETDATE()),
		('Texas', 'TX', 231, 1, GETDATE()),
		('Florida', 'FL', 231, 1, GETDATE()),
		('New York', 'NY', 231, 1, GETDATE()),
		('Illinois', 'IL', 231, 1, GETDATE()),
		
		-- Provinces for United Kingdom (GB)
		('England', 'ENG', 78, 1, GETDATE()),
		('Scotland', 'SCT', 78, 1, GETDATE()),
		('Wales', 'WLS', 78, 1, GETDATE()),
		('Northern Ireland', 'NIR', 78, 1, GETDATE()),
		
		-- Provinces for Australia (AU)
		('New South Wales', 'NSW', 14, 1, GETDATE()),
		('Queensland', 'QLD', 14, 1, GETDATE()),
		('Victoria', 'VIC', 14, 1, GETDATE()),
		('Western Australia', 'WA', 14, 1, GETDATE()),
		('South Australia', 'SA', 14, 1, GETDATE()),
		
		-- Provinces for India (IN)
		('Maharashtra', 'MH', 104, 1, GETDATE()),
		('Uttar Pradesh', 'UP', 104, 1, GETDATE()),
		('Tamil Nadu', 'TN', 104, 1, GETDATE()),
		('Karnataka', 'KA', 104, 1, GETDATE()),
		('Gujarat', 'GJ', 104, 1, GETDATE()),
		
		-- Provinces for China (CN)
		('Guangdong', 'GD', 49, 1, GETDATE()),
		('Shandong', 'SD', 49, 1, GETDATE()),
		('Jiangsu', 'JS', 49, 1, GETDATE()),
		('Zhejiang', 'ZJ', 49, 1, GETDATE()),
		('Henan', 'HA', 49, 1, GETDATE()),
		
		-- Provinces for Russia (RU)
		('Moscow', 'MOW', 189, 1, GETDATE()),
		('Saint Petersburg', 'SPE', 189, 1, GETDATE()),
		('Novosibirsk', 'NVS', 189, 1, GETDATE()),
		('Yekaterinburg', 'EKB', 189, 1, GETDATE()),
		('Nizhny Novgorod', 'NIZ', 189, 1, GETDATE()),
		
		-- Provinces for France (FR)
		('Île-de-France', 'IDF', 76, 1, GETDATE()),
		('Auvergne-Rhône-Alpes', 'ARA', 76, 1, GETDATE()),
		('Hauts-de-France', 'HDF', 76, 1, GETDATE()),
		('Occitanie', 'OCC', 76, 1, GETDATE()),
		('Normandy', 'NOR', 76, 1, GETDATE()),
		
		-- Provinces for Germany (DE)
		('North Rhine-Westphalia', 'NRW', 58, 1, GETDATE()),
		('Bavaria', 'BY', 58, 1, GETDATE()),
		('Baden-Württemberg', 'BW', 58, 1, GETDATE()),
		('Lower Saxony', 'NI', 58, 1, GETDATE()),
		('Hesse', 'HE', 58, 1, GETDATE()),
		
		-- Provinces for Italy (IT)
		('Lombardy', 'LOM', 109, 1, GETDATE()),
		('Lazio', 'LAZ', 109, 1, GETDATE()),
		('Campania', 'CAM', 109, 1, GETDATE()),
		('Sicily', 'SIC', 109, 1, GETDATE()),
		('Veneto', 'VEN', 109, 1, GETDATE()),
		
		-- Provinces for Spain (ES)
		('Madrid', 'MAD', 69, 1, GETDATE()),
		('Catalonia', 'CAT', 69, 1, GETDATE()),
		('Andalusia', 'AND', 69, 1, GETDATE()),
		('Valencia', 'VAL', 69, 1, GETDATE()),
		('Galicia', 'GAL', 69, 1, GETDATE()),

		-- Provinces for Honduras (HN)
		('Atlantida', '01', 97, 1, GETDATE()),
		('Colon', '02', 97, 1, GETDATE()),
		('Comayagua', '03', 97, 1, GETDATE()),
		('Copan', '04', 97, 1, GETDATE()),
		('Cortes', '05', 97, 1, GETDATE()),
		('Choluteca', '06', 97, 1, GETDATE()),
		('El Paraiso', '07', 97, 1, GETDATE()),
		('Francisco Morazan', '08', 97, 1, GETDATE()),
		('Gracias a Dios', '09', 97, 1, GETDATE()),
		('Intibuca', '10', 97, 1, GETDATE()),
		('Islas de La Bahia', '11', 97, 1, GETDATE()),
		('La Paz', '12', 97, 1, GETDATE()),
		('Lempira', '13', 97, 1, GETDATE()),
		('Ocotepeque', '14', 97, 1, GETDATE()),
		('Olancho', '15', 97, 1, GETDATE()),
		('Santa Barbara', '16', 97, 1, GETDATE()),
		('Valle', '17', 97, 1, GETDATE()),
		('Yoro', '18', 97, 1, GETDATE());

INSERT INTO [Gral].[tbCiudades] ([ciud_Nombre], [pvin_Id], [usua_UsuarioCreacion], [ciud_FechaCreacion])
VALUES
	('La Ceiba', 65, 1, GETDATE()),
	('El Porvenir', 65, 1, GETDATE()),
	('Tela', 65, 1, GETDATE()),
	('Jutiapa', 65, 1, GETDATE()),
	('La Masica', 65, 1, GETDATE()),
	('San Francisco', 65, 1, GETDATE()),
	('Arizona', 65, 1, GETDATE()),
	('Esparta', 65, 1, GETDATE()),
	('Trujillo', 66, 1, GETDATE()),
	('Balfate', 66, 1, GETDATE()),
	('Iriona', 66, 1, GETDATE()),
	('Limón', 66, 1, GETDATE()),
	('Sabá', 66, 1, GETDATE()),
	('Santa Fe', 66, 1, GETDATE()),
	('Santa Rosa de Aguán', 66, 1, GETDATE()),
	('Sonaguera', 66, 1, GETDATE()),
	('Tocoa', 66, 1, GETDATE()),
	('Bonito Oriental', 66, 1, GETDATE()),
	('Comayagua', 67, 1, GETDATE()),
	('Ajuterique', 67, 1, GETDATE()),
	('El Rosario', 67, 1, GETDATE()),
	('Esquías', 67, 1, GETDATE()),
	('Humuya', 67, 1, GETDATE()),
	('La Libertad', 67, 1, GETDATE()),
	('Lamaní', 67, 1, GETDATE()),
	('La Trinidad', 67, 1, GETDATE()),
	('Lejamaní', 67, 1, GETDATE()),
	('Meámbar', 67, 1, GETDATE()),
	('Minas de Oro', 67, 1, GETDATE()),
	('Ojos de Agua', 67, 1, GETDATE()),
	('San Jerónimo', 67, 1, GETDATE()),
	('San José de Comayagua', 67, 1, GETDATE()),
	('San José del Potrero', 67, 1, GETDATE()),
	('San Luis', 67, 1, GETDATE()),
	('San Sebastián', 67, 1, GETDATE()),
	('Siguatepeque', 67, 1, GETDATE()),
	('Villa de San Antonio', 67, 1, GETDATE()),
	('Las Lajas', 67, 1, GETDATE()),
	('Taulabé', 67, 1, GETDATE()),
	('Santa Rosa de Copán', 68, 1, GETDATE()),
	('Cabañas', 68, 1, GETDATE()),
	('Concepción', 68, 1, GETDATE()),
	('Copán Ruinas', 68, 1, GETDATE()),
	('Corquín', 68, 1, GETDATE()),
	('Cucuyagua', 68, 1, GETDATE()),
	('Dolores', 68, 1, GETDATE()),
	('Dulce Nombre', 68, 1, GETDATE()),
	('El Paraíso', 68, 1, GETDATE()),
	('Florida', 68, 1, GETDATE()),
	('La Jigua', 68, 1, GETDATE()),
	('La Unión', 68, 1, GETDATE()),
	('Nueva Arcadia', 68, 1, GETDATE()),
	('San Agustín', 68, 1, GETDATE()),
	('San Antonio', 68, 1, GETDATE()),
	('San Jerónimo', 68, 1, GETDATE()),
	('San José', 68, 1, GETDATE()),
	('San Juan de Opoa', 68, 1, GETDATE()),
	('San Nicolás', 68, 1, GETDATE()),
	('San Pedro', 68, 1, GETDATE()),
	('Santa Rita', 68, 1, GETDATE()),
	('Trinidad de Copán', 68, 1, GETDATE()),
	('Veracruz', 68, 1, GETDATE()),
	('San Pedro Sula', 69, 1, GETDATE()),
	('Choloma', 69, 1, GETDATE()),
	('Omoa', 69, 1, GETDATE()),
	('Pimienta', 69, 1, GETDATE()),
	('Potrerillos', 69, 1, GETDATE()),
	('Puerto Cortés', 69, 1, GETDATE()),
	('San Antonio de Cortés', '69', 1, GETDATE()),
	('San Francisco de Yojoa', 69, 1, GETDATE()),
	('San Manuel', 69, 1, GETDATE()),
	('Santa Cruz de Yojoa', 69, 1, GETDATE()),
	('Villanueva', 69, 1, GETDATE()),
	('La Lima', 69, 1, GETDATE()),
	
	('Choluteca', 70, 1, GETDATE()),
	('Apacilagua', 70, 1, GETDATE()),
	('Concepción de María', 70, 1, GETDATE()),
	('Duyure', 70, 1, GETDATE()),
	('El Corpus', 70, 1, GETDATE()),
	('El Triunfo', 70, 1, GETDATE()),
	('Marcovia', 70, 1, GETDATE()),
	('Morolica', 70, 1, GETDATE()),
	('Namasigüe', 70, 1, GETDATE()),
	('Orocuina', 70, 1, GETDATE()),
	('Pespire', 70, 1, GETDATE()),
	('San Antonio de Flores', 70, 1, GETDATE()),
	('San Isidro', 70, 1, GETDATE()),
	('San José', 70, 1, GETDATE()),
	('San Marcos de Colón', 70, 1, GETDATE()),
	('Santa Ana de Yusguare', 70, 1, GETDATE()),
	
	('Yuscarán', 71, 1, GETDATE()),
	('Alauca', 71, 1, GETDATE()),
	('Danlí', 71, 1, GETDATE()),
	('El Paraíso', 71, 1, GETDATE()),
	('Güinope', 71, 1, GETDATE()),
	('Jacaleapa', 71, 1, GETDATE()),
	('Liure', 71, 1, GETDATE()),
	('Morocelí', 71, 1, GETDATE()),
	('Oropolí', 71, 1, GETDATE()),
	('Potrerillos', 71, 1, GETDATE()),
	('San Antonio de Flores', 71, 1, GETDATE()),
	('San Lucas', 71, 1, GETDATE()),
	('San Matías', 71, 1, GETDATE()),
	('Soledad', 71, 1, GETDATE()),
	('Teupasenti', 71, 1, GETDATE()),
	('Texiguat', 71, 1, GETDATE()),
	('Vado Ancho', 71, 1, GETDATE()),
	('Yauyupe', 71, 1, GETDATE()),
	('Trojes', 71, 1, GETDATE()),
	
	('Distrito Central', 72, 1, GETDATE()),
	('Alubarén', 72, 1, GETDATE()),
	('Cedros', 72, 1, GETDATE()),
	('Curarén', 72, 1, GETDATE()),
	('El Porvenir', 72, 1, GETDATE()),
	('Guaimaca', 72, 1, GETDATE()),
	('La Libertad', 72, 1, GETDATE()),
	('La Venta', 72, 1, GETDATE()),
	('Lepaterique', 72, 1, GETDATE()),
	('Maraita', 72, 1, GETDATE()),
	('Marale', 72, 1, GETDATE()),
	('Nueva Armenia', 72, 1, GETDATE()),
	('Ojojona', 72, 1, GETDATE()),
	('Orica', 72, 1, GETDATE()),
	('Reitoca', 72, 1, GETDATE()),
	('Sabanagrande', 72, 1, GETDATE()),
	('San Antonio de Oriente', 72, 1, GETDATE()),
	('San Buenaventura', 72, 1, GETDATE()),
	('San Ignacio', 72, 1, GETDATE()),
	('San Juan de Flores', 72, 1, GETDATE()),
	('San Miguelito', 72, 1, GETDATE()),
	('Santa Ana', 72, 1, GETDATE()),
	('Santa Lucía', 72, 1, GETDATE()),
	('Talanga', 72, 1, GETDATE()),
	('Tatumbla', 72, 1, GETDATE()),
	('Valle de Ángeles', 72, 1, GETDATE()),
	('Villa de San Francisco', 72, 1, GETDATE()),
	('Vallecillo', 72, 1, GETDATE()),
	
	('Puerto Lempira', 73, 1, GETDATE()),
	('Brus Laguna', 73, 1, GETDATE()),
	('Ahuas', 73, 1, GETDATE()),
	('Juan Francisco Bulnes', 73, 1, GETDATE()),
	('Ramón Villeda Morales', 73, 1, GETDATE()),
	('Wampusirpe', 73, 1, GETDATE()),
	
	('La Esperanza', 74, 1, GETDATE()),
	('Camasca', 74, 1, GETDATE()),
	('Colomoncagua', 74, 1, GETDATE()),
	('Concepción', 74, 1, GETDATE()),
	('Dolores', 74, 1, GETDATE()),
	('Intibucá', 74, 1, GETDATE()),
	('Jesús de Otoro', 74, 1, GETDATE()),
	('Magdalena', 74, 1, GETDATE()),
	('Masaguara', 74, 1, GETDATE()),
	('San Antonio', 74, 1, GETDATE()),
	('San Isidro', 74, 1, GETDATE()),
	('San Juan', 74, 1, GETDATE()),
	('San Marcos de la Sierra', 74, 1, GETDATE()),
	('San Miguel Guancapla', 74, 1, GETDATE()),
	('Santa Lucía', 74, 1, GETDATE()),
	('Yamaranguila', 74, 1, GETDATE()),
	('San Francisco de Opalaca', 74, 1, GETDATE()),
	
	('Roatán', 75, 1, GETDATE()),
	('Guanaja', 75, 1, GETDATE()),
	('José Santos Guardiola', 75, 1, GETDATE()),
	('Utila', 75, 1, GETDATE()),
	
	('La Paz', 76, 1, GETDATE()),
	('Aguanqueterique', 76, 1, GETDATE()),
	('Cabañas', 76, 1, GETDATE()),
	('Cane', 76, 1, GETDATE()),
	('Chinacla', 76, 1, GETDATE()),
	('Guajiquiro', 76, 1, GETDATE()),
	('Lauterique', 76, 1, GETDATE()),
	('Marcala', 76, 1, GETDATE()),
	('Mercedes de Oriente', 76, 1, GETDATE()),
	('Opatoro', 76, 1, GETDATE()),
	('San Antonio del Norte', 76, 1, GETDATE()),
	('San José', 76, 1, GETDATE()),
	('San Juan', 76, 1, GETDATE()),
	('San Pedro de Tutule', 76, 1, GETDATE()),
	('Santa Ana', 76, 1, GETDATE()),
	('Santa Elena', 76, 1, GETDATE()),
	('Santa María', 76, 1, GETDATE()),
	('Santiago de Puringla', 76, 1, GETDATE()),
	('Yarula', 76, 1, GETDATE()),
	('Gracias', 77, 1, GETDATE()),
	('Belén', 77, 1, GETDATE()),
	('Candelaria', 77, 1, GETDATE()),
	('Cololaca', 77, 1, GETDATE()),
	('Erandique', 77, 1, GETDATE()),
	('Gualcince', 77, 1, GETDATE()),
	('Guarita', 77, 1, GETDATE()),
	('La Campa', 77, 1, GETDATE()),
	('La Iguala', 77, 1, GETDATE()),
	('Las Flores', 77, 1, GETDATE()),
	('La Unión', 77, 1, GETDATE()),
	('La Virtud', 77, 1, GETDATE()),
	('Lepaera', 77, 1, GETDATE()),
	('Mapulaca', 77, 1, GETDATE()),
	('Piraera', 77, 1, GETDATE()),
	('San Andrés', 77, 1, GETDATE()),
	('San Francisco', 77, 1, GETDATE()),
	('San Juan Guarita', 77, 1, GETDATE()),
	('San Manuel Colohete', 77, 1, GETDATE()),
	('San Rafael', 77, 1, GETDATE()),
	('San Sebastián', 77, 1, GETDATE()),
	('Santa Cruz', 77, 1, GETDATE()),
	('Talgua', 77, 1, GETDATE()),
	('Tambla', 77, 1, GETDATE()),
	('Tomalá', 77, 1, GETDATE()),
	('Valladolid', 77, 1, GETDATE()),
	('Virginia', 77, 1, GETDATE()),
	('San Marcos de Caiquín', 77, 1, GETDATE()),
	('Ocotepeque', 78, 1, GETDATE()),
	('Belén Gualcho', 78, 1, GETDATE()),
	('Concepción', 78, 1, GETDATE()),
	('Dolores Merendón', 78, 1, GETDATE()),
	('Fraternidad', 78, 1, GETDATE()),
	('La Encarnación', 78, 1, GETDATE()),
	('La Labor', 78, 1, GETDATE()),
	('Lucerna', 78, 1, GETDATE()),
	('Mercedes', 78, 1, GETDATE()),
	('San Fernando', 78, 1, GETDATE()),
	('San Francisco del Valle', 78, 1, GETDATE()),
	('San Jorge', 78, 1, GETDATE()),
	('San Marcos', 78, 1, GETDATE()),
	('Santa Fe', 78, 1, GETDATE()),
	('Sensenti', 78, 1, GETDATE()),
	('Sinuapa', 78, 1, GETDATE()),
	('Juticalpa', 79, 1, GETDATE()),
	('Campamento', 79, 1, GETDATE()),
	('Catacamas', 79, 1, GETDATE()),
	('Concordia', 79, 1, GETDATE()),
	('Dulce Nombre de Culmí', 79, 1, GETDATE()),
	('El Rosario', 79, 1, GETDATE()),
	('Esquipulas del Norte', 79, 1, GETDATE()),
	('Gualaco', 79, 1, GETDATE()),
	('Guarizama', 79, 1, GETDATE()),
	('Guata', 79, 1, GETDATE()),
	('Guayape', 79, 1, GETDATE()),
	('Jano', 79, 1, GETDATE()),
	('La Unión', 79, 1, GETDATE()),
	('Mangulile', 79, 1, GETDATE()),
	('Manto', 79, 1, GETDATE()),
	('Salamá', 79, 1, GETDATE()),
	('San Esteban', 79, 1, GETDATE()),
	('San Francisco de Becerra', 79, 1, GETDATE()),
	('San Francisco de la Paz', 79, 1, GETDATE()),
	('Santa María del Real', 79, 1, GETDATE()),
	('Silca', 79, 1, GETDATE()),
	('Yocón', 79, 1, GETDATE()),
	('Patuca', 79, 1, GETDATE()),
	('Santa Bárbara', 80, 1, GETDATE()),
	('Arada', 80, 1, GETDATE()),
	('Atima', 80, 1, GETDATE()),
	('Azacualpa', 80, 1, GETDATE()),
	('Ceguaca', 80, 1, GETDATE()),
	('Concepción del Norte', 80, 1, GETDATE()),
	('Concepción del Sur', 80, 1, GETDATE()),
	('Chinda', 80, 1, GETDATE()),
	('El Níspero', 80, 1, GETDATE()),
	('Gualala', 80, 1, GETDATE()),
	('Ilama', 80, 1, GETDATE()),
	('Las Vegas', 80, 1, GETDATE()),
	('Macuelizo', 80, 1, GETDATE()),
	('Naranjito', 80, 1, GETDATE()),
	('Nuevo Celilac', 80, 1, GETDATE()),
	('Nueva Frontera', 80, 1, GETDATE()),
	('Petoa', 80, 1, GETDATE()),
	('Protección', 80, 1, GETDATE()),
	('Quimistán', 80, 1, GETDATE()),
	('San Francisco de Ojuera', 80, 1, GETDATE()),
	('San José de las Colinas', 80, 1, GETDATE()),
	('San Luis', 80, 1, GETDATE()),
	('San Marcos', 80, 1, GETDATE()),
	('San Nicolás', 80, 1, GETDATE()),
	('San Pedro Zacapa', 80, 1, GETDATE()),
	('San Vicente Centenario', 80, 1, GETDATE()),
	('Santa Rita', 80, 1, GETDATE()),
	('Trinidad', 80, 1, GETDATE()),
	('Nacaome', 81, 1, GETDATE()),
	('Alianza', 81, 1, GETDATE()),
	('Amapala', 81, 1, GETDATE()),
	('Aramecina', 81, 1, GETDATE()),
	('Caridad', 81, 1, GETDATE()),
	('Goascorán', 81, 1, GETDATE()),
	('Langue', 81, 1, GETDATE()),
	('San Francisco de Coray', 81, 1, GETDATE()),
	('San Lorenzo', 81, 1, GETDATE()),
	('Yoro', 82, 1, GETDATE()),
	('Arenal', 82, 1, GETDATE()),
	('El Negrito', 82, 1, GETDATE()),
	('El Progreso', 82, 1, GETDATE()),
	('Jocón', 82, 1, GETDATE()),
	('Morazán', 82, 1, GETDATE()),
	('Olanchito', 82, 1, GETDATE()),
	('Santa Rita', 82, 1, GETDATE()),
	('Sulaco', 82, 1, GETDATE()),
	('Victoria', 82, 1, GETDATE()),
	('Yorito', 82, 1, GETDATE());


INSERT INTO [Gral].[tbAldeas] ([alde_Nombre], [ciud_Id], [usua_UsuarioCreacion], [alde_FechaCreacion])
VALUES ('El Carmen', 63, 1, GETDATE()),
	   ('El Hatillo', 69, 1, GETDATE()),
	   ('Los Lirios', 12, 1, GETDATE()),
	   ('El Rosario', 25, 1, GETDATE())


INSERT INTO [Gral].[tbMonedas]([mone_Codigo], [mone_Descripcion], [usua_UsuarioCreacion], [mone_FechaCreacion])
VALUES	('EUR', 'COMUNIDAD EUROPEA, EURO', 1, GETDATE()),
		('HNL', 'HONDURAS, LEMPIRA', 1, GETDATE()),
		('USD', 'DOLAR NORTEAMERICANO', 1, GETDATE()),
		('AED', 'EMIRATOS ARABES UNIDOS, DIRHAM', 1, GETDATE()),
		('AFN', 'AFGANISTAN, AFGANI', 1, GETDATE()),
		('ALL', 'ALBANIA, LEK', 1, GETDATE()),
		('AMD', 'ARMENIA, DRAM ARMENIO', 1, GETDATE()),
		('ANG', 'HOLANDESAS ANTILLAS, FLORIN ANTILLANO NEERLANDES', 1, GETDATE()),
		('AOA', 'ANGOLA, KWANZA', 1, GETDATE()),
		('ARS', 'ARGENTINA, PESO ARGENTINO', 1, GETDATE()),
		('AUD', 'AUSTRALIA, DOLAR AUSTRALIANO', 1, GETDATE()),
		('AWG', 'ARUBA, FLORIN ARUBEÑO', 1, GETDATE()),
		('AZN', 'AZERBALIAN, MANAT AZERBAIYANO', 1, GETDATE()),
		('BAM', 'BOSNIA HERZSEGOVINA, MARCO CONVERTIBLE', 1, GETDATE()),
		('BBD', 'BARBADOS, DOLAR DE BARBADOS', 1, GETDATE()),
		('BDT', 'BANGLADESH, TAKA', 1, GETDATE()),
		('BGN', 'BULGARIA, LEV BULGARO', 1, GETDATE()),
		('BHD', 'BAHREIN, DINAR BAREINI', 1, GETDATE()),
		('BIF', 'BURUNDI, FRANCO DE BURUNDI', 1, GETDATE()),
		('BMD', 'BARMUDA, DOLAR BERMUDEÑO', 1, GETDATE()),
		('BND', 'BRUNEI, DOLAR DE BRUNEI', 1, GETDATE()),
		('BOB', 'BOLIVIA, BOLIVIANO', 1, GETDATE()),
		('BRL', 'BRASIL, REAL BRASILEÑO', 1, GETDATE()),
		('BSD', 'BAHAMAS, DOLAR BAHAMEÑO', 1, GETDATE()),
		('BTN', 'BUTAN, NGULTRUM', 1, GETDATE()),
		('BWP', 'BOTSWANA, PULA', 1, GETDATE()),
		('BYR', 'BIELORRUSIA, RUBLO BIELORRUSO', 1, GETDATE()),
		('BZD', 'BELICE, DOLAR BELICEÑO', 1, GETDATE()),
		('CAD', 'CANADA, DOLAR CANADIENSE', 1, GETDATE()),
		('CDF', 'CONGO, REPUBLICA DEMOCRATICA, FRANCO CONGOLEÑO', 1, GETDATE()),
		('CHF', 'SUIZA, FRANCO SUIZO', 1, GETDATE()),
		('CLP', 'CHILE, PESO CHILENO', 1, GETDATE()),
		('CNY', 'CHINA, YUAN CHINO', 1, GETDATE()),
		('COP', 'COLOMBIA, PESO COLOMBIANO', 1, GETDATE()),
		('CRC', 'COSTA RICA, COLON COSTARRICENSE', 1, GETDATE()),
		('CUC', 'CUBA, PESO CONVERTIBLE', 1, GETDATE()),
		('CUP', 'CUBA, PESO CUBANO', 1, GETDATE()),
		('CVE', 'CABO VERDE, ESCUDO CABOVERDIANO', 1, GETDATE()),
		('CZK', 'CHECA REPUBLICA, CORONA CHECA', 1, GETDATE()),
		('DJF', 'DJIBOUTH, FRANCO YIBUTIANO', 1, GETDATE()),
		('DKK', 'DINAMARCA, CORONA DANESA', 1, GETDATE()),
		('DOP', 'DOMINICANA REPUBLICA, PESO DOMINICANO', 1, GETDATE()),
		('DZD', 'ARGELIA, DINAR ARGELINO', 1, GETDATE()),
		('EGP', 'EGIPTO, LIBRA EGIPCIA', 1, GETDATE()),
		('ERN', 'ERITREA, NAKFA', 1, GETDATE()),
		('ETB', 'ETIOPIA, BIRR ETIOPE', 1, GETDATE()),
		('FJD', 'FIJI, DOLAR FIYIANO', 1, GETDATE()),
		('FKP', 'ISLAS MALVINAS, LIBRA MALVINENSE', 1, GETDATE()),
		('GBP', 'REINO UNIDO, LIBRA ESTERLINA', 1, GETDATE()),
		('GEL', 'GEORGIA, LARI', 1, GETDATE()),
		('GHS', 'GHANA, CEDI GHANES', 1, GETDATE()),
		('GIP', 'GIBRALTAR, LIBRA DE GIBRALTAR', 1, GETDATE()),
		('GMD', 'GAMBIA, DALASI', 1, GETDATE()),
		('GNF', 'GUINEA, FRANCO GUINEANO', 1, GETDATE()),
		('GTQ', 'GUATEMALA, QUETZAL', 1, GETDATE()),
		('GYD', 'GUYANA, DOLAR GUYANES', 1, GETDATE()),
		('HKD', 'HONG KONG, DOLAR DE HONG KONG', 1, GETDATE()),
		('HRK', 'CROACIA, KUNA', 1, GETDATE()),
		('HTG', 'HAITI, GOURDE', 1, GETDATE()),
		('HUF', 'HUNGRIA, FORINTO', 1, GETDATE()),
		('IDR', 'INDONESIA, RUPIA INDONESIA', 1, GETDATE()),
		('ILS', 'ISRAEL, NUEVO SHEQUEL ISRAELI', 1, GETDATE()),
		('INR', 'INDIA, RUPIA INDIA', 1, GETDATE()),
		('IQD', 'IRAQ, DINAR IRAQUI', 1, GETDATE()),
		('IRR', 'IRAN, RIAL IRANI', 1, GETDATE()),
		('ISK', 'ISLANDIA, CORONA ISLANDESA', 1, GETDATE()),
		('JMD', 'JAMAICA, DOLAR JAMAIQUINO', 1, GETDATE()),
		('JOD', 'JORDANIA, DINAR JORDANO', 1, GETDATE()),
		('JPY', 'JAPON, YEN', 1, GETDATE()),
		('KES', 'KENIA, CHELIN KENIANO', 1, GETDATE()),
		('KGS', 'KIRGHIZISTAN, SOM', 1, GETDATE()),
		('KHR', 'CAMBOYA, RIEL', 1, GETDATE()),
		('KMF', 'COMORES, FRANCO COMORENSE', 1, GETDATE()),
		('KPW', 'KOREA, REPUBLICA POPULAR, WON NORCOREANO', 1, GETDATE()),
		('KRW', 'KOREA, REPUBLICA DEMOCRATICA, WON', 1, GETDATE()),
		('KWD', 'KUWAIT, DINAR KUWAITI', 1, GETDATE()),
		('KYD', 'CAIMAN ISLAS, DOLAR DE LAS ISLAS CAIMAN', 1, GETDATE()),
		('KZT', 'KAZAKSTAN, TENGE', 1, GETDATE()),
		('LAK', 'LAOS, REPUBLICA POPULAR DEMOCRATICA, KIP', 1, GETDATE()),
		('LBP', 'LIBANO, LIBRA LIBANESA', 1, GETDATE()),
		('LKR', 'SRI LANKA, RUPIA DE SRI LANKA', 1, GETDATE()),
		('LRD', 'LIBERIA, DOLAR LIBERIANO', 1, GETDATE()),
		('LSL', 'LESOTHO, LOTI', 1, GETDATE()),
		('LYD', 'LIBIA ARABE, DINAR LIBIO', 1, GETDATE()),
		('MAD', 'MARRUECOS, DIRHAM MARROQUI', 1, GETDATE()),
		('MDL', 'MOLDAVIA, REPUBLICA DE, LEU MOLDAVO', 1, GETDATE()),
		('MGA', 'MADAGASCAR, ARIARY MALGACHE', 1, GETDATE()),
		('MKD', 'MACEDONIA, DENAR', 1, GETDATE()),
		('MMK', 'MYANMA, KYAT', 1, GETDATE()),
		('MNT', 'MONGOLIA, TUGRIK', 1, GETDATE()),
		('MOP', 'MACAU, PATACA', 1, GETDATE()),
		('MRO', 'MAURITANIA, UQUIYA', 1, GETDATE()),
		('MUR', 'MAURICIOS, RUPIA DE MAURICIO', 1, GETDATE()),
		('MVR', 'MALDIVAS, RUFIYAA', 1, GETDATE()),
		('MWK', 'MALAWI, KWACHA', 1, GETDATE()),
		('MXN', 'MEXICO, PESO MEXICANO', 1, GETDATE()),
		('MYR', 'MALASIA, RINGGIT MALAYO', 1, GETDATE()),
		('MZN', 'MOZAMBIQUE, METICAL MOZAMBIQUEÑO', 1, GETDATE()),
		('NAD', 'NAMIBIA, DOLAR NAMIBIO', 1, GETDATE()),
		('NGN', 'NIGERIA, NAIRA', 1, GETDATE()),
		('NIO', 'NICARAGUA, CORDOBA', 1, GETDATE()),
		('NOK', 'NORUEGA, CORONA NORUEGA', 1, GETDATE()),
		('NPR', 'NEPAL, RUPIA NEPALI', 1, GETDATE()),
		('NZD', 'NUEVA ZELANDA, DOLAR NEOZELANDES', 1, GETDATE()),
		('OMR', 'OMAN, RIAL OMANI', 1, GETDATE()),
		('PAB', 'PANAMA, BALBOA', 1, GETDATE()),
		('PEN', 'PERU, SOL PERUANO', 1, GETDATE()),
		('PGK', 'PAPUA NUEVA GUINEA, KINA', 1, GETDATE()),
		('PHP', 'FILIPINAS, PESO FILIPINO', 1, GETDATE()),
		('PKR', 'PAKISTAN, RUPIA PAKISTANI', 1, GETDATE()),
		('PLN', 'POLONIA, ZLOTY', 1, GETDATE()),
		('PYG', 'PARAGUAY, GUARANI', 1, GETDATE()),
		('QAR', 'QATAR, RIYAL QATARI', 1, GETDATE()),
		('RON', 'RUMANIA, LEU RUMANO', 1, GETDATE()),
		('RSD', 'SERBIA, DINAR SERBIO', 1, GETDATE()),
		('RUB', 'RUSA FEDERACION, RUBLO RUSO', 1, GETDATE()),
		('RWF', 'RUANDA, FRANCO RUANDES', 1, GETDATE()),
		('SAR', 'SAUDITA ARABIA, RIYAL SAUDI', 1, GETDATE()),
		('SBD', 'SOLOMON ISLAS, DOLAR DE LAS ISLAS SALOMON', 1, GETDATE()),
		('SCR', 'SEYCHELLES ISLAS, RUPIA SEYCHELENSE', 1, GETDATE()),
		('SDG', 'SUDAN, DINAR SUDANES', 1, GETDATE()),
		('SEK', 'SUECIA, CORONA SUECA', 1, GETDATE()),
		('SGD', 'SINGAPUR, DOLAR DE SINGAPUR', 1, GETDATE()),
		('SHP', 'SANTA HELENA, LIBRA DE SANTA ELENA', 1, GETDATE()),
		('SLL', 'SIERRA LEONA, LEONE', 1, GETDATE()),
		('SOS', 'SOMALIA, CHELIN SOMALI', 1, GETDATE()),
		('SRD', 'SURINAM, DOLAR SURINAMES', 1, GETDATE()),
		('SSP', 'SUDAN DEL SUR, LIBRA SURSUDANESA', 1, GETDATE()),
		('STD', 'SAO TOME Y PRINCIPE, DOBRA', 1, GETDATE()),
		('SYP', 'SIRIA REPUBLICA ARABE, LIBRA SIRIA', 1, GETDATE()),
		('SZL', 'SUAZILANDIA, LILANGENI', 1, GETDATE()),
		('THB', 'TAILANDIA, BAHT', 1, GETDATE()),
		('TJS', 'TADJIKISTAN, SOMONI TAYIKO', 1, GETDATE()),
		('TMT', 'TURKMENISTAN, MANAT TURCOMANO', 1, GETDATE()),
		('TND', 'TUNISIA, DINAR TUNECINO', 1, GETDATE()),
		('TOP', 'TONGA, PA''ANGA', 1, GETDATE()),
		('TRY', 'TURQUIA, LIRA TURCA', 1, GETDATE()),
		('TTD', 'TRINIDAD Y TOBAGO, DOLAR DE TRINIDAD Y TOBAGO', 1, GETDATE()),
		('TWD', 'TAIWAN, NUEVO DOLAR TAIWANES', 1, GETDATE()),
		('TZS', 'TANZANIA, CHELIN TANZANO', 1, GETDATE()),
		('UAH', 'UCRANIA, GRIVNA', 1, GETDATE()),
		('UGX', 'UGANDA, CHELIN UGANDES', 1, GETDATE()),
		('UYU', 'URUGUAY, PESO URUGUAYO', 1, GETDATE()),
		('UZS', 'UZBEKISTAN, SOM UZBEKO', 1, GETDATE()),
		('VEF', 'VENEZUELA, BOLIVAR', 1, GETDATE()),
		('VND', 'VIETNAM, DONG VIETNAMITA', 1, GETDATE()),
		('VUV', 'VANUATU, VATU', 1, GETDATE()),
		('WST', 'SAMOA, TALA', 1, GETDATE()),
		('XAF', 'FRANCO CFA DE AFRICA CENTRAL', 1, GETDATE()),
		('XCD', 'DOLAR DEL CARIBE ORIENTAL', 1, GETDATE()),
		('XOF', 'FRANCO CFA DE AFRICA OCCIDENTAL', 1, GETDATE()),
		('XPF', 'FRANCO CFP', 1, GETDATE()),
		('XSU', 'SUCRE', 1, GETDATE()),
		('YER', 'YEMEN, RIAL YEMENI', 1, GETDATE()),
		('ZAR', 'SURAFRICA, RAND', 1, GETDATE()),
		('ZMW', 'ZAMBIA, KWACHA ZAMBIANO', 1, GETDATE()),
		('ZWL', 'ZIMBABWE, DOLAR ZIMBABUENSE', 1, GETDATE());

INSERT INTO [Adua].[tbIncoterm]([inco_Codigo], [inco_Descripcion], [usua_UsuarioCreacion], [inco_FechaCreacion])
VALUES	('CFR', 'COSTO Y FLETE', 1, GETDATE()),
		('CIF', 'COSTO,SEGURO Y FLETE', 1, GETDATE()),
		('CIP', 'TRANSPORTE Y SEGURO', 1, GETDATE()),
		('CPT', 'TRANSPORTE PAGADO', 1, GETDATE()),
		('DAF', 'ENTREGAS EN FRONTERA', 1, GETDATE()),
		('DAP', 'ENTREGA EN LUGAR', 1, GETDATE()),
		('DDP', 'DERECHOS PAGADOS', 1, GETDATE()),
		('DDU', 'DERECHOS NO PAGADOS', 1, GETDATE()),
		('DEQ', 'ENTRGADAS EN MUELLE', 1, GETDATE()),
		('DES', 'ENTREGA SOBRE BUQUE', 1, GETDATE()),
		('DPU', 'ENTREGADA EN LUGAR DESCARGADA', 1, GETDATE()),
		('EXW', 'EN FABRICA', 1, GETDATE()),
		('FAS', 'LIBRE COSTADO BUQUE', 1, GETDATE()),
		('FCA', 'FRANCO TRANSPORTISTA', 1, GETDATE()),
		('FOB', 'LIBRE PUESTA A BORDO', 1, GETDATE());


INSERT INTO [Adua].[tbFormasdePago]([fopa_Descripcion], [usua_UsuarioCreacion], [fopa_FechaCreacion])
VALUES	('CHEQUE BANCARIO/CHEQUE PERSONAL', 1, GETDATE()),
		('CARTA DE CREDITO', 1, GETDATE()),
		('EFECTIVO', 1, GETDATE()),
		('GIRO BANCARIO', 1, GETDATE()),
		('OTRO', 1, GETDATE()),
		('PAGO ANTICIPADO', 1, GETDATE()),
		('PAGO ELECTRONICO', 1, GETDATE()),
		('TRANSFERENCIA BANCARIA', 1, GETDATE()),
		('TARJETA DE CREDITO', 1, GETDATE());


INSERT INTO [Prod].[tbProcesos](proc_Descripcion, usua_UsuarioCreacion, proc_FechaCreacion)
VALUES('pROCESO',1,'05-10-2021')


INSERT INTO [Prod].[tbClientes](clie_Nombre_O_Razon_Social, clie_Direccion, clie_RTN, clie_Nombre_Contacto, clie_Numero_Contacto, clie_Correo_Electronico, clie_FAX, usua_UsuarioCreacion, clie_FechaCreacion)
values('Miguel','Direccionando','054564','Josue','465465','sdkjssdasd','45454',1,'05-10-2021')

INSERT INTO [Gral].[tbEmpleados](empl_Nombres, empl_Apellidos, empl_DNI, escv_Id, empl_Sexo, empl_FechaNacimiento, empl_Telefono, empl_DireccionExacta, pvin_Id, empl_CorreoElectronico, carg_Id, empl_EsAduana, usua_UsuarioCreacion, empl_FechaCreacion)
values('Mario','Acasa','06412',1,'M','05-10-2022','97856222','A la orilla de mi casa',1,'La acasa',1,1,1,'05-06-2000')

INSERT INTO [Prod].[tbMarcasMaquina](marq_Nombre, usua_UsuarioCreacion, marq_FechaCreacion)
VALUES('Maquita',1,'05-10-2022')


INSERT INTO [Prod].[tbFuncionesMaquina](func_Nombre, usua_UsuarioCreacion, func_FechaCreacion)
VALUES('Funcionando',1,'05-11-2022')


INSERT INTO [Prod].[tbModulos](modu_Nombre, proc_Id, empr_Id, usua_UsuarioCreacion, modu_FechaCreacion)
VALUES('Nombrando',1,1,1,'05-10-2021')


insert into [Prod].[tbModelosMaquina](mmaq_Nombre, marq_Id, func_Id, mmaq_Imagen, usua_UsuarioCreacion, mmaq_FechaCreacion)
VALUES('Maquinaria',1,1,'https://www.google.com/url?sa=i&url=https%3A%2F%2Fes.wikipedia.org%2Fwiki%2FM%25C3%25A1quina_herramienta&psig=AOvVaw2Z7iOnlL73w4kM6faV6xVd&ust=1689787202888000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCMC774LimIADFQAAAAAdAAAAABAE',1,'05-10-2021')


INSERT INTO [Adua].[tbNivelesComerciales](nico_Codigo, [nico_Descripcion], [usua_UsuarioCreacion], [nico_FechaCreacion])
VALUES ('DIS', 'DISTRIBUIDOR', 1, GETDATE()),
	   ('MAY', 'MAYORISTA', 1, GETDATE()),
	   ('MIN', 'MINORISTA', 1, GETDATE()),
	   ('OTR', 'OTROS', 1, GETDATE())

INSERT INTO [Adua].[tbAduanas](adua_Codigo, [adua_Nombre], [adua_Direccion_Exacta], [usua_UsuarioCreacion], [adua_FechaCreacion])
VALUES	('0001', 'ADUANA AMAPALA', '1st Street, Amapala, Valle, Honduras', 1, GETDATE()),
		('0002', 'ADUANA LA CEIBA', '2nd Avenue, La Ceiba, Atlántida, Honduras', 1, GETDATE()),
		('0003', 'ADUANA PUERTO HENECAN-SN LORENZO', '3rd Road, Puerto Henecán, San Lorenzo, Valle, Honduras', 1, GETDATE()),
		('0004', 'ADUANA PUERTO CORTES', '4th Street, Puerto Cortés, Cortés, Honduras', 1, GETDATE()),
		('0005', 'ADUANA PUERTO LEMPIRA', '5th Avenue, Puerto Lempira, Gracias a Dios, Honduras', 1, GETDATE()),
		('0006', 'ADUANA ROATAN', '6th Road, Roatán, Bay Islands, Honduras', 1, GETDATE()),
		('0007', 'GUARDATURA ROATAN', '7th Street, Roatán, Bay Islands, Honduras', 1, GETDATE()),
		('0008', 'ADUANA TELA', '8th Avenue, Tela, Atlántida, Honduras', 1, GETDATE()),
		('0009', 'ADUANA PUERTO CASTILLA', '9th Road, Puerto Castilla, Colón, Honduras', 1, GETDATE()),
		('0010', 'GUARDATURA GOLOSON-CEIBA', '10th Street, Golosón, La Ceiba, Atlántida, Honduras', 1, GETDATE()),
		('0011', 'ADUANA LA MESA', '11th Avenue, La Mesa, Lempira, Honduras', 1, GETDATE()),
		('0013', 'GUARDATURA LA MESA', '13th Road, La Mesa, Lempira, Honduras', 1, GETDATE()),
		('0014', 'ADUANA TONCONTIN', '14th Street, Tegucigalpa, Francisco Morazán, Honduras', 1, GETDATE()),
		('0015', 'GUARDATURA TONCONTIN', '15th Avenue, Tegucigalpa, Francisco Morazán, Honduras', 1, GETDATE()),
		('0016', 'PASO FRONTERIZO CORINTO HN-GT', '16th Road, Paso Fronterizo Corinto, Cortés, Honduras', 1, GETDATE()),
		('0017', 'ADUANA PALMEROLA', '17th Street, Comayagua, Comayagua, Honduras', 1, GETDATE()),
		('0018', 'GUARDATURA PALMEROLA', '18th Avenue, Comayagua, Comayagua, Honduras', 1, GETDATE()),
		('0020', 'ADUANA AGUA CALIENTE', '20th Road, Agua Caliente, Ocotepeque, Honduras', 1, GETDATE()),
		('0021', 'ADUANA MOCALEMPA', '21st Street, Mocálempa, Valle, Honduras', 1, GETDATE()),
		('0022', 'ADUANA LA CONCORDIA', '22nd Avenue, La Concordia, Copán, Honduras', 1, GETDATE()),
		('0023', 'ADUANA EL AMATILLO', '23rd Road, El Amatillo, Valle, Honduras', 1, GETDATE()),
		('0024', 'ADUANA EL FLORIDO', '24th Street, El Florido, Copán, Honduras', 1, GETDATE()),
		('0025', 'ADUANA EL POY', '25th Avenue, El Poy, Chalatenango, El Salvador', 1, GETDATE()),
		('0027', 'ADUANA LA FRATERNIDAD', '27th Road, La Fraternidad, Ocotepeque, Honduras', 1, GETDATE()),
		('0029', 'ADUANA GUASAULE', '29th Street, Guasaule, Chinandega, Nicaragua', 1, GETDATE()),
		('0034', 'ADUANA LAS MANOS', '34th Avenue, Las Manos, Ocotepeque, Honduras', 1, GETDATE()),
		('3004', 'ADUANA TECUN UMAN', 'Tecún Umán Bridge, International Bridge, Guatemala', 1, GETDATE()),
		('6001', 'ZOLI PUERTO CORTES', 'Puerto Cortés, Cortés, Honduras', 1, GETDATE()),
		('6003', 'ZOLI INHDELVA', 'Inhdelva Industrial Park, San Pedro Sula, Cortés, Honduras', 1, GETDATE()),
		('6005', 'CONSTRUCCIONES Y DESARROLLOS VICTOR', '5th Avenue, Tegucigalpa, Francisco Morazán, Honduras', 1, GETDATE()),
		('6011', 'HONDURAS AMERICAN TABACO SA (HATSA)', '11th Street, Danlí, El Paraíso, Honduras', 1, GETDATE()),
		('6012', 'CONFECCIONES INTERNACIONALES S.A. DE C.V.', '12th Avenue, San Pedro Sula, Cortés, Honduras', 1, GETDATE()),
		('6013', 'ZOLI NOVEM CAR', 'Novem Car Factory, Choloma, Cortés, Honduras', 1, GETDATE()),
		('6017', 'ZOLI DELI DE HONDURAS S.A. DE C.V.', 'Deli de Honduras, Villanueva, Cortés, Honduras', 1, GETDATE()),
		('6021', 'ZOLI EMPACADORA DE CAMARONES SANTA INES', 'Empacadora de Camarones, Puerto Cortés, Cortés, Honduras', 1, GETDATE()),
		('6022', 'ZOLI EMPACADORA DE PRODUCTO ACUATICOS SAN LORENZO', '123 Main Street, San Lorenzo, Honduras', 1, GETDATE()),
		('6023', 'ZOLI HATSA (DANLI)', '456 Elm Avenue, Danli, Honduras', 1, GETDATE()),
		('6029', 'ZOLI CONFECCIONES MONZINI S.A.', '789 Oak Road, Tegucigalpa, Honduras', 1, GETDATE()),
		('6030', 'ZOLI METROPOLITANA JACALEAPA', '10 Maple Lane, Jacaleapa, Honduras', 1, GETDATE()),
		('6035', 'ZOLI ORVASA', '55 Pine Street, San Pedro Sula, Honduras', 1, GETDATE()),
		('6043', 'ZOLI COMPONENTES ELECTRONICOS', '100 Cedar Avenue, Choloma, Honduras', 1, GETDATE()),
		('6045', 'ZOLI CLASIF. Y EXPORT. TABACO', '200 Walnut Drive, El Progreso, Honduras', 1, GETDATE()),
		('6047', 'ZOLI IBEROAMERICANA DE MARISCO', '300 Cherry Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6048', 'ZOLI CARACOL KNITS', '400 Oakwood Street, Puerto Cortes, Honduras', 1, GETDATE()),
		('6056', 'ASTRO CARTON HONDURAS SA DE CV', '500 Maple Avenue, Tela, Honduras', 1, GETDATE()),
		('6059', 'ZOLI MANUFACTURERA CEIBEÑA', '600 Elm Street, Ceiba, Honduras', 1, GETDATE()),
		('6060', 'ZOLI ATUTO', '700 Pine Lane, Atuto, Honduras', 1, GETDATE()),
		('6064', 'ZOLI TABACOS DE DANLI', '800 Cedar Road, Danli, Honduras', 1, GETDATE()),
		('6065', 'ZOLI COTTONWISE TEXTILES HOND.', '900 Walnut Drive, Choloma, Honduras', 1, GETDATE()),
		('6067', 'ZOLI WOONG CHUN HOND.S.A.', '1000 Cherry Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6068', 'ZONA LIBRE HONDURAS SA DE CV', '1100 Oakwood Street, Tegucigalpa, Honduras', 1, GETDATE()),
		('6073', 'ZOLI ZIP SAN MIGUEL VI', '1200 Maple Avenue, San Miguel, Honduras', 1, GETDATE()),
		('6074', 'PARQUE INDUSTRIAL BUFALO S.A.', '1300 Elm Street, La Paz, Honduras', 1, GETDATE()),
		('6075', 'GRUPO J SOCIEDAD ANONIMA', '1400 Pine Lane, Comayagua, Honduras', 1, GETDATE()),
		('6077', 'ZONA INDUSTRIAL DE EXPORTACION BUENAVISTA SA', '1500 Cedar Road, Siguatepeque, Honduras', 1, GETDATE()),
		('6078', 'ZOLI ZIP CHOLOMA', '1600 Walnut Drive, Choloma, Honduras', 1, GETDATE()),
		('6079', 'ZIP EL PORVENIR', '1700 Cherry Lane, El Provenir, Honduras', 1, GETDATE()),
		('6083', 'ZOLI LEAR AUTOMOTIVE EDDS, HOND.', '1800 Oakwood Street, San Pedro Sula, Honduras', 1, GETDATE()),
		('6085', 'ZOLI ZIP SAN JOSE', '1900 Elm Street, San Jose, Honduras', 1, GETDATE()),
		('6091', 'ZOLI GRANDWAY HONDURAS, S. DE R.L.', '2000 Pine Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6093', 'ZOLI U.S. YACHTS S. DE R.L.', '2100 Cedar Road, La Ceiba, Honduras', 1, GETDATE()),
		('6095', 'ZOLI ZIP CALPULES', '2200 Walnut Drive, Calpules, Honduras', 1, GETDATE()),
		('6100', 'ZOLI AQUAFINCA ST. PETER FISH', '2300 Cherry Lane, Tela, Honduras', 1, GETDATE()),
		('6102', 'AEREO -IMPEX S.A.', '2400 Oakwood Street, Puerto Cortes, Honduras', 1, GETDATE()),
		('6103', 'ZOLI C.B.I., S.A.', '2500 Elm Street, Choloma, Honduras', 1, GETDATE()),
		('6106', 'ZOLI. CIA. OPERAD.ZIP RIO BLANCO', '2600 Pine Lane, Rio Blanco, Honduras', 1, GETDATE()),
		('6107', 'ZOLI EMPACADORA LITORAL, S.A.', '2700 Cedar Road, La Ceiba, Honduras', 1, GETDATE()),
		('6108', 'NEW HOLLAND LINGERIE DE HONDURAS SA', '2800 Walnut Drive, Tegucigalpa, Honduras', 1, GETDATE()),
		('6109', 'ZOLI AMERICA S.A. DE C.V.', '2900 Cherry Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6110', 'ZOLI AGENCIA J. E HANDAL S.A DE C.V', '3000 Oakwood Street, Choloma, Honduras', 1, GETDATE()),
		('6114', 'ZOLI PARQUE INDUSTRIAL REAL', '3100 Elm Street, Tegucigalpa, Honduras', 1, GETDATE()),
		('6118', 'ZOLI HONDURAS ELECT. DISTRIB. SYST.', '3200 Pine Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6121', 'ZOLI S. HONDURAS', '3300 Cedar Road, Tegucigalpa, Honduras', 1, GETDATE()),
		('6125', 'ZOLI GAS DEL CARIBE, S.A. DE C.V.', '3400 Walnut Drive, San Pedro Sula, Honduras', 1, GETDATE()),
		('6126', 'ZOLI INVERSIONES EL CACAO', '400 Magnolia Street, San Pedro Sula, Honduras', 1, GETDATE()),
		('6129', 'ZOLI  R.L.A. MANUFACTURING, SRL', '500 Oak Avenue, Tegucigalpa, Honduras', 1, GETDATE()),
		('6131', 'ZOLI FARM FRESH, S.A.', '600 Pine Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6132', 'ZOLI ZINMA EXPORT', '700 Cherry Lane, Danli, Honduras', 1, GETDATE()),
		('6136', 'ZOLI GOLFO AZUL', '800 Walnut Drive, San Lorenzo, Honduras', 1, GETDATE()),
		('6137', 'ZOLI BANG SAN  HONDURAS, S. DE R.L.', '900 Cedar Road, Choloma, Honduras', 1, GETDATE()),
		('6138', 'ZOLI MICROENVASES', '1000 Elm Street, San Miguel, Honduras', 1, GETDATE()),
		('6142', 'ZOLI FOSFORERA CENTROAMERICANA', '1100 Pine Lane, Tela, Honduras', 1, GETDATE()),
		('6143', 'ZOLI  ALAMODE S.A.', '1200 Oakwood Street, Puerto Cortes, Honduras', 1, GETDATE()),
		('6145', 'ZOLI TEXTILE SUPLY SERVICE S.ADE CV', '1300 Elm Avenue, Choloma, Honduras', 1, GETDATE()),
		('6146', 'ZOLI INVERSIONISTAS Y EXPORTADORES', '1400 Pine Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6148', 'ZOLI H.M.M DE HONDURAS S.A DE C.V', '1500 Cherry Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6149', 'ZOLI YODECO DE HONDURAS S A BUFALO', '1600 Oak Avenue, La Ceiba, Honduras', 1, GETDATE()),
		('6154', 'ZOLI YODECO (YORO)', '1700 Elm Street, Comayagua, Honduras', 1, GETDATE()),
		('6155', 'ZOLI YODECO DE HONDURAS S.A OLANCHO', '1800 Pine Lane, Siguatepeque, Honduras', 1, GETDATE()),
		('6159', 'ZOLI EL POLVORIN, S.A. DE C.V.', '1900 Cherry Lane, El Progreso, Honduras', 1, GETDATE()),
		('6160', 'AEREO -IMPEX S.A.', '2000 Oakwood Street, San Pedro Sula, Honduras', 1, GETDATE()),
		('6161', 'ZOLI PRIDE, S.A. DE C.V.', '2100 Elm Street, Tegucigalpa, Honduras', 1, GETDATE()),
		('6162', 'ZOLI SER.PROF. MADERA (SERPROMA)', '2200 Pine Lane, Danli, Honduras', 1, GETDATE()),
		('6163', 'ZOLI TECNOSUPPLIER S. DE R.L.', '2300 Cherry Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6164', 'ZONA INDUST. DE EXPORT. CHOLOMA II', '2400 Oakwood Street, Tela, Honduras', 1, GETDATE()),
		('6165', 'ZOLI ZIP AMARATECA', '2500 Elm Street, Puerto Cortes, Honduras', 1, GETDATE()),
		('6166', 'ZOLI GREEN VALLEY INDUSTRIAL PARK', '2600 Pine Lane, Choloma, Honduras', 1, GETDATE()),
		('6169', 'NOVA CHEM S DE RL DE CV', '2700 Cherry Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6172', 'ZOLI J.C. INTERNAT. INDUST. LAUNDRY', '2800 Oakwood Street, Tegucigalpa, Honduras', 1, GETDATE()),
		('6175', 'ZOLI ALIMENTOS CONCENTRADOS  NACI.', '2900 Elm Street, Danli, Honduras', 1, GETDATE()),
		('6176', 'ZOLI MADERAS DE AMERICA', '3000 Pine Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6177', 'ZOLI VESTA TRADING SA', '3100 Cherry Lane, San Miguel, Honduras', 1, GETDATE()),
		('6178', 'ZOLI MARTEX FIBER INTERNATIONAL SRL', '3200 Oakwood Street, Tela, Honduras', 1, GETDATE()),
		('6179', 'ZOLI CENTRAL TEXTILES', '3300 Elm Street, Puerto Cortes, Honduras', 1, GETDATE()),
		('6180', 'ZOLI LA FLOR DE COPAN SAS', '3400 Pine Lane, Choloma, Honduras', 1, GETDATE()),
		('6182', 'ZOLI DE SULA S.A.', '3500 Cherry Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6184', 'ZOLI MARISCOS PERLA MAR, SRL', '3600 Oakwood Street, Tegucigalpa, Honduras', 1, GETDATE()),
		('6185', 'ZOLI INVERSIONES MATERIALES, SRL', '3700 Elm Street, La Ceiba, Honduras', 1, GETDATE()),
		('6186', 'ZOLI GILDAN HOND. HOSIERY FACTORY', '3800 Pine Lane, Danli, Honduras', 1, GETDATE()),
		('6187', 'ZOLI GILDAN CHOLOMA TEXTILES, S.A.', '3900 Cherry Lane, Siguatepeque, Honduras', 1, GETDATE()),
		('6188', 'RECYCLERS GROUP OF HONDURAS S DE R', '4000 Oakwood Street, Comayagua, Honduras', 1, GETDATE()),
		('6191', 'ZOLI MANUFACTURAS DEL TROPICO', '4100 Elm Street, San Pedro Sula, Honduras', 1, GETDATE()),
		('6194', 'ZOLI EXPORT. DE CALIDAD DE HOND.', '4200 Pine Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6196', 'ZOLI INVERSIONES AMALGAMADAS', '4300 Cherry Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6197', 'ZOLI MOUNT DORA FARMS HONDURAS', '4400 Oakwood Street, Danli, Honduras', 1, GETDATE()),
		('6200', 'ZOLI MARINOS PESCADERIA, SRL', '4500 Elm Street, La Ceiba, Honduras', 1, GETDATE()),
		('6201', 'ZOLI HANIL HONDURAS, S.A. DE C.V.', '4600 Pine Lane, Puerto Cortes, Honduras', 1, GETDATE()),
		('6205', 'ZOLI PARQUES E INVER. INDUSTRIALES', '4700 Cherry Lane, Choloma, Honduras', 1, GETDATE()),
		('6208', 'ZOLI HARNES CONT. EQUIPMENT HOND.', '4800 Oakwood Street, San Pedro Sula, Honduras', 1, GETDATE()),
		('6209', 'ZOLI FORMAS TERMICAS, S.A. DE C.V.', '4900 Elm Street, Tegucigalpa, Honduras', 1, GETDATE()),
		('6210', 'ENERGIA Y VAPOR S.A. DE C.V.', '5000 Pine Lane, Danli, Honduras', 1, GETDATE()),
		('6211', 'ZOLI ACEITES Y DERIVADOS, S.A.', '5100 Cherry Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6212', 'ZOLI CORUMO INTERNACIONAL, SRL', '5200 Oakwood Street, Siguatepeque, Honduras', 1, GETDATE()),
		('6215', 'ZOLI AGROINDUSTRIAL PALMA REAL', '5300 Elm Street, Comayagua, Honduras', 1, GETDATE()),
		('6216', 'ZOLI AGRICOLA INDUSTRIAL CEIBEÑA S.', '5400 Pine Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6218', 'ZOLI ALTIA BUSINESS PARK', '5500 Cherry Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6219', 'ZOLI  VOGUE CORPORATION INTERNATIO.', '5600 Oakwood Street, La Ceiba, Honduras', 1, GETDATE()),
		('6220', 'ZOLI  SCANDINAVIAN TOBACCO GROUP', '5700 Elm Street, Puerto Cortes, Honduras', 1, GETDATE()),
		('6221', 'ZOLI RECICLAJE DIAMANTE', '5800 Pine Lane, Choloma, Honduras', 1, GETDATE()),
		('6222', 'ZOLI MANUCHAR HONDURAS', '5900 Cherry Lane, San Miguel, Honduras', 1, GETDATE()),
		('6223', 'S & P RECICLYNG HONDURAS S.A. DE', '6000 Oakwood Street, Tela, Honduras', 1, GETDATE()),
		('6225', 'PALMAS CENTROAMERICANAS (PALCASA)', '6100 Elm Street, Puerto Cortes, Honduras', 1, GETDATE()),
		('6226', 'HENDRIX AND DAIL DE HONDURAS SA', '6200 Pine Lane, Choloma, Honduras', 1, GETDATE()),
		('6227', 'RM SEWING SUPPLY, S. DE R. L.', '6300 Cherry Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6228', 'ZONA LIBRE ST ANDRREWS S.A. DE C.V.', '6400 Oakwood Street, Tegucigalpa, Honduras', 1, GETDATE()),
		('6229', 'METALES Y ALEACIONES S A DE C V', '6500 Elm Street, Danli, Honduras', 1, GETDATE()),
		('6230', 'CHEMICAL MANUFACTURING AND EXPORTIN', '6600 Pine Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6231', 'ZOLI ALMACEN FISCAL P SA DE CV', '6700 Cherry Lane, Siguatepeque, Honduras', 1, GETDATE()),
		('6232', 'ZONA LIBRE LAS AMERICAS SA DE CV', '6800 Oakwood Street, Comayagua, Honduras', 1, GETDATE()),
		('6233', 'NOVA HONDURAS ZONA LIBRE SA', '6900 Elm Street, San Pedro Sula, Honduras', 1, GETDATE()),
		('6234', 'NEW HOLLAND LINGERIE DE HONDURAS', '7000 Pine Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6235', 'CENTRAL AMERICAN TRAILER REPAIR SRL', '7100 Cherry Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6236', 'HONDURAS CONTAINER SERVICE SA DE CV', '7200 Oakwood Street, Siguatepeque, Honduras', 1, GETDATE()),
		('6237', 'ELASTICOS CENTROAMERICANOS Y TEXTIL', '7300 Pine Lane, Comayagua, Honduras', 1, GETDATE()),
		('6238', 'ELASTICOS CENTROAMERICANOS SA DE CV', '7400 Cherry Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6239', 'GENESIS APPAREL', '7500 Oakwood Street, Tegucigalpa, Honduras', 1, GETDATE()),
		('6240', 'HILOS A&E DE HONDURAS', '7600 Pine Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6241', 'INVERSIONES LAS FLORES', '7700 Cherry Lane, Puerto Cortes, Honduras', 1, GETDATE()),
		('6242', 'RIO NANCE AGRO-INDUSTRIAL SA DE CV', '7800 Oakwood Street, Choloma, Honduras', 1, GETDATE()),
		('6244', 'INDUSTRIA HONDUREÑA DE MECHAS SA CV', '7900 Pine Lane, San Miguel, Honduras', 1, GETDATE()),
		('6245', 'ARTESANOS SA DE CV', '8000 Cherry Lane, Tela, Honduras', 1, GETDATE()),
		('6246', 'FIBRAS Y TEXTILES SA DE CV', '8100 Oakwood Street, Puerto Cortes, Honduras', 1, GETDATE()),
		('6247', 'YKK HONDURAS SA', '8200 Pine Lane, Choloma, Honduras', 1, GETDATE()),
		('6248', 'EUROMODAS SA', '8300 Cherry Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6249', 'CAOBA D EHONDURAS SA D ECV', '8400 Oakwood Street, Tegucigalpa, Honduras', 1, GETDATE()),
		('6251', 'WINTEX DE HONDURAS SA DE CV', '8500 Pine Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6253', 'INDUSTRIAS CONTINENTAL S DE RL', '8600 Cherry Lane, Puerto Cortes, Honduras', 1, GETDATE()),
		('6254', 'TECNO SUPPLIER SA DE CV', '8700 Oakwood Street, Comayagua, Honduras', 1, GETDATE()),
		('6255', 'INVERSIONES LA VICTORIA', '8800 Pine Lane, Siguatepeque, Honduras', 1, GETDATE()),
		('6256', 'COFRADIA INDUSTRIAL PARK SA', '8900 Cherry Lane, Danli, Honduras', 1, GETDATE()),
		('6257', 'CIRSA HONDURAS S DE RL DE CV', '9000 Oakwood Street, La Ceiba, Honduras', 1, GETDATE()),
		('6258', 'RECYCLERS GROUP OF HONDURAS S DE R', '9100 Pine Lane, Tela, Honduras', 1, GETDATE()),
		('6259', 'GRUPO INDUSTRIAL RIO BLANQUITO SA', '9200 Cherry Lane, Puerto Cortes, Honduras', 1, GETDATE()),
		('6260', 'ELECTROQUIMICA DE HONDURAS SA', '9300 Oakwood Street, San Pedro Sula, Honduras', 1, GETDATE()),
		('6261', 'MAQUILA Y CONFECCIONES AXIID INTERN', '9400 Pine Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6262', 'SJ MARIOL SA DE CV', '9500 Cherry Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6263', 'PALMA DEL BAJO AGUAN SA', '9600 Oakwood Street, Comayagua, Honduras', 1, GETDATE()),
		('6264', 'ETHAN ALLEN SA', '9700 Pine Lane, Siguatepeque, Honduras', 1, GETDATE()),
		('6265', 'RECICLAJE Y METALES DE CORTES S RL', '9800 Cherry Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6267', 'TABACOS DEL ORIENTE S DE RL', '9900 Oakwood Street, Tegucigalpa, Honduras', 1, GETDATE()),
		('6269', 'AQUAFEED SA DE CV', '10000 Pine Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6270', 'HILOS Y MECHAS SA DE CV', '10100 Cherry Lane, Puerto Cortes, Honduras', 1, GETDATE()),
		('6271', 'C Y D S.A. DE C.V.', '10200 Oakwood Street, Comayagua, Honduras', 1, GETDATE()),
		('6272', 'AGROINDUSTRIAL DEL VALLE S A', '10300 Pine Lane, Siguatepeque, Honduras', 1, GETDATE()),
		('6273', 'FARM FRESH SA - LA PAZ', '10400 Cherry Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6274', 'FARM FRESH SA - COMAYAGUA', '10500 Oakwood Street, Tegucigalpa, Honduras', 1, GETDATE()),
		('6275', 'PESCA DEL ATLANTICO S DE RL', '10600 Pine Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6276', 'ADMINISTRACION DE CALL CENTERS, S.A', '10700 Cherry Lane, Puerto Cortes, Honduras', 1, GETDATE()),
		('6277', 'INVERSIONES EMCO SA DE CV', '10800 Oakwood Street, Comayagua, Honduras', 1, GETDATE()),
		('6278', 'AGROECOLOGICA INTERNACIONAL S DE RL', '10900 Pine Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6279', 'CHOCOLATE DEL CARIBE S.A.', '11000 Cherry Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6280', 'CONVERTIDORA DE FIBRAS SA DE CV', '11100 Oakwood Street, La Ceiba, Honduras', 1, GETDATE()),
		('6281', 'SOLUCIONES QUIMICAS INDUSTRIALES SA', '11200 Pine Lane, Puerto Cortes, Honduras', 1, GETDATE()),
		('6282', 'PRODUCTOS FRESCOS DEL MAR SN CARLOS', '11300 Cherry Lane, Comayagua, Honduras', 1, GETDATE()),
		('6283', 'EXTRUM SA DE CV', '11400 Oakwood Street, Siguatepeque, Honduras', 1, GETDATE()),
		('6284', 'DICKIES DE HONDURAS SA', '11500 Pine Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6285', 'ALUCOM INTERNATIONAL S A DE C V', '11600 Cherry Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6286', 'PALMEROS DEL AGUAN SA (PALMASA)', '11700 Oakwood Street, La Ceiba, Honduras', 1, GETDATE()),
		('6287', 'NUTRIAVES SA DE CV', '11800 Pine Lane, Puerto Cortes, Honduras', 1, GETDATE()),
		('6288', 'RECYCLERS GROUP OF HONDURAS S DE R', '11900 Cherry Lane, Comayagua, Honduras', 1, GETDATE()),
		('6289', 'REPLAST DE HONDURAS S DE RL', '12000 Oakwood Street, Siguatepeque, Honduras', 1, GETDATE()),
		('6290', 'PROCESA SA DE CV', '12100 Pine Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6291', 'GRUPO RODRIGUEZ', '12200 Cherry Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6292', 'ZONA LIBRE LAS AMERICAS SA DE CV', '12300 Oakwood Street, La Ceiba, Honduras', 1, GETDATE()),
		('6293', 'HILOTEX, S.A. DE C.V.', '12400 Pine Lane, Puerto Cortes, Honduras', 1, GETDATE()),
		('6294', 'MOLINOS DE HONDURAS, SA', '12500 Cherry Lane, Comayagua, Honduras', 1, GETDATE()),
		('6295', 'BESCO S DE R L', '12600 Oakwood Street, Siguatepeque, Honduras', 1, GETDATE()),
		('6296', 'INDUSTRIAS CARNEAS DEL SUR SA', '12700 Pine Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6297', 'ZOLI JAMEE EXPORT, S.A.', '12800 Cherry Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6298', 'FORESTAL LATINOAMERICANA SA DE CV', '12900 Oakwood Street, La Ceiba, Honduras', 1, GETDATE()),
		('6299', 'ZOLI EXPORTADORA  SAMOA', '13000 Pine Lane, Puerto Cortes, Honduras', 1, GETDATE()),
		('6300', 'ARNESES Y ENSAMBLES S DE RL', '13100 Cherry Lane, Comayagua, Honduras', 1, GETDATE()),
		('6301', 'O. R. S. DE HONDURAS S. DE R. L.', '13200 Oakwood Street, Siguatepeque, Honduras', 1, GETDATE()),
		('6302', 'EXPORTADORA ECO INDUSTRIAL SA DE C', '13300 Pine Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6303', 'COMPAÑIA INTERNACIONAL DE CONFECCIO', '13400 Cherry Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6304', 'LOS ROBLES SA DE CV', '13500 Oakwood Street, La Ceiba, Honduras', 1, GETDATE()),
		('6305', 'INDUSTRIAS CONTINENTAL S DE RL', '13600 Pine Lane, Puerto Cortes, Honduras', 1, GETDATE()),
		('6306', 'SISTEMAS DE ENERGIA DE HONDURAS SA', '13700 Cherry Lane, Comayagua, Honduras', 1, GETDATE()),
		('6307', 'FLAMES INTERNATIONAL S DE RL', '13800 Oakwood Street, Siguatepeque, Honduras', 1, GETDATE()),
		('6308', 'PALMAS INTERNATIONAL SA DE CV', '13900 Pine Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6309', 'PARQUE INDUSTRIAL DE CHOLIMA SA', '14000 Cherry Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6310', 'SANITARIOS CAIRO SA', '14100 Oakwood Street, La Ceiba, Honduras', 1, GETDATE()),
		('6311', 'SADELCA DE HONDURAS S DE RL', '14200 Pine Lane, Puerto Cortes, Honduras', 1, GETDATE()),
		('6312', 'YKK HONDURAS SA DE CV', '14300 Cherry Lane, Comayagua, Honduras', 1, GETDATE()),
		('6313', 'EUROMODAS SA', '14400 Oakwood Street, Siguatepeque, Honduras', 1, GETDATE()),
		('6314', 'CAOBA DE HONDURAS SA DE CV', '14500 Pine Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6315', 'CORPORACION CARTONERA & IMPRESOS 3J', '12345 Elm Street, San Pedro Sula, Honduras', 1, GETDATE()),
		('6316', 'BIOCOMBUSTIBLES Y SALUD S A DE C', '67890 Oak Avenue, Tegucigalpa, Honduras', 1, GETDATE()),
		('6317', 'SAN JUAN INNOVATION PARK SA DE CV', '24680 Maple Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6318', 'PRIDE PERFORMANCE FABRICS, S.A. DE', '13579 Pine Road, Puerto Cortes, Honduras', 1, GETDATE()),
		('6320', 'CIA AGRICOLA IND CEIBEÑA S A DE CV', '97531 Birch Street, Comayagua, Honduras', 1, GETDATE()),
		('6321', 'ALMACENADORA DE MATERIALES A GRANEL', '86420 Cedar Avenue, Siguatepeque, Honduras', 1, GETDATE()),
		('6322', 'GUAYACAN FARMS S A DE C V', '24680 Elm Street, San Pedro Sula, Honduras', 1, GETDATE()),
		('6323', 'PROGRESSIVE ENERGY CORPORATION SA D', '13579 Oak Avenue, Tegucigalpa, Honduras', 1, GETDATE()),
		('6324', 'Q-APPAREL, SOCIEDAD ANONIMA', '97531 Maple Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6325', 'BIOLARVA AQUACULTURE SA', '86420 Pine Road, Puerto Cortes, Honduras', 1, GETDATE()),
		('6326', 'BIOLARVA AQUACULTURE SA', '12345 Cedar Avenue, Comayagua, Honduras', 1, GETDATE()),
		('6327', 'INVERSIONES MI PULPE S DE R L', '67890 Elm Street, Siguatepeque, Honduras', 1, GETDATE()),
		('6328', 'LEVANTER SA DE CV', '24680 Oak Avenue, San Pedro Sula, Honduras', 1, GETDATE()),
		('6329', 'ALMACENADORA DE MATERIALES A GRANEL', '13579 Maple Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6330', 'REMA S.A.', '97531 Birch Street, La Ceiba, Honduras', 1, GETDATE()),
		('6331', 'FABRICA HONDUREÑA DE RECICLAJE S', '86420 Cedar Avenue, Puerto Cortes, Honduras', 1, GETDATE()),
		('6332', 'GRAN COSTA HONDURAS S DE R L', '12345 Oak Avenue, Comayagua, Honduras', 1, GETDATE()),
		('6333', 'BENEFICIO DE CAFE INLOHER S DE RL', '67890 Maple Lane, Siguatepeque, Honduras', 1, GETDATE()),
		('6334', 'CARIBBEAN APPETIZERS SA DE CV', '24680 Elm Street, San Pedro Sula, Honduras', 1, GETDATE()),
		('6335', 'SAN SERVICES S DE RL DE CV', '13579 Oak Avenue, Tegucigalpa, Honduras', 1, GETDATE()),
		('6336', 'CYGNUS PACIFIC S A DE C V', '97531 Maple Lane, La Ceiba, Honduras', 1, GETDATE()),
		('6337', 'TABLEROS DE HONDURAS SA DE CV', '86420 Birch Street, Puerto Cortes, Honduras', 1, GETDATE()),
		('6338', 'LEVANTER SA DE CV', '12345 Cedar Avenue, Comayagua, Honduras', 1, GETDATE()),
		('6339', 'BIJAO ELECTRIC COMPANY SA DE C.V', '67890 Elm Street, Siguatepeque, Honduras', 1, GETDATE()),
		('6340', 'INHDELVA SPS S.A. DE C.V.', '24680 Oak Avenue, San Pedro Sula, Honduras', 1, GETDATE()),
		('6341', 'GILDAN HONDURAS PROPERTIES S DE R L', '13579 Maple Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6342', 'INGENIERIA OPERACION PLANTAS TRATAM', '97531 Birch Street, La Ceiba, Honduras', 1, GETDATE()),
		('6343', 'INVERSIONES ECOTEK SOCIEDAD ANONIMA', '86420 Cedar Avenue, Puerto Cortes, Honduras', 1, GETDATE()),
		('6344', 'EXPORTADORA E IMPORTADORA LA SIRENA', '12345 Elm Street, Comayagua, Honduras', 1, GETDATE()),
		('6345', 'CORAL BAY SA DE CV', '67890 Oak Avenue, Siguatepeque, Honduras', 1, GETDATE()),
		('6346', 'COFFEE PLANET CORPORATION SA DE CV', '24680 Maple Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6347', 'ZONA LIBRE PRIDE, S.A. DE C.V,', '13579 Pine Road, Tegucigalpa, Honduras', 1, GETDATE()),
		('6348', 'CAFETALEROS DE HONDURAS S DE RL CV', '97531 Cedar Avenue, La Ceiba, Honduras', 1, GETDATE()),
		('6349', 'PARTNER HERO CENTRAL AMERICA SRL CV', '86420 Elm Street, Puerto Cortes, Honduras', 1, GETDATE()),
		('6350', 'CORPORACION ANDIFAR, S. A. DE C. V.', '12345 Maple Lane, Comayagua, Honduras', 1, GETDATE()),
		('6351', 'CORUMO INTERNACIONAL S DE RL DE CV', '67890 Birch Street, Siguatepeque, Honduras', 1, GETDATE()),
		('6352', 'AVANZA LOGISTICS SA DE CV', '24680 Oak Avenue, San Pedro Sula, Honduras', 1, GETDATE()),
		('6353', 'CORPORACION ATAMAR, S.A.', '13579 Cedar Avenue, Tegucigalpa, Honduras', 1, GETDATE()),
		('6354', 'LABORATORIOS KARNEL, S.A', '97531 Elm Street, La Ceiba, Honduras', 1, GETDATE()),
		('6355', 'CALZADOS DE HONDURAS S A', '86420 Maple Lane, Puerto Cortes, Honduras', 1, GETDATE()),
		('6356', 'TELEPERFORMANCE, SOCIEDAD ANONIMA', '12345 Cedar Avenue, Comayagua, Honduras', 1, GETDATE()),
		('6357', 'PROCESADORA DEL CARIBE S.A DE C.V.', '67890 Elm Street, Siguatepeque, Honduras', 1, GETDATE()),
		('6358', 'SAN JUAN INNOVATION PARK SA DE CV', '24680 Oak Avenue, San Pedro Sula, Honduras', 1, GETDATE()),
		('6359', 'ALTIA BUSINESS PARK S.A. DE C.V.', '13579 Maple Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6360', 'ZABA INDUSTRIES, S. DE R. L. DE C.', '97531 Birch Street, La Ceiba, Honduras', 1, GETDATE()),
		('6361', 'TABACO MAYA S DE RL', '86420 Cedar Avenue, Puerto Cortes, Honduras', 1, GETDATE()),
		('6362', 'CRC BPO SOLUTIONS S. DE R.L.', '12345 Elm Street, Comayagua, Honduras', 1, GETDATE()),
		('6363', 'GRUPO ALCA, S.A. DE C.V.', '67890 Oak Avenue, Siguatepeque, Honduras', 1, GETDATE()),
		('6364', 'UNION DE FINCAS CAMARONERAS SOCIEDAD ANONIMA DE CA', '24680 Maple Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6365', 'ALTIA BUSINESS PARK SA DE CV', '13579 Oak Avenue, Tegucigalpa, Honduras', 1, GETDATE()),
		('6366', 'DEL MAR APPAREL S. A.', '97531 Cedar Avenue, La Ceiba, Honduras', 1, GETDATE()),
		('6367', 'POWERS ATHLETIC DE HONDURAS SOCIEDAD ANONIMA DE CA', '86420 Elm Street, Puerto Cortes, Honduras', 1, GETDATE()),
		('6368', 'PRIDE YARN, S. DE R.L', '12345 Maple Lane, Comayagua, Honduras', 1, GETDATE()),
		('6369', 'EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A', '67890 Birch Street, Siguatepeque, Honduras', 1, GETDATE()),
		('6370', 'EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A', '24680 Oak Avenue, San Pedro Sula, Honduras', 1, GETDATE()),
		('6371', 'EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A', '13579 Cedar Avenue, Tegucigalpa, Honduras', 1, GETDATE()),
		('6372', 'EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A', '97531 Elm Street, La Ceiba, Honduras', 1, GETDATE()),
		('6373', 'EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A', '86420 Maple Lane, Puerto Cortes, Honduras', 1, GETDATE()),
		('6374', 'EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A', '12345 Cedar Avenue, Comayagua, Honduras', 1, GETDATE()),
		('6375', 'EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A', '67890 Elm Street, Siguatepeque, Honduras', 1, GETDATE()),
		('6376', 'EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A', '24680 Oak Avenue, San Pedro Sula, Honduras', 1, GETDATE()),
		('6377', 'EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A', '13579 Cedar Avenue, Tegucigalpa, Honduras', 1, GETDATE()),
		('6378', 'EMPACADORA DE PRODUCTOS ACUATICOS SAN LORENZO S.A', '97531 Elm Street, La Ceiba, Honduras', 1, GETDATE()),
		('6379', 'PLASTICOS INDUSTRIALES HONDUREÑOS SA DE CV', '86420 Maple Lane, Puerto Cortes, Honduras', 1, GETDATE()),
		('6380', 'EXPORTADORA AGRICOLA MESOAMERICANA, SOCIEDAD ANONI', '12345 Cedar Avenue, Comayagua, Honduras', 1, GETDATE()),
		('6381', 'RESULTS HONDURAS, S.A.', '67890 Elm Street, Siguatepeque, Honduras', 1, GETDATE()),
		('6382', 'ZONA LIBRE GREEN VALLEY INDUSTRIAL PARK SA DE CV', '24680 Oak Avenue, San Pedro Sula, Honduras', 1, GETDATE()),
		('6383', 'SANTA LUCIA DEL PARAISO, S.A. DE C.V.', '13579 Maple Lane, Tegucigalpa, Honduras', 1, GETDATE()),
		('6384', 'RIVERMAR LARVICULTURA S. DE R.L.', '97531 Birch Street, La Ceiba, Honduras', 1, GETDATE()),
		('6385', 'ACUARIUS, S DE R.L. DE C.V.', '86420 Cedar Avenue, Puerto Cortes, Honduras', 1, GETDATE()),
		('6386', 'INDUSTRIA RESINERA BAHR, S. A.', '12345 Elm Street, Comayagua, Honduras', 1, GETDATE()),
		('6387', 'SOUTHERN APPAREL CONTRACTORS S.A.', '67890 Oak Avenue, Siguatepeque, Honduras', 1, GETDATE()),
		('6388', 'CORINFAR S A DE C V', '24680 Maple Lane, San Pedro Sula, Honduras', 1, GETDATE()),
		('6389', 'SOUTHERN APPAREL CONTRACTORS SA', '13579 Pine Road, Tegucigalpa, Honduras', 1, GETDATE()),
		('6392', 'GLOBAL PRINTING SOLUTIONS DE HONDURAS SOCIEDAD ANO', '97531 Cedar Avenue, La Ceiba, Honduras', 1, GETDATE()),
		('9100', 'ZEDE MORAZAN', '24680 Elm Street, San Pedro Sula, Honduras', 1, GETDATE()),
		('9101', 'ZEDE ORQUIDEA', '13579 Oak Avenue, Tegucigalpa, Honduras', 1, GETDATE()),
		('9102', 'ZEDE PROSPERA', '67890 Maple Lane, La Ceiba, Honduras', 1, GETDATE());





