-----------------INSERTS GENERAL

--**********CARGOS**********--
INSERT INTO [Gral].[tbCargos] ([carg_Nombre], usua_UsuarioCreacion, [carg_FechaCreacion])
VALUES ('Operario', 1, GETDATE()),
	   ('Supervisor de módulo', 1, GETDATE()),
	   ('Coordinador de logística', 1, GETDATE()),
	   ('Gerente de RRHH', 1, GETDATE())


--**********ESTADOS CIVILES**********--
INSERT INTO [Gral].[tbEstadosCiviles] (escv_Nombre, usua_UsuarioCreacion, escv_FechaCreacion)
VALUES ('Soltero(a)', 1, GETDATE()),
	   ('Casado(a)', 1, GETDATE()),
	   ('Divorciado(a)', 1, GETDATE()),
	   ('Viudo(a)', 1, GETDATE()),
	   ('Unión Libre', 1, GETDATE())
	   

--**********OFICINAS**********--
INSERT INTO [Gral].[tbOficinas] ([ofic_Nombre], usua_UsuarioCreacion, [ofic_FechaCreacion])
VALUES ('TEGUCIGALPA, M.D.C.', 1, GETDATE()),
	   ('SAN PEDRO SULA, CORTÉS', 1, GETDATE())


--**********OFICIO/PROFESIÓN**********--
INSERT INTO [Gral].[tbOficio_Profesiones] ([ofpr_Nombre], usua_UsuarioCreacion, [ofpr_FechaCreacion])
VALUES ('OFICIALES DE LAS FUERZAS ARMADAS', 1, GETDATE()),
	   ('SUBOFICIALES DE LAS FUERZAS ARMADAS', 1, GETDATE()),
	   ('OTROS MIEMBROS DE LAS FUERZAS ARMADAS', 1, GETDATE()),
	   ('MIEMBROS DEL PODER EJECUTIVO Y DE LOS CUERPOS LEGISLATIVOS', 1, GETDATE())


--**********PAISES**********--
INSERT INTO [Gral].[tbPaises] ([pais_Codigo], [pais_Nombre], [usua_UsuarioCreacion], [pais_FechaCreacion])
VALUES	('AD', 'ANDORRA', 1, GETDATE()),
		('AE', 'EMIRATOS ARABES UNIDOS', 1, GETDATE()),
		('AF', 'AFGANISTAN', 1, GETDATE()),
		('AG', 'ANTIGUA Y BARBUDA', 1, GETDATE()),
		('AI', 'ANGUILLA', 1, GETDATE()),
		('AL', 'ALBANIA', 1, GETDATE()),
		('AM', 'ARMENIA', 1, GETDATE()),
		('AN', 'ANTILLAS HOLANDESAS', 1, GETDATE()),
		('AO', 'ANGOLA', 1, GETDATE()),
		('AQ', 'ANTARTIDA', 1, GETDATE()),
		('AR', 'ARGENTINA', 1, GETDATE()),
		('AS', 'SAMOA AMERICANA', 1, GETDATE()),
		('AT', 'AUSTRIA', 1, GETDATE()),
		('AU', 'AUSTRALIA', 1, GETDATE()),
		('AW', 'ARUBA', 1, GETDATE()),
		('AX', 'ALAND, ISLAS', 1, GETDATE()),
		('AZ', 'AZERBALIAN', 1, GETDATE()),
		('BA', 'BOSNIA Y HERZSEGOVINA', 1, GETDATE()),
		('BB', 'BARBADOS', 1, GETDATE()),
		('BD', 'BANGLADESH', 1, GETDATE()),
		('BE', 'BELGICA', 1, GETDATE()),
		('BF', 'BURKINA FASO', 1, GETDATE()),
		('BG', 'BULGARIA', 1, GETDATE()),
		('BH', 'BAHREIN', 1, GETDATE()),
		('BI', 'BURUNDI', 1, GETDATE()),
		('BJ', 'BENIN', 1, GETDATE()),
		('BL', 'SAINT BARTHELEMY', 1, GETDATE()),
		('BM', 'BERMUDA', 1, GETDATE()),
		('BN', 'BRUNEI DARUSSALAM', 1, GETDATE()),
		('BO', 'BOLIVIA', 1, GETDATE()),
		('BQ', 'BONAIRE, SINT EUSTATIUS AND SABA', 1, GETDATE()),
		('BR', 'BRASIL', 1, GETDATE()),
		('BS', 'BAHAMAS', 1, GETDATE()),
		('BT', 'BUTAN', 1, GETDATE()),
		('BV', 'BOUVET, ISLA', 1, GETDATE()),
		('BW', 'BOTSWANA', 1, GETDATE()),
		('BY', 'BIELORRUSIA', 1, GETDATE()),
		('BZ', 'BELICE', 1, GETDATE()),
		('CA', 'CANADA', 1, GETDATE()),
		('CC', 'COCOS (KEELING) ISLAS', 1, GETDATE()),
		('CD', 'CONGO, REPUBLICA DEMOCRATICA', 1, GETDATE()),
		('CF', 'CENTROAFRICANA, REPUBLICA', 1, GETDATE()),
		('CG', 'CONGO, REP. POPULAR DEL', 1, GETDATE()),
		('CH', 'SUIZA', 1, GETDATE()),
		('CI', 'COSTA DE MARFIL (COTE D''IVOIRE)', 1, GETDATE()),
		('CK', 'COOK ISLAS', 1, GETDATE()),
		('CL', 'CHILE', 1, GETDATE()),
		('CM', 'CAMERUN', 1, GETDATE()),
		('CN', 'CHINA', 1, GETDATE()),
		('CO', 'COLOMBIA', 1, GETDATE()),
		('CR', 'COSTA RICA', 1, GETDATE()),
		('CU', 'CUBA', 1, GETDATE()),
		('CV', 'CABO VERDE', 1, GETDATE()),
		('CW', 'CURAZAO', 1, GETDATE()),
		('CX', 'NAVIDAD, ISLAS', 1, GETDATE()),
		('CY', 'CHIPRE', 1, GETDATE()),
		('CZ', 'CHECA, REPUBLICA', 1, GETDATE()),
		('DE', 'ALEMANIA, REPUBLICA FEDERAL', 1, GETDATE()),
		('DJ', 'DJIBOUTH', 1, GETDATE()),
		('DK', 'DINAMARCA', 1, GETDATE()),
		('DM', 'DOMINICA', 1, GETDATE()),
		('DO', 'DOMINICANA, REPUBLICA', 1, GETDATE()),
		('DZ', 'ARGELIA', 1, GETDATE()),
		('EC', 'ECUADOR', 1, GETDATE()),
		('EE', 'ESTONIA', 1, GETDATE()),
		('EG', 'EGIPTO', 1, GETDATE()),
		('EH', 'SAHARA DEL OESTE', 1, GETDATE()),
		('ER', 'ERITREA', 1, GETDATE()),
		('ES', 'ESPAÑA', 1, GETDATE()),
		('ET', 'ETIOPIA', 1, GETDATE()),
		('FI', 'FINLANDIA', 1, GETDATE()),
		('FJ', 'FIJI', 1, GETDATE()),
		('FK', 'FALKLAND ISLAS (MALVINAS)', 1, GETDATE()),
		('FM', 'MICRONESIA,ESTADO FEDERAL DE', 1, GETDATE()),
		('FO', 'FAROE, ISLAS', 1, GETDATE()),
		('FR', 'FRANCIA', 1, GETDATE()),
		('GA', 'GABON', 1, GETDATE()),
		('GB', 'REINO UNIDO (INGLATERRA, IRLANDA NORTE, ESCOCIA, GALES)', 1, GETDATE()),
		('GD', 'GRENADA', 1, GETDATE()),
		('GE', 'GEORGIA', 1, GETDATE()),
		('GF', 'FRANCESA, GUINEA', 1, GETDATE()),
		('GH', 'GHANA', 1, GETDATE()),
		('GI', 'GIBRALTAR', 1, GETDATE()),
		('GL', 'GROENLANDIA', 1, GETDATE()),
		('GM', 'GAMBIA', 1, GETDATE()),
		('GN', 'GUINEA', 1, GETDATE()),
		('GP', 'GUADALUPE', 1, GETDATE()),
		('GQ', 'ECUATORIAL, GUINEA', 1, GETDATE()),
		('GR', 'GRECIA', 1, GETDATE()),
		('GS', 'GEORGIA DEL SUR E ISLAS SAND', 1, GETDATE()),
		('GT', 'GUATEMALA', 1, GETDATE()),
		('GU', 'GUAN', 1, GETDATE()),
		('GW', 'GUINEA-BISSAU', 1, GETDATE()),
		('GY', 'GUYANA (ANTIGUA GUYANA INGLESA', 1, GETDATE()),
		('HK', 'HONG KONG', 1, GETDATE()),
		('HM', 'HEARD Y MC DONALD ISLAS', 1, GETDATE()),
		('HN', 'HONDURAS', 1, GETDATE()),
		('HR', 'CROACIA', 1, GETDATE()),
		('HT', 'HAITI', 1, GETDATE()),
		('HU', 'HUNGRIA', 1, GETDATE()),
		('ID', 'INDONESIA', 1, GETDATE()),
		('IE', 'IRLANDA', 1, GETDATE()),
		('IL', 'ISRAEL', 1, GETDATE()),
		('IN', 'INDIA', 1, GETDATE()),
		('IO', 'TERRITORIO BRITANICO DEL OCEANO INDICO', 1, GETDATE()),
		('IQ', 'IRAQ', 1, GETDATE()),
		('IR', 'IRAN, REPUBLICA ISLAMICA', 1, GETDATE()),
		('IS', 'ISLANDIA', 1, GETDATE()),
		('IT', 'ITALIA', 1, GETDATE()),
		('JM', 'JAMAICA', 1, GETDATE()),
		('JO', 'JORDANIA', 1, GETDATE()),
		('JP', 'JAPON', 1, GETDATE()),
		('KE', 'KENIA', 1, GETDATE()),
		('KG', 'KIRGHIZISTAN', 1, GETDATE()),
		('KH', 'CAMBOYA', 1, GETDATE()),
		('KI', 'KIRIBATI', 1, GETDATE()),
		('KM', 'COMORES', 1, GETDATE()),
		('KN', 'SAINT KITTS AND NEVIS', 1, GETDATE()),
		('KP', 'KOREA, REP. POPULAR DEMOCRATICA', 1, GETDATE()),
		('KR', 'KOREA, REP. DE (KOREA DEL SUR)', 1, GETDATE()),
		('KW', 'KUWAIT', 1, GETDATE()),
		('KY', 'CAIMAN ISLAS', 1, GETDATE()),
		('KZ', 'KAZAKSTAN', 1, GETDATE()),
		('LA', 'LAOS, REPUBLICA POPULAR DEMOCRATICA', 1, GETDATE()),
		('LB', 'LIBANO', 1, GETDATE()),
		('LC', 'SANTA LUCIA', 1, GETDATE()),
		('LI', 'LIECHTENSTEIN', 1, GETDATE()),
		('LK', 'SRI LANKA (CEILAN)', 1, GETDATE()),
		('LR', 'LIBERIA', 1, GETDATE()),
		('LS', 'LESOTHO', 1, GETDATE()),
		('LT', 'LITUANIA', 1, GETDATE()),
		('LU', 'LUXEMBURGO', 1, GETDATE()),
		('LV', 'LETONIA', 1, GETDATE()),
		('LY', 'LIBIA ARABE JAMAHIRIYA', 1, GETDATE()),
		('MA', 'MARRUECOS', 1, GETDATE()),
		('MC', 'MONACO', 1, GETDATE()),
		('MD', 'MOLDAVIA, REPUBLICA DE', 1, GETDATE()),
		('ME', 'MONTENEGRO', 1, GETDATE()),
		('MF', 'SAINT MARTIN (FRENCH PART)', 1, GETDATE()),
		('MG', 'MADAGASCAR', 1, GETDATE()),
		('MH', 'MARSHALL, ISLAS', 1, GETDATE()),
		('MK', 'MACEDONIA, LA ANT.REP.DE YUGOS', 1, GETDATE()),
		('ML', 'MALI', 1, GETDATE()),
		('MM', 'MYANMAR (ANTIGUA REP. DE BIRMANIA)', 1, GETDATE()),
		('MN', 'MONGOLIA', 1, GETDATE()),
		('MO', 'MACAU', 1, GETDATE()),
		('MP', 'MARIANAS SEPTENTRIONALES, ISLAS', 1, GETDATE()),
		('MQ', 'MARTINICA', 1, GETDATE()),
		('MR', 'MAURITANIA', 1, GETDATE()),
		('MS', 'MONTSERRAT', 1, GETDATE()),
		('MT', 'MALTA', 1, GETDATE()),
		('MU', 'MAURICIOS', 1, GETDATE()),
		('MV', 'MALDIVAS', 1, GETDATE()),
		('MW', 'MALAWI', 1, GETDATE()),
		('MX', 'MEXICO', 1, GETDATE()),
		('MY', 'MALASIA', 1, GETDATE()),
		('MZ', 'MOZAMBIQUE', 1, GETDATE()),
		('NA', 'NAMIBIA', 1, GETDATE()),
		('NC', 'NUEVA CALEDONIA', 1, GETDATE()),
		('NE', 'NIGER', 1, GETDATE()),
		('NF', 'NORFOLK, ISLAS', 1, GETDATE()),
		('NG', 'NIGERIA', 1, GETDATE()),
		('NI', 'NICARAGUA', 1, GETDATE()),
		('NL', 'PAISES BAJOS', 1, GETDATE()),
		('NO', 'NORUEGA', 1, GETDATE()),
		('NP', 'NEPAL', 1, GETDATE()),
		('NR', 'NAURO', 1, GETDATE()),
		('NU', 'NIUE', 1, GETDATE()),
		('NZ', 'NUEVA ZELANDA', 1, GETDATE()),
		('OM', 'OMAN', 1, GETDATE()),
		('PA', 'PANAMA', 1, GETDATE()),
		('PE', 'PERU', 1, GETDATE()),
		('PF', 'FRANCESA POLINESIA', 1, GETDATE()),
		('PG', 'PAPUA NUEVA GUINEA', 1, GETDATE()),
		('PH', 'FILIPINAS', 1, GETDATE()),
		('PK', 'PAKISTAN', 1, GETDATE()),
		('PL', 'POLONIA', 1, GETDATE()),
		('PM', 'SAN PEDRO Y MIGUELON', 1, GETDATE()),
		('PN', 'PITCAIRN', 1, GETDATE()),
		('PR', 'PUERTO RICO', 1, GETDATE()),
		('PS', 'TERRITORIO PALESTINO OCUPADO', 1, GETDATE()),
		('PT', 'PORTUGAL', 1, GETDATE()),
		('PW', 'PALAU', 1, GETDATE()),
		('PY', 'PARAGUAY', 1, GETDATE()),
		('QA', 'QATAR', 1, GETDATE()),
		('RE', 'REUNION', 1, GETDATE()),
		('RO', 'RUMANIA', 1, GETDATE()),
		('RS', 'SERBIA', 1, GETDATE()),
		('RU', 'RUSA, FEDERACION', 1, GETDATE()),
		('RW', 'RUANDA', 1, GETDATE()),
		('SA', 'SAUDITA ARABIA', 1, GETDATE()),
		('SB', 'SOLOMON, ISLAS', 1, GETDATE()),
		('SC', 'SEYCHELLES, ISLAS', 1, GETDATE()),
		('SD', 'SUDAN', 1, GETDATE()),
		('SE', 'SUECIA', 1, GETDATE()),
		('SG', 'SINGAPUR', 1, GETDATE()),
		('SH', 'SANTA HELENA', 1, GETDATE()),
		('SI', 'ESLOVENIA', 1, GETDATE()),
		('SJ', 'SVALBARD AND JAN MAYEN ISLAS', 1, GETDATE()),
		('SK', 'ESLOVAKIA', 1, GETDATE()),
		('SL', 'SIERRA LEONA', 1, GETDATE()),
		('SM', 'SAN MARINO', 1, GETDATE()),
		('SN', 'SENEGAL', 1, GETDATE()),
		('SO', 'SOMALIA', 1, GETDATE()),
		('SR', 'SURINAM (GUAYANA HOLANDESAS)', 1, GETDATE()),
		('SS', 'SUDAN DEL SUR', 1, GETDATE()),
		('ST', 'SAO TOME Y PRINCIPE', 1, GETDATE()),
		('SV', 'EL SALVADOR', 1, GETDATE()),
		('SX', 'SINT MAARTEN (DUTCH PART)', 1, GETDATE()),
		('SY', 'SIRIA, REPUBLICA ARABE', 1, GETDATE()),
		('SZ', 'SUAZILANDIA', 1, GETDATE()),
		('TC', 'TURCOS Y CAICOS ISLAS', 1, GETDATE()),
		('TD', 'CHAD', 1, GETDATE()),
		('TF', 'FRANCESES, TERRITORIOS DEL SURESTE', 1, GETDATE()),
		('TG', 'TOGO', 1, GETDATE()),
		('TH', 'TAILANDIA', 1, GETDATE()),
		('TJ', 'TADJIKISTAN', 1, GETDATE()),
		('TK', 'TOKELAU', 1, GETDATE()),
		('TL', 'TIMOR DEL ESTE', 1, GETDATE()),
		('TM', 'TURKMENISTAN', 1, GETDATE()),
		('TN', 'TUNISIA', 1, GETDATE()),
		('TO', 'TONGA', 1, GETDATE()),
		('TR', 'TURQUIA', 1, GETDATE()),
		('TT', 'TRINIDAD Y TOBAGO', 1, GETDATE()),
		('TV', 'TUVALU', 1, GETDATE()),
		('TW', 'TAIWAN, PROVINCIA CHINA DE', 1, GETDATE()),
		('TZ', 'TANZANIA, REPUBLICA UNIDA DE', 1, GETDATE()),
		('UA', 'UCRANIA', 1, GETDATE()),
		('UG', 'UGANDA', 1, GETDATE()),
		('UM', 'ISLAS ULTRAMARINAS MENORES (EEUU)', 1, GETDATE()),
		('US', 'ESTADOS UNIDOS', 1, GETDATE()),
		('UY', 'URUGUAY', 1, GETDATE()),
		('UZ', 'UZBEKISTAN', 1, GETDATE()),
		('VA', 'SANTA SEDE (CIUDAD DEL VATICANO)', 1, GETDATE()),
		('VC', 'SAN VICENTE Y LAS GRANADINAS', 1, GETDATE()),
		('VE', 'VENEZUELA', 1, GETDATE()),
		('VG', 'VIRGENES, ISLAS (BRITANICAS)', 1, GETDATE()),
		('VI', 'VIRGENES, ISLAS (ESTADOS UNIDOS)', 1, GETDATE()),
		('VN', 'VIETNAM', 1, GETDATE()),
		('VU', 'VANUATU', 1, GETDATE()),
		('WF', 'WALLIS Y FUTUNA, ISLAS', 1, GETDATE()),
		('WS', 'SAMOA', 1, GETDATE()),
		('YE', 'YEMEN', 1, GETDATE()),
		('YT', 'MAYOTTE', 1, GETDATE()),
		('ZA', 'SURAFRICA', 1, GETDATE()),
		('ZM', 'ZAMBIA', 1, GETDATE()),
		('ZW', 'ZIMBABWE', 1, GETDATE());


INSERT INTO [Gral].[tbProvincias] ([pvin_Nombre], [pvin_Codigo], [pais_Codigo], [usua_UsuarioCreacion], [pvin_FechaCreacion])
VALUES	-- Provinces for Argentina (AR)
		('Buenos Aires', 'BA', 'AR', 1, GETDATE()),
		('Córdoba', 'CO', 'AR', 1, GETDATE()),
		('Santa Fe', 'SF', 'AR', 1, GETDATE()),
		('Mendoza', 'MZ', 'AR', 1, GETDATE()),
		('Tucumán', 'TU', 'AR', 1, GETDATE()),
		
		-- Provinces for Brazil (BR)
		('São Paulo', 'SP', 'BR', 1, GETDATE()),
		('Rio de Janeiro', 'RJ', 'BR', 1, GETDATE()),
		('Minas Gerais', 'MG', 'BR', 1, GETDATE()),
		('Bahia', 'BA', 'BR', 1, GETDATE()),
		('Rio Grande do Sul', 'RS', 'BR', 1, GETDATE()),
		
		-- Provinces for Canada (CA)
		('Ontario', 'ON', 'CA', 1, GETDATE()),
		('Quebec', 'QC', 'CA', 1, GETDATE()),
		('British Columbia', 'BC', 'CA', 1, GETDATE()),
		('Alberta', 'AB', 'CA', 1, GETDATE()),
		('Manitoba', 'MB', 'CA', 1, GETDATE()),
		
		-- Provinces for United States (US)
		('California', 'CA', 'US', 1, GETDATE()),
		('Texas', 'TX', 'US', 1, GETDATE()),
		('Florida', 'FL', 'US', 1, GETDATE()),
		('New York', 'NY', 'US', 1, GETDATE()),
		('Illinois', 'IL', 'US', 1, GETDATE()),
		
		-- Provinces for United Kingdom (GB)
		('England', 'ENG', 'GB', 1, GETDATE()),
		('Scotland', 'SCT', 'GB', 1, GETDATE()),
		('Wales', 'WLS', 'GB', 1, GETDATE()),
		('Northern Ireland', 'NIR', 'GB', 1, GETDATE()),
		
		-- Provinces for Australia (AU)
		('New South Wales', 'NSW', 'AU', 1, GETDATE()),
		('Queensland', 'QLD', 'AU', 1, GETDATE()),
		('Victoria', 'VIC', 'AU', 1, GETDATE()),
		('Western Australia', 'WA', 'AU', 1, GETDATE()),
		('South Australia', 'SA', 'AU', 1, GETDATE()),
		
		-- Provinces for India (IN)
		('Maharashtra', 'MH', 'IN', 1, GETDATE()),
		('Uttar Pradesh', 'UP', 'IN', 1, GETDATE()),
		('Tamil Nadu', 'TN', 'IN', 1, GETDATE()),
		('Karnataka', 'KA', 'IN', 1, GETDATE()),
		('Gujarat', 'GJ', 'IN', 1, GETDATE()),
		
		-- Provinces for China (CN)
		('Guangdong', 'GD', 'CN', 1, GETDATE()),
		('Shandong', 'SD', 'CN', 1, GETDATE()),
		('Jiangsu', 'JS', 'CN', 1, GETDATE()),
		('Zhejiang', 'ZJ', 'CN', 1, GETDATE()),
		('Henan', 'HA', 'CN', 1, GETDATE()),
		
		-- Provinces for Russia (RU)
		('Moscow', 'MOW', 'RU', 1, GETDATE()),
		('Saint Petersburg', 'SPE', 'RU', 1, GETDATE()),
		('Novosibirsk', 'NVS', 'RU', 1, GETDATE()),
		('Yekaterinburg', 'EKB', 'RU', 1, GETDATE()),
		('Nizhny Novgorod', 'NIZ', 'RU', 1, GETDATE()),
		
		-- Provinces for France (FR)
		('Île-de-France', 'IDF', 'FR', 1, GETDATE()),
		('Auvergne-Rhône-Alpes', 'ARA', 'FR', 1, GETDATE()),
		('Hauts-de-France', 'HDF', 'FR', 1, GETDATE()),
		('Occitanie', 'OCC', 'FR', 1, GETDATE()),
		('Normandy', 'NOR', 'FR', 1, GETDATE()),
		
		-- Provinces for Germany (DE)
		('North Rhine-Westphalia', 'NRW', 'DE', 1, GETDATE()),
		('Bavaria', 'BY', 'DE', 1, GETDATE()),
		('Baden-Württemberg', 'BW', 'DE', 1, GETDATE()),
		('Lower Saxony', 'NI', 'DE', 1, GETDATE()),
		('Hesse', 'HE', 'DE', 1, GETDATE()),
		
		-- Provinces for Italy (IT)
		('Lombardy', 'LOM', 'IT', 1, GETDATE()),
		('Lazio', 'LAZ', 'IT', 1, GETDATE()),
		('Campania', 'CAM', 'IT', 1, GETDATE()),
		('Sicily', 'SIC', 'IT', 1, GETDATE()),
		('Veneto', 'VEN', 'IT', 1, GETDATE()),
		
		-- Provinces for Spain (ES)
		('Madrid', 'MAD', 'ES', 1, GETDATE()),
		('Catalonia', 'CAT', 'ES', 1, GETDATE()),
		('Andalusia', 'AND', 'ES', 1, GETDATE()),
		('Valencia', 'VAL', 'ES', 1, GETDATE()),
		('Galicia', 'GAL', 'ES', 1, GETDATE()),

		-- Provinces for Honduras (HN)
		('Atlantida', '01', 'HN', 1, GETDATE()),
		('Colon', '02', 'HN', 1, GETDATE()),
		('Comayagua', '03', 'HN', 1, GETDATE()),
		('Copan', '04', 'HN', 1, GETDATE()),
		('Cortes', '05', 'HN', 1, GETDATE()),
		('Choluteca', '06', 'HN', 1, GETDATE()),
		('El Paraiso', '07', 'HN', 1, GETDATE()),
		('Francisco Morazan', '08', 'HN', 1, GETDATE()),
		('Gracias a Dios', '09', 'HN', 1, GETDATE()),
		('Intibuca', '10', 'HN', 1, GETDATE()),
		('Islas de La Bahia', '11', 'HN', 1, GETDATE()),
		('La Paz', '12', 'HN', 1, GETDATE()),
		('Lempira', '13', 'HN', 1, GETDATE()),
		('Ocotepeque', '14', 'HN', 1, GETDATE()),
		('Olancho', '15', 'HN', 1, GETDATE()),
		('Santa Barbara', '16', 'HN', 1, GETDATE()),
		('Valle', '17', 'HN', 1, GETDATE()),
		('Yoro', '18', 'HN', 1, GETDATE());

INSERT INTO [Gral].[tbCiudades] ([ciud_Nombre], [pvin_Id], [usua_UsuarioCreacion], [ciud_FechaCreacion])
VALUES
	('La Ceiba', 65, 1, GETDATE()),
	('El Porvenir', 65, 1, GETDATE()),
	('Tela', 65, 1, GETDATE()),
	('Jutiapa', 65, 1, GETDATE()),
	('La Masica', 65, 1, GETDATE()),
	('San Francisco', 65, 1, GETDATE()),
	('Arizona', 65, 1, GETDATE()),
	('Esparta', 65, 1, GETDATE()),
	('Trujillo', 66, 1, GETDATE()),
	('Balfate', 66, 1, GETDATE()),
	('Iriona', 66, 1, GETDATE()),
	('Limón', 66, 1, GETDATE()),
	('Sabá', 66, 1, GETDATE()),
	('Santa Fe', 66, 1, GETDATE()),
	('Santa Rosa de Aguán', 66, 1, GETDATE()),
	('Sonaguera', 66, 1, GETDATE()),
	('Tocoa', 66, 1, GETDATE()),
	('Bonito Oriental', 66, 1, GETDATE()),
	('Comayagua', 67, 1, GETDATE()),
	('Ajuterique', 67, 1, GETDATE()),
	('El Rosario', 67, 1, GETDATE()),
	('Esquías', 67, 1, GETDATE()),
	('Humuya', 67, 1, GETDATE()),
	('La Libertad', 67, 1, GETDATE()),
	('Lamaní', 67, 1, GETDATE()),
	('La Trinidad', 67, 1, GETDATE()),
	('Lejamaní', 67, 1, GETDATE()),
	('Meámbar', 67, 1, GETDATE()),
	('Minas de Oro', 67, 1, GETDATE()),
	('Ojos de Agua', 67, 1, GETDATE()),
	('San Jerónimo', 67, 1, GETDATE()),
	('San José de Comayagua', 67, 1, GETDATE()),
	('San José del Potrero', 67, 1, GETDATE()),
	('San Luis', 67, 1, GETDATE()),
	('San Sebastián', 67, 1, GETDATE()),
	('Siguatepeque', 67, 1, GETDATE()),
	('Villa de San Antonio', 67, 1, GETDATE()),
	('Las Lajas', 67, 1, GETDATE()),
	('Taulabé', 67, 1, GETDATE()),
	('Santa Rosa de Copán', 68, 1, GETDATE()),
	('Cabañas', 68, 1, GETDATE()),
	('Concepción', 68, 1, GETDATE()),
	('Copán Ruinas', 68, 1, GETDATE()),
	('Corquín', 68, 1, GETDATE()),
	('Cucuyagua', 68, 1, GETDATE()),
	('Dolores', 68, 1, GETDATE()),
	('Dulce Nombre', 68, 1, GETDATE()),
	('El Paraíso', 68, 1, GETDATE()),
	('Florida', 68, 1, GETDATE()),
	('La Jigua', 68, 1, GETDATE()),
	('La Unión', 68, 1, GETDATE()),
	('Nueva Arcadia', 68, 1, GETDATE()),
	('San Agustín', 68, 1, GETDATE()),
	('San Antonio', 68, 1, GETDATE()),
	('San Jerónimo', 68, 1, GETDATE()),
	('San José', 68, 1, GETDATE()),
	('San Juan de Opoa', 68, 1, GETDATE()),
	('San Nicolás', 68, 1, GETDATE()),
	('San Pedro', 68, 1, GETDATE()),
	('Santa Rita', 68, 1, GETDATE()),
	('Trinidad de Copán', 68, 1, GETDATE()),
	('Veracruz', 68, 1, GETDATE()),
	('San Pedro Sula', 69, 1, GETDATE()),
	('Choloma', 69, 1, GETDATE()),
	('Omoa', 69, 1, GETDATE()),
	('Pimienta', 69, 1, GETDATE()),
	('Potrerillos', 69, 1, GETDATE()),
	('Puerto Cortés', 69, 1, GETDATE()),
	('San Antonio de Cortés', '69', 1, GETDATE()),
	('San Francisco de Yojoa', 69, 1, GETDATE()),
	('San Manuel', 69, 1, GETDATE()),
	('Santa Cruz de Yojoa', 69, 1, GETDATE()),
	('Villanueva', 69, 1, GETDATE()),
	('La Lima', 69, 1, GETDATE()),
	
	('Choluteca', 70, 1, GETDATE()),
	('Apacilagua', 70, 1, GETDATE()),
	('Concepción de María', 70, 1, GETDATE()),
	('Duyure', 70, 1, GETDATE()),
	('El Corpus', 70, 1, GETDATE()),
	('El Triunfo', 70, 1, GETDATE()),
	('Marcovia', 70, 1, GETDATE()),
	('Morolica', 70, 1, GETDATE()),
	('Namasigüe', 70, 1, GETDATE()),
	('Orocuina', 70, 1, GETDATE()),
	('Pespire', 70, 1, GETDATE()),
	('San Antonio de Flores', 70, 1, GETDATE()),
	('San Isidro', 70, 1, GETDATE()),
	('San José', 70, 1, GETDATE()),
	('San Marcos de Colón', 70, 1, GETDATE()),
	('Santa Ana de Yusguare', 70, 1, GETDATE()),
	
	('Yuscarán', 71, 1, GETDATE()),
	('Alauca', 71, 1, GETDATE()),
	('Danlí', 71, 1, GETDATE()),
	('El Paraíso', 71, 1, GETDATE()),
	('Güinope', 71, 1, GETDATE()),
	('Jacaleapa', 71, 1, GETDATE()),
	('Liure', 71, 1, GETDATE()),
	('Morocelí', 71, 1, GETDATE()),
	('Oropolí', 71, 1, GETDATE()),
	('Potrerillos', 71, 1, GETDATE()),
	('San Antonio de Flores', 71, 1, GETDATE()),
	('San Lucas', 71, 1, GETDATE()),
	('San Matías', 71, 1, GETDATE()),
	('Soledad', 71, 1, GETDATE()),
	('Teupasenti', 71, 1, GETDATE()),
	('Texiguat', 71, 1, GETDATE()),
	('Vado Ancho', 71, 1, GETDATE()),
	('Yauyupe', 71, 1, GETDATE()),
	('Trojes', 71, 1, GETDATE()),
	
	('Distrito Central', 72, 1, GETDATE()),
	('Alubarén', 72, 1, GETDATE()),
	('Cedros', 72, 1, GETDATE()),
	('Curarén', 72, 1, GETDATE()),
	('El Porvenir', 72, 1, GETDATE()),
	('Guaimaca', 72, 1, GETDATE()),
	('La Libertad', 72, 1, GETDATE()),
	('La Venta', 72, 1, GETDATE()),
	('Lepaterique', 72, 1, GETDATE()),
	('Maraita', 72, 1, GETDATE()),
	('Marale', 72, 1, GETDATE()),
	('Nueva Armenia', 72, 1, GETDATE()),
	('Ojojona', 72, 1, GETDATE()),
	('Orica', 72, 1, GETDATE()),
	('Reitoca', 72, 1, GETDATE()),
	('Sabanagrande', 72, 1, GETDATE()),
	('San Antonio de Oriente', 72, 1, GETDATE()),
	('San Buenaventura', 72, 1, GETDATE()),
	('San Ignacio', 72, 1, GETDATE()),
	('San Juan de Flores', 72, 1, GETDATE()),
	('San Miguelito', 72, 1, GETDATE()),
	('Santa Ana', 72, 1, GETDATE()),
	('Santa Lucía', 72, 1, GETDATE()),
	('Talanga', 72, 1, GETDATE()),
	('Tatumbla', 72, 1, GETDATE()),
	('Valle de Ángeles', 72, 1, GETDATE()),
	('Villa de San Francisco', 72, 1, GETDATE()),
	('Vallecillo', 72, 1, GETDATE()),
	
	('Puerto Lempira', 73, 1, GETDATE()),
	('Brus Laguna', 73, 1, GETDATE()),
	('Ahuas', 73, 1, GETDATE()),
	('Juan Francisco Bulnes', 73, 1, GETDATE()),
	('Ramón Villeda Morales', 73, 1, GETDATE()),
	('Wampusirpe', 73, 1, GETDATE()),
	
	('La Esperanza', 74, 1, GETDATE()),
	('Camasca', 74, 1, GETDATE()),
	('Colomoncagua', 74, 1, GETDATE()),
	('Concepción', 74, 1, GETDATE()),
	('Dolores', 74, 1, GETDATE()),
	('Intibucá', 74, 1, GETDATE()),
	('Jesús de Otoro', 74, 1, GETDATE()),
	('Magdalena', 74, 1, GETDATE()),
	('Masaguara', 74, 1, GETDATE()),
	('San Antonio', 74, 1, GETDATE()),
	('San Isidro', 74, 1, GETDATE()),
	('San Juan', 74, 1, GETDATE()),
	('San Marcos de la Sierra', 74, 1, GETDATE()),
	('San Miguel Guancapla', 74, 1, GETDATE()),
	('Santa Lucía', 74, 1, GETDATE()),
	('Yamaranguila', 74, 1, GETDATE()),
	('San Francisco de Opalaca', 74, 1, GETDATE()),
	
	('Roatán', 75, 1, GETDATE()),
	('Guanaja', 75, 1, GETDATE()),
	('José Santos Guardiola', 75, 1, GETDATE()),
	('Utila', 75, 1, GETDATE()),
	
	('La Paz', 76, 1, GETDATE()),
	('Aguanqueterique', 76, 1, GETDATE()),
	('Cabañas', 76, 1, GETDATE()),
	('Cane', 76, 1, GETDATE()),
	('Chinacla', 76, 1, GETDATE()),
	('Guajiquiro', 76, 1, GETDATE()),
	('Lauterique', 76, 1, GETDATE()),
	('Marcala', 76, 1, GETDATE()),
	('Mercedes de Oriente', 76, 1, GETDATE()),
	('Opatoro', 76, 1, GETDATE()),
	('San Antonio del Norte', 76, 1, GETDATE()),
	('San José', 76, 1, GETDATE()),
	('San Juan', 76, 1, GETDATE()),
	('San Pedro de Tutule', 76, 1, GETDATE()),
	('Santa Ana', 76, 1, GETDATE()),
	('Santa Elena', 76, 1, GETDATE()),
	('Santa María', 76, 1, GETDATE()),
	('Santiago de Puringla', 76, 1, GETDATE()),
	('Yarula', 76, 1, GETDATE()),
	('Gracias', 77, 1, GETDATE()),
	('Belén', 77, 1, GETDATE()),
	('Candelaria', 77, 1, GETDATE()),
	('Cololaca', 77, 1, GETDATE()),
	('Erandique', 77, 1, GETDATE()),
	('Gualcince', 77, 1, GETDATE()),
	('Guarita', 77, 1, GETDATE()),
	('La Campa', 77, 1, GETDATE()),
	('La Iguala', 77, 1, GETDATE()),
	('Las Flores', 77, 1, GETDATE()),
	('La Unión', 77, 1, GETDATE()),
	('La Virtud', 77, 1, GETDATE()),
	('Lepaera', 77, 1, GETDATE()),
	('Mapulaca', 77, 1, GETDATE()),
	('Piraera', 77, 1, GETDATE()),
	('San Andrés', 77, 1, GETDATE()),
	('San Francisco', 77, 1, GETDATE()),
	('San Juan Guarita', 77, 1, GETDATE()),
	('San Manuel Colohete', 77, 1, GETDATE()),
	('San Rafael', 77, 1, GETDATE()),
	('San Sebastián', 77, 1, GETDATE()),
	('Santa Cruz', 77, 1, GETDATE()),
	('Talgua', 77, 1, GETDATE()),
	('Tambla', 77, 1, GETDATE()),
	('Tomalá', 77, 1, GETDATE()),
	('Valladolid', 77, 1, GETDATE()),
	('Virginia', 77, 1, GETDATE()),
	('San Marcos de Caiquín', 77, 1, GETDATE()),
	('Ocotepeque', 78, 1, GETDATE()),
	('Belén Gualcho', 78, 1, GETDATE()),
	('Concepción', 78, 1, GETDATE()),
	('Dolores Merendón', 78, 1, GETDATE()),
	('Fraternidad', 78, 1, GETDATE()),
	('La Encarnación', 78, 1, GETDATE()),
	('La Labor', 78, 1, GETDATE()),
	('Lucerna', 78, 1, GETDATE()),
	('Mercedes', 78, 1, GETDATE()),
	('San Fernando', 78, 1, GETDATE()),
	('San Francisco del Valle', 78, 1, GETDATE()),
	('San Jorge', 78, 1, GETDATE()),
	('San Marcos', 78, 1, GETDATE()),
	('Santa Fe', 78, 1, GETDATE()),
	('Sensenti', 78, 1, GETDATE()),
	('Sinuapa', 78, 1, GETDATE()),
	('Juticalpa', 79, 1, GETDATE()),
	('Campamento', 79, 1, GETDATE()),
	('Catacamas', 79, 1, GETDATE()),
	('Concordia', 79, 1, GETDATE()),
	('Dulce Nombre de Culmí', 79, 1, GETDATE()),
	('El Rosario', 79, 1, GETDATE()),
	('Esquipulas del Norte', 79, 1, GETDATE()),
	('Gualaco', 79, 1, GETDATE()),
	('Guarizama', 79, 1, GETDATE()),
	('Guata', 79, 1, GETDATE()),
	('Guayape', 79, 1, GETDATE()),
	('Jano', 79, 1, GETDATE()),
	('La Unión', 79, 1, GETDATE()),
	('Mangulile', 79, 1, GETDATE()),
	('Manto', 79, 1, GETDATE()),
	('Salamá', 79, 1, GETDATE()),
	('San Esteban', 79, 1, GETDATE()),
	('San Francisco de Becerra', 79, 1, GETDATE()),
	('San Francisco de la Paz', 79, 1, GETDATE()),
	('Santa María del Real', 79, 1, GETDATE()),
	('Silca', 79, 1, GETDATE()),
	('Yocón', 79, 1, GETDATE()),
	('Patuca', 79, 1, GETDATE()),
	('Santa Bárbara', 80, 1, GETDATE()),
	('Arada', 80, 1, GETDATE()),
	('Atima', 80, 1, GETDATE()),
	('Azacualpa', 80, 1, GETDATE()),
	('Ceguaca', 80, 1, GETDATE()),
	('Concepción del Norte', 80, 1, GETDATE()),
	('Concepción del Sur', 80, 1, GETDATE()),
	('Chinda', 80, 1, GETDATE()),
	('El Níspero', 80, 1, GETDATE()),
	('Gualala', 80, 1, GETDATE()),
	('Ilama', 80, 1, GETDATE()),
	('Las Vegas', 80, 1, GETDATE()),
	('Macuelizo', 80, 1, GETDATE()),
	('Naranjito', 80, 1, GETDATE()),
	('Nuevo Celilac', 80, 1, GETDATE()),
	('Nueva Frontera', 80, 1, GETDATE()),
	('Petoa', 80, 1, GETDATE()),
	('Protección', 80, 1, GETDATE()),
	('Quimistán', 80, 1, GETDATE()),
	('San Francisco de Ojuera', 80, 1, GETDATE()),
	('San José de las Colinas', 80, 1, GETDATE()),
	('San Luis', 80, 1, GETDATE()),
	('San Marcos', 80, 1, GETDATE()),
	('San Nicolás', 80, 1, GETDATE()),
	('San Pedro Zacapa', 80, 1, GETDATE()),
	('San Vicente Centenario', 80, 1, GETDATE()),
	('Santa Rita', 80, 1, GETDATE()),
	('Trinidad', 80, 1, GETDATE()),
	('Nacaome', 81, 1, GETDATE()),
	('Alianza', 81, 1, GETDATE()),
	('Amapala', 81, 1, GETDATE()),
	('Aramecina', 81, 1, GETDATE()),
	('Caridad', 81, 1, GETDATE()),
	('Goascorán', 81, 1, GETDATE()),
	('Langue', 81, 1, GETDATE()),
	('San Francisco de Coray', 81, 1, GETDATE()),
	('San Lorenzo', 81, 1, GETDATE()),
	('Yoro', 82, 1, GETDATE()),
	('Arenal', 82, 1, GETDATE()),
	('El Negrito', 82, 1, GETDATE()),
	('El Progreso', 82, 1, GETDATE()),
	('Jocón', 82, 1, GETDATE()),
	('Morazán', 82, 1, GETDATE()),
	('Olanchito', 82, 1, GETDATE()),
	('Santa Rita', 82, 1, GETDATE()),
	('Sulaco', 82, 1, GETDATE()),
	('Victoria', 82, 1, GETDATE()),
	('Yorito', 82, 1, GETDATE());


INSERT INTO [Gral].[tbAldeas] ([alde_Nombre], [ciud_Id], [usua_UsuarioCreacion], [alde_FechaCreacion])
VALUES ('El Carmen', 63, 1, GETDATE()),
	   ('El Hatillo', 69, 1, GETDATE()),
	   ('Los Lirios', 12, 1, GETDATE()),
	   ('El Rosario', 25, 1, GETDATE())