// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMEXPRO.Entities.Entities
{
    public partial class tbAduanas
    {
        public tbAduanas()
        {
            tbDeclaraciones_Valordeva_Aduana_Despacho = new HashSet<tbDeclaraciones_Valor>();
            tbDeclaraciones_Valordeva_Aduana_Ingreso = new HashSet<tbDeclaraciones_Valor>();
            tbDucaduca_AduanaRegistroNavigation = new HashSet<tbDuca>();
            tbDucaduca_AduanaSalidaNavigation = new HashSet<tbDuca>();
        }

        public int adua_Id { get; set; }
        public string adua_Codigo { get; set; }
        public string adua_Nombre { get; set; }
        public string adua_Direccion_Exacta { get; set; }
        public int usua_UsuarioCreacion { get; set; }
        public DateTime adua_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        public DateTime? adua_FechaModificacion { get; set; }
        public int? usua_UsuarioEliminacion { get; set; }
        public DateTime? adua_FechaEliminacion { get; set; }
        public bool? adua_Estado { get; set; }

        public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioEliminacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbDeclaraciones_Valor> tbDeclaraciones_Valordeva_Aduana_Despacho { get; set; }
        public virtual ICollection<tbDeclaraciones_Valor> tbDeclaraciones_Valordeva_Aduana_Ingreso { get; set; }
        public virtual ICollection<tbDuca> tbDucaduca_AduanaRegistroNavigation { get; set; }
        public virtual ICollection<tbDuca> tbDucaduca_AduanaSalidaNavigation { get; set; }
    }
}