// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMEXPRO.Entities.Entities
{
    public partial class tbCondicionesComerciales
    {
        public tbCondicionesComerciales()
        {
            tbProveedoresDeclaracion = new HashSet<tbProveedoresDeclaracion>();
        }

        public int coco_Id { get; set; }
        public string coco_Codigo { get; set; }
        public string coco_Descripcion { get; set; }
        public int usua_UsuarioCreacion { get; set; }
        public DateTime coco_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        public DateTime? coco_FechaModificacion { get; set; }
        public int? usua_UsuarioEliminacion { get; set; }
        public DateTime? coco_FechaEliminacion { get; set; }
        public bool? coco_Estado { get; set; }

        public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioEliminacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbProveedoresDeclaracion> tbProveedoresDeclaracion { get; set; }
    }
}