// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIMEXPRO.Entities.Entities
{
    public partial class tbDuca
    {
        public tbDuca()
        {
            tbBoletinPago = new HashSet<tbBoletinPago>();
            tbDocumentosDeSoporte = new HashSet<tbDocumentosDeSoporte>();
            tbLiquidacionGeneral = new HashSet<tbLiquidacionGeneral>();
            tbPedidosOrden = new HashSet<tbPedidosOrden>();
        }

        public string duca_No_Duca { get; set; }
        public string duca_No_Correlativo_Referencia { get; set; }
        public int deva_Id { get; set; }
        public int duca_AduanaRegistro { get; set; }
        public int duca_AduanaSalida { get; set; }
        public string duca_DomicilioFiscal_Exportador { get; set; }
        public int duca_Tipo_Iden_Exportador { get; set; }
        public int duca_Pais_Emision_Exportador { get; set; }
        public string duca_Numero_Id_Importador { get; set; }
        public int duca_Pais_Emision_Importador { get; set; }
        public string duca_DomicilioFiscal_Importador { get; set; }
        public string duca_Regimen_Aduanero { get; set; }
        public string duca_Modalidad { get; set; }
        public string duca_Clase { get; set; }
        public string duca_Codigo_Declarante { get; set; }
        public string duca_Numero_Id_Declarante { get; set; }
        public string duca_NombreSocial_Declarante { get; set; }
        public string duca_DomicilioFiscal_Declarante { get; set; }
        public int duca_Pais_Procedencia { get; set; }
        public int duca_Pais_Exportacion { get; set; }
        public int duca_Pais_Destino { get; set; }
        public string duca_Deposito_Aduanero { get; set; }
        public string duca_Lugar_Embarque { get; set; }
        public string duca_Lugar_Desembarque { get; set; }
        public string duca_Manifiesto { get; set; }
        public string duca_Titulo { get; set; }
        public string duca_Codigo_Transportista { get; set; }
        public decimal? duca_PesoBrutoTotal { get; set; }
        public decimal? duca_PesoNetoTotal { get; set; }
        public int? motr_id { get; set; }
        public string duca_Transportista_Nombre { get; set; }
        public int? duca_Conductor_Id { get; set; }
        public string duca_Codigo_Tipo_Documento { get; set; }
        public DateTime duca_FechaVencimiento { get; set; }
        public string duca_CanalAsignado { get; set; }
        public int usua_UsuarioCreacion { get; set; }
        public DateTime duca_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        public DateTime? duca_FechaModificacion { get; set; }
        public bool? duca_Estado { get; set; }

        [NotMapped]
        public string cont_Licencia { get; set; }

        [NotMapped]
        public int pais_IdExpedicion { get; set; }

        [NotMapped]
        public string cont_Nombre { get; set; }

        [NotMapped]
        public string cont_Apellido { get; set; }

        [NotMapped]
        public int pais_Id { get; set; }

        [NotMapped]
        public int marca_Id { get; set; }

        [NotMapped]
        public string tran_Chasis { get; set; }

        [NotMapped]
        public string tran_Remolque { get; set; }

        [NotMapped]
        public int tran_CantCarga { get; set; }

        [NotMapped]
        public int tran_NumDispositivoSeguridad { get; set; }

        [NotMapped]
        public string tran_Equipamiento { get; set; }

        [NotMapped]
        public string tran_TipoCarga { get; set; }
        
        [NotMapped]
        public string tran_IdContenedor { get; set; }

        [NotMapped]
        public int usua_UsuarioCreacio { get; set; }

        [NotMapped]
        public DateTime tran_FechaCreacion { get; set; }


        public virtual tbDeclaraciones_Valor deva { get; set; }
        public virtual tbAduanas duca_AduanaRegistroNavigation { get; set; }
        public virtual tbAduanas duca_AduanaSalidaNavigation { get; set; }
        public virtual tbConductor duca_Conductor { get; set; }
        public virtual tbPaises duca_Pais_DestinoNavigation { get; set; }
        public virtual tbPaises duca_Pais_Emision_ExportadorNavigation { get; set; }
        public virtual tbPaises duca_Pais_Emision_ImportadorNavigation { get; set; }
        public virtual tbPaises duca_Pais_ExportacionNavigation { get; set; }
        public virtual tbPaises duca_Pais_ProcedenciaNavigation { get; set; }
        public virtual tbTiposIdentificacion duca_Tipo_Iden_ExportadorNavigation { get; set; }
        public virtual tbModoTransporte motr { get; set; }
        public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbBoletinPago> tbBoletinPago { get; set; }
        public virtual ICollection<tbDocumentosDeSoporte> tbDocumentosDeSoporte { get; set; }
        public virtual ICollection<tbLiquidacionGeneral> tbLiquidacionGeneral { get; set; }
        public virtual ICollection<tbPedidosOrden> tbPedidosOrden { get; set; }
    }
}