// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMEXPRO.Entities.Entities
{
    public partial class tbLotes
    {
        public tbLotes()
        {
            tbAsignacionesOrdenDetalle = new HashSet<tbAsignacionesOrdenDetalle>();
            tbPedidosProduccionDetalles = new HashSet<tbPedidosProduccionDetalles>();
        }

        public int lote_Id { get; set; }
        public int mate_Id { get; set; }
        public int unme_Id { get; set; }
        public int? code_Id { get; set; }
        public int lote_Stock { get; set; }
        public int lote_CantIngresada { get; set; }
        public string lote_Observaciones { get; set; }
        public int tipa_Id { get; set; }
        public int usua_UsuarioCreacion { get; set; }
        public DateTime lote_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        public DateTime? lote_FechaModificacion { get; set; }
        public int? usua_UsuarioEliminacion { get; set; }
        public DateTime? lote_FechaEliminacion { get; set; }
        public bool? lote_Estado { get; set; }

        public virtual tbOrdenCompraDetalles code { get; set; }
        public virtual tbMateriales mate { get; set; }
        public virtual tbUnidadMedidas unme { get; set; }
        public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioEliminacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbAsignacionesOrdenDetalle> tbAsignacionesOrdenDetalle { get; set; }
        public virtual ICollection<tbPedidosProduccionDetalles> tbPedidosProduccionDetalles { get; set; }
    }
}