// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIMEXPRO.Entities.Entities
{
    public partial class tbModulos
    {
        public tbModulos()
        {
            tbMaquinas = new HashSet<tbMaquinas>();
            tbReporteModuloDia = new HashSet<tbReporteModuloDia>();
        }

        public int modu_Id { get; set; }
        public string modu_Nombre { get; set; }
        public int proc_Id { get; set; }
        public int empr_Id { get; set; }
        public int usua_UsuarioCreacion { get; set; }
        public DateTime modu_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        public DateTime? modu_FechaModificacion { get; set; }
        public int? usua_UsuarioEliminacion { get; set; }
        public DateTime? modu_FechaEliminacion { get; set; }
        public bool? modu_Estado { get; set; }

        [NotMapped]
        public string empleado_Nombre { get; set; }
        [NotMapped]
        public string proc_Descripcion { get; set; }
        [NotMapped]
        public string UsuarioCreacion { get; set; }
        [NotMapped]
        public string UsuarioModifica { get; set; }
        public virtual tbEmpleados empr { get; set; }
        public virtual tbProcesos proc { get; set; }
        public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioEliminacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbMaquinas> tbMaquinas { get; set; }
        public virtual ICollection<tbReporteModuloDia> tbReporteModuloDia { get; set; }
    }
}