// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMEXPRO.Entities.Entities
{
    public partial class tbOrdenCompraDetalles
    {
        public tbOrdenCompraDetalles()
        {
            tbLotes = new HashSet<tbLotes>();
            tbMaterialesBrindar = new HashSet<tbMaterialesBrindar>();
            tbOrde_Ensa_Acab_Etiq = new HashSet<tbOrde_Ensa_Acab_Etiq>();
            tbReporteModuloDiaDetalle = new HashSet<tbReporteModuloDiaDetalle>();
        }

        public int code_Id { get; set; }
        public int orco_Id { get; set; }
        public int code_CantidadPrenda { get; set; }
        public int esti_Id { get; set; }
        public int tall_Id { get; set; }
        public string code_Sexo { get; set; }
        public int colr_Id { get; set; }
        public string code_Documento { get; set; }
        public string code_Medidas { get; set; }
        public int proc_IdComienza { get; set; }
        public int proc_IdActual { get; set; }
        public decimal code_Unidad { get; set; }
        public decimal code_Valor { get; set; }
        public decimal code_Impuesto { get; set; }
        public decimal code_Descuento { get; set; }
        public string code_EspecificacionEmbalaje { get; set; }
        public int usua_UsuarioCreacion { get; set; }
        public DateTime code_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        public DateTime? code_FechaModificacion { get; set; }
        public bool? code_Estado { get; set; }

        public virtual tbColores colr { get; set; }
        public virtual tbEstilos esti { get; set; }
        public virtual tbOrdenCompra orco { get; set; }
        public virtual tbProcesos proc_IdComienzaNavigation { get; set; }
        public virtual tbTallas tall { get; set; }
        public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbLotes> tbLotes { get; set; }
        public virtual ICollection<tbMaterialesBrindar> tbMaterialesBrindar { get; set; }
        public virtual ICollection<tbOrde_Ensa_Acab_Etiq> tbOrde_Ensa_Acab_Etiq { get; set; }
        public virtual ICollection<tbReporteModuloDiaDetalle> tbReporteModuloDiaDetalle { get; set; }
    }
}