// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMEXPRO.Entities.Entities
{
    public partial class tbPedidosProduccion
    {
        public tbPedidosProduccion()
        {
            tbOrde_Ensa_Acab_Etiq = new HashSet<tbOrde_Ensa_Acab_Etiq>();
            tbPedidosProduccionDetalles = new HashSet<tbPedidosProduccionDetalles>();
        }

        public int ppro_Id { get; set; }
        public int empl_Id { get; set; }
        public DateTime ppro_Fecha { get; set; }
        public string ppro_Estados { get; set; }
        public string ppro_Observaciones { get; set; }
        public int usua_UsuarioCreacion { get; set; }
        public DateTime ppro_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        public DateTime? ppro_FechaModificacion { get; set; }
        public bool? ppro_Estado { get; set; }

        public virtual tbEmpleados empl { get; set; }
        public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbOrde_Ensa_Acab_Etiq> tbOrde_Ensa_Acab_Etiq { get; set; }
        public virtual ICollection<tbPedidosProduccionDetalles> tbPedidosProduccionDetalles { get; set; }
    }
}