// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMEXPRO.Entities.Entities
{
    public partial class tbProveedores
    {
        public tbProveedores()
        {
            tbPedidosOrden = new HashSet<tbPedidosOrden>();
        }

        public int prov_Id { get; set; }
        public string prov_NombreCompania { get; set; }
        public string prov_NombreContacto { get; set; }
        public string prov_Telefono { get; set; }
        public string prov_CodigoPostal { get; set; }
        public int prov_Ciudad { get; set; }
        public string prov_DireccionExacta { get; set; }
        public string prov_CorreoElectronico { get; set; }
        public string prov_Fax { get; set; }
        public int usua_UsuarioCreacion { get; set; }
        public DateTime prov_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        public DateTime? prov_FechaModificacion { get; set; }
        public int? usua_UsuarioEliminacion { get; set; }
        public DateTime? prov_FechaEliminacion { get; set; }
        public bool? prov_Estado { get; set; }

        public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioEliminacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPedidosOrden> tbPedidosOrden { get; set; }
    }
}