/* eslint-disable no-shadow */
import "@material-ui/icons";
import i18next from "i18next";
import ar from "./navigation-i18n/ar";
import en from "./navigation-i18n/en";
import tr from "./navigation-i18n/tr";

i18next.addResourceBundle("en", "navigation", en);
i18next.addResourceBundle("tr", "navigation", tr);
i18next.addResourceBundle("ar", "navigation", ar);

let navigationConfig = [
  {
    id: "MenuInicio",
    title: "Inicio",
    type: "group",
    icon: "heroicons-outline:home",
    translate: "INICIO",
    children: [
      {
        id: "InicioBlank",
        title: "Inicio",
        type: "item",
        icon: "heroicons-outline:clipboard-check",
        url: "/Inicio/Blank",
      },
      {
        id: "InicioProduccion",
        title: "Inicio",
        type: "item",
        icon: "heroicons-outline:clipboard-check",
        url: "/Inicio/Produccion",
      },
      {
        id: "InicioAduana",
        title: "Inicio",
        type: "item",
        icon: "heroicons-outline:clipboard-check",
        url: "/Inicio/Aduana",
      },
    ],
  },
  {
    id: "Acce",
    title: "Seguridad",
    type: "group",
    icon: "heroicons-outline:lock-closed",
    translate: "SEGURIDAD",
    children: [
      {
        id: "Acceso",
        title: "ECommerce",
        type: "collapse",
        icon: "heroicons-outline:lock-closed",
        translate: "Acceso",
        children: [
          {
            id: "Usuarios",
            title: "Usuarios",
            type: "item",
            icon: "material-outline:hail",
            url: "/Usuarios/Index",
          },
          {
            id: "Roles",
            title: "Roles",
            type: "item",
            icon: "material-outline:manage_search",
            url: "/Roles/Index",
          },
        ],
      },
    ],
  },
  {
    id: "Gral",
    title: "Generales",
    type: "group",
    icon: "heroicons-outline:home",
    translate: "GENERALES",
    children: [
      {
        id: "Generales",
        title: "ECommerce",
        type: "collapse",
        icon: "heroicons-outline:bookmark-alt",
        translate: "Generales",
        children: [
          {
            id: "Cargos",
            title: "Cargos",
            type: "item",
            icon: "material-outline:cleaning_services",
            url: "Cargos/Index",
          },
          {
            id: "EstadosCiviles",
            title: "Estados Civiles",
            type: "item",
            icon: "material-outline:male",
            url: "EstadosCiviles/Index",
          },
          {
            id: "FormasEnvio",
            title: "Formas de envío",
            type: "item",
            icon: "material-outline:taxi_alert",
            url: "/FormaEnvio/Index",
          },
          {
            id: "Oficinas",
            title: "Oficinas Aduaneras",
            type: "item",
            icon: "material-outline:computer",
            url: "Oficinas/Index",
          },
          {
            id: "OficiosProfesiones",
            title: "Oficios y Profesiones",
            type: "item",
            icon: "heroicons-outline:academic-cap",
            url: "OficiosProfesiones/Index",
          },
          {
            id: "Monedas",
            title: "Monedas",
            type: "item",
            icon: "material-outline:attach_money",
            url: "Monedas/Index",
          },
          {
            id: "TipoIdentificacion",
            title: "Tipos de Identificacion",
            type: "item",
            icon: "heroicons-outline:identification",
            url: "TipoIdentificacion/Index",
          },
          {
            id: "UnidadesMedida",
            title: "Unidades de medida",
            type: "item",
            icon: "material-outline:aspect_ratio",
            url: "UnidadesMedida/Index",
          },
        ],
      },
      {
        id: "Personas",
        title: "Personas",
        type: "collapse",
        icon: "material-outline:emoji_people",
        translate: "Personas",
        children: [
          {
            id: "Clientes",
            title: "Clientes",
            type: "item",
            icon: "material-outline:airline_seat_recline_normal",
            url: "Clientes/Index",
          },
          {
            id: "Empleados",
            title: "Empleados ",
            type: "item",
            icon: "material-outline:groups",
            url: "Empleados/Index",
          },
          // {
          //   id: "20",
          //   title: "Personas ",
          //   type: "item",
          //   icon: "heroicons-solid:users",
          //   url: "Personas/Index",
          // },
          {
            id: "Proveedores",
            title: "Proveedores ",
            type: "item",
            icon: "heroicons-solid:user",
            url: "/Proveedores/Index",
          },
          {
            id: "TipoIntermediario",
            title: "Tipos de Intermediarios ",
            type: "item",
            icon: "heroicons-solid:user-add",
            url: "/TipoIntermediario/Index",
          },
        ],
      },
      {
        id: "ubicaciones",
        title: "Ubicaciones",
        type: "collapse",
        icon: "material-outline:public",
        translate: "Ubicaciones",
        children: [
          {
            id: "Aldeas",
            title: "Aldeas",
            type: "item",
            icon: "material-outline:cabin",
            url: "/Aldeas/Index",
          },
          {
            id: "Ciudades",
            title: "Ciudades",
            type: "item",
            icon: "material-outline:business",
            url: "Ciudades/Index",
          },
          {
            id: "Colonias",
            title: "Colonias",
            type: "item",
            icon: "material-outline:holiday_village",
            url: "/Colonias/Index",
          },
          {
            id: "Paises",
            title: "Países",
            type: "item",
            icon: "material-outline:map",
            url: "Paises/Index",
          },
          {
            id: "Provincias",
            title: "Provincias",
            type: "item",
            icon: "material-outline:house",
            url: "Provincias/Index",
          },
        ],
      },
    ],
  },
  {
    id: "Adua",
    title: "Aduanas",
    type: "group",
    icon: "material-outline:content_cut",
    translate: "ADUANAS",
    children: [

      {
        id: "ContratoAdhesion",
        title: "Contrato de Adhesión",
        type: "collapse",
        icon: "material-outline:contact_mail",
        translate: "",
        children: [
          {
            id: "ComercianteIndividual",
            title: "Comerciante Individual",
            type: "item",
            icon: "heroicons-solid:user",
            url: "ComercianteIndividual/Index",
          },
          {
            id: "PersonaJuridica",
            title: "Persona Juridica",
            type: "item",
            icon: "heroicons-solid:user",
            url: "/PersonaJuridica",
          },
          {
            id: "PersonaNatural",
            title: "Persona Natural",
            type: "item",
            icon: "heroicons-solid:user",
            url: "/PersonaNatural/Index",
          },
        ],
      },
      {
        id: "DEVA",
        title: "Declaración de Valor",
        type: "item",
        icon: "material-outline:fact_check",
        url: "Declaracion_Valor/Index",
      },
      {
        id: "DUCA",
        title: "Duca",
        type: "item",
        icon: "material-outline:article",
        url: "Duca/Index",
      },
      {
        id: "BoletinPago",
        title: "Boletin de Pago",
        type: "item",
        icon: "material-outline:price_check",
        url: "BoletindePago/index",
      },
      {
        id: "Administracion",
        title: "Administración",
        type: "collapse",
        icon: "material-solid:nature_people",
        translate: "Administración",
        children: [
          {
            id: "Aduanas",
            title: "Aduanas",
            type: "item",
            icon: "material-outline:house",
            url: "/Aduana/Index",
          },
          {
            id: "CondicionComercial",
            title: "Condiciones Comerciales",
            type: "item",
            icon: "material-outline:house",
            url: "/CondicionesComerciales/Index",
          },
          {
            id: "EstadoMercancia",
            title: "Estados de las mercancías",
            type: "item",
            icon: "material-solid:offline_pin",
            url: "/EstadoMercancia/Index",
          },
          {
            id: "EstadoBoletin",
            title: "Estados del Boletín",
            type: "item",
            icon: "material-solid:nfc",
            url: "/EstadoBoletin/Index",
          },
          {
            id: "LugaresEmbarque",
            title: "Lugares de Embarque",
            type: "item",
            icon: "material-solid:sailing",
            url: "/LugaresEmbarque/Index",
          },
          {
            id: "NivelesComerciasles",
            title: "Niveles Comerciales",
            type: "item",
            icon: "material-solid:shopping_cart",
            url: "/NivelesComerciales/Index",
          },
          {
            id: "RegimenesAduaneros",
            title: "Regímenes Aduaneros",
            type: "item",
            icon: "material-outline:area_chart",
            url: "/RegimenesAduaneros/Index",
          },
          {
            id: "TipoDocumento",
            title: "Tipo de Documento",
            type: "item",
            icon: "material-outline:backup_table",
            url: "/TipoDocumentos",
          },
        ],
      },
      {
        id: "DocumentoSancion",
        title: "Documento de Sanciones",
        type: "item",
        icon: "material-twotone:find_in_page",
        url: "/DocumentosDeSanciones",
      },

      {
        id: "Facturacion",
        title: "Facturación",
        type: "collapse",
        icon: "material-solid:upload_file",
        translate: "Facturación",
        children: [
          {
            id: "FormasPago",
            title: "Formas de Pago",
            type: "item",
            icon: "material-solid:file_present",
            url: "/FormasPago/Index",
          },
        ],
      },
      {
        id: "Impuestos",
        title: "Impuestos",
        type: "collapse",
        icon: "heroicons-solid:currency-dollar   ",
        translate: "Impuestos",
        children: [
          {
            id: "Aranceles",
            title: "Aranceles",
            type: "item",
            icon: "heroicons-solid:newspaper",
            url: "/Aranceles/Index",
          },
          {
            id: "CodigoImpuesto",
            title: "Código de Impuestos",
            type: "item",
            icon: "heroicons-solid:qrcode",
            url: "/CodigoImpuesto/Index",
          },
          {
            id: "ConceptoPago",
            title: "Concepto de Pago",
            type: "item",
            icon: "heroicons-solid:receipt-refund",
            url: "/ConceptoPago/Index",
          },
          {
            id: "Impuestos",
            title: "Impuestos",
            type: "item",
            icon: "heroicons-solid:scale",
            url: "/Impuestos/Index",
          },
          {
            id: "Incoterms",
            title: "Incoterms",
            type: "item",
            icon: "heroicons-solid:table",
            url: "/Incoterm/Index",
          },
          // {
          //   id: "34",
          //   title: "Liquidación General",
          //   type: "item",
          //   icon: "material-solid:campaign",
          //   url: "/LiquidacionGeneral/Index",
          // },
          // {
          //   id: "35",
          //   title: "Liquidación Por Línea",
          //   type: "item",
          //   icon: "material-solid:charging_station",
          //   url: "/LiquidacionPorLinea/Index",
          // },
          {
            id: "TipoLiquidacion",
            title: "Tipo de Liquidación",
            type: "item",
            icon: "material-solid:donut_small",
            url: "/TipoLiquidacion/Index",
          },
        ],
      },
      {
        id: "Transporte",
        title: "Transporte",
        type: "collapse",
        icon: "material-solid:directions_boat_filled  ",
        translate: "Transporte",
        children: [
          {
            id: "MarcasCarros",
            title: "Marcas de Carros",
            type: "item",
            icon: "material-solid:directions_car",
            url: "/MarcasCarros/Index",
          },
          {
            id: "ModoTransporte",
            title: "Modo de Transporte",
            type: "item",
            icon: "material-solid:local_shipping",
            url: "/ModoTransporte/Index",
          },
          // {
          //   id: '38',
          //   title: 'Transporte',
          //   type: 'item',
          //   icon: 'material-solid:electric_rickshaw',
          //   url: '/Transporte/Index',
          // },
        ],
      },
    ],
  },
  {
    id: "Prod",
    title: "Produccion",
    type: "group",
    icon: "material-outline:content_cut",
    translate: "PRODUCCIÓN",
    children: [
      {
        id: "Inventario",
        title: "Inventario",
        type: "collapse",
        icon: "material-outline:store",
        translate: "Inventario",
        children: [
          {
            id: "Areas",
            title: "Áreas",
            type: "item",
            icon: "material-outline:all_inbox",
            url: "/Areas/Index",
          },
          {
            id: "Categorias",
            title: "Categorías",
            type: "item",
            icon: "material-outline:category",
            url: "/Categorias/Index",
          },
          {
            id: "Lotes",
            title: "Lotes",
            type: "item",
            icon: "material-outline:card_membership",
            url: "/Lotes/Index",
          },
          {
            id: "Materiales",
            title: "Materiales",
            type: "item",
            icon: "material-outline:bakery_dining",
            url: "/Materiales/Index",
          },
          {
            id: "Procesos",
            title: "Procesos",
            type: "item",
            icon: "material-outline:mediation",
            url: "/Procesos/Index",
          },
          {
            id: "ImpuestosProd",
            title: "Impuestos",
            type: "item",
            icon: "heroicons-solid:scale",
            url: "/ImpuestosProd/Index",
          },
          // {
          //   id: "63",
          //   title: "Materiales a Brindar",
          //   type: "item",
          //   icon: "material-outline:business_center",
          //   url: "/MaterialesBrindar/Index",
          // },
          {
            id: "SubCategorias",
            title: "Subcategorías",
            type: "item",
            icon: "material-outline:apps",
            url: "/Subcategorias/Index",
          },
          {
            id: "TipoEmbalaje",
            title: "Tipo de Embalaje",
            type: "item",
            icon: "material-outline:integration_instructions",
            url: "/TipoEmbalaje/Index",
          },
        ],
      },
      {
        id: "Maquinaria",
        title: "Maquinaria",
        type: "collapse",
        icon: "material-outline:account_tree   ",
        translate: "Maquinaria",
        children: [
          {
            id: "FuncionesMaquina",
            title: "Funciones de Máquinas",
            type: "item",
            icon: "material-outline:bike_scooter",
            url: "/FuncionesMaquina/Index",
          },
          {
            id: "HistorialMaquina",
            title: "Historial de Máquina",
            type: "item",
            icon: "material-outline:all_inbox",
            url: "/MaquinaHistorial/Index",
          },
          {
            id: "MarcasMaquina",
            title: "Marcas de Máquinas",
            type: "item",
            icon: "material-outline:auto_stories",
            url: "/MarcasMaquina/Index",
          },
          {
            id: "Maquinas",
            title: "Máquinas",
            type: "item",
            icon: "material-outline:precision_manufacturing",
            url: "/Maquinas/Index",
          },

          {
            id: "ModeloMaquina",
            title: "Modelos de Máquinas",
            type: "item",
            icon: "material-outline:biotech",
            url: "/ModelosMaquina/Index",
          },
          {
            id: "Modulos",
            title: "Módulos",
            type: "item",
            icon: "material-outline:iron",
            url: "/Modulos/Index",
          },
        ],
      },
      {
        id: "prendas",
        title: "Prendas",
        type: "collapse",
        icon: "material-outline:checkroom",
        translate: "Prendas",
        children: [
          {
            id: "Colores",
            title: "Colores",
            type: "item",
            icon: "material-outline:format_color_fill",
            url: "/Colores/Index",
          },

          {
            id: "Estilos",
            title: "Estilos",
            type: "item",
            icon: "material-outline:design_services",
            url: "/Estilos/Index",
          },
          {
            id: "Tallas",
            title: "Tallas",
            type: "item",
            icon: "material-outline:dry_cleaning",
            url: "/Tallas/Index",
          },
        ],
      },
      {
        id: "Produccion",
        title: "ECommerce",
        type: "collapse",
        icon: "material-outline:content_cut",
        translate: "Producción",
        children: [
          // {
          //   id: "46",
          //   title: "Inspecciones",
          //   type: "item",
          //   icon: "material-outline:manage_search",
          //   url: "/Inspecciones/Index",
          // },
          {
            id: "OrdenCompra",
            title: "Orden de Compra",
            type: "item",
            icon: "material-outline:library_books",
            url: "/OrdenCompra/Index",
          },
          {
            id: "OrdenPedido",
            title: "Orden de Pedido",
            type: "item",
            icon: "material-outline:library_books",
            url: "/OrdenPedido/Index",
          },
          {
            id: "Planificacion",
            title: "Planificación",
            type: "item",
            icon: "material-outline:hail",
            url: "/Planificacion/Index",
          },
          {
            id: "PedidoProduccion",
            title: "Pedidos de Producción",
            type: "item",
            icon: "material-outline:local_mall",
            url: "PedidosProduccion/Index",
          },
          {
            id: "OrdenProceso",
            title: "Orden de Procesos",
            type: "item",
            icon: "material-outline:insights",
            url: "/OrdenProcesos/Index",
          },
          {
            id: "RevisionCalidad",
            title: "Revisión de Calidad",
            type: "item",
            icon: "material-outline:pageview",
            url: "/RevisionCalidad/Index",
          },
          {
            id: "FacturaExportacion",
            title: "Factura de exportacion",
            type: "item",
            icon: "heroicons-outline:newspaper",
            url: "/FacturasExportacion/Index",
          },
          {
            id: "LineadeTiempoPO",
            title: "Rastreo de la Orden de Compra",
            type: "item",
            icon: "material-solid:linear_scale",
            url: "/LineadeTiempoPO/Index",
          },
        ],
      },
      {
        id: "ReportesModulo",
        title: "Reportes de Modulos",
        type: "item",
        icon: "heroicons-outline:document-report",
        url: "ReporteModulo/Index",
      },
      
    ],
  },
  {
    id: "Repo",
    title: "Reportes",
    type: "group",
    icon: "material-outline:content_cut",
    translate: "REPORTES",
    children: [
      {
        id: "Reportes",
        title: "Reportes",
        type: "collapse",
        icon: "heroicons-outline:clipboard-list",
        translate: "Reportes",
        children: [
          {
            id: "ConsumoMateriales",
            title: "Consumo de Materiales",
            type: "item",
            icon: "heroicons-outline:document-report",
            url: "Reportes/ConsumoMateriales",
          },
          {
            id: "ReportesContratosAdhesion",
            title: "Contratos de Adhesion",
            type: "item",
            icon: "heroicons-outline:document-report",
            url: "Reportes/ContratosAdhesion",
          },
          {
            id: "CostosdeProduccion",
            title: "Costos de Materiales",
            type: "item",
            icon: "heroicons-outline:document-report",
            url: "Reportes/CostosdeProduccion",
          },
          {
            id: "DevasPendientes",
            title: "DEVAS Pendientes",
            type: "item",
            icon: "heroicons-outline:document-report",
            url: "Reportes/DevasPendientes",
          },
          {
            id: "ReporteImportaciones",
            title: "Importaciones",
            type: "item",
            icon: "heroicons-outline:document-report",
            url: "Reportes/Importaciones",
          },
          {
            id: "IngresoMateriales",
            title: "Ingreso de Materiales",
            type: "item",
            icon: "heroicons-outline:document-report",
            url: "Reportes/IngresoMateriales",
          },
          {
            id: "ReporteInventario",
            title: "Inventario",
            type: "item",
            icon: "heroicons-outline:document-report",
            url: "Reportes/Inventario",
          },
          {
            id: "MaquinasUso",
            title: "Maquinas habilitadas",
            type: "item",
            icon: "heroicons-outline:document-report",
            url: "Reportes/MaquinasUso",
          },
          {
            id: "MaterialesPorPO",
            title: "Materiales por Órden de Compra",
            type: "item",
            icon: "heroicons-outline:document-report",
            url: "Reportes/MaterialesPorPO",
          },
          {
            id: "PedidosCliente",
            title: "Pedidos Por Cliente",
            type: "item",
            icon: "heroicons-outline:document-report",
            url: "Reportes/PedidosCliente",
          },
          {
            id: "ProduccionPorAreayfechas",
            title: "Producción por Areas",
            type: "item",
            icon: "heroicons-outline:document-report",
            url: "Reportes/ProduccionPorAreayfechas",
          },
          {
            id: "ProduccionPorModulo",
            title: "Produccion de Módulos",
            type: "item",
            icon: "heroicons-outline:document-report",
            url: "Reportes/ProduccionPorModulo",
          },
          {
            id: "PlanificacionOrdenCompra",
            title: "Programación Órden de Compra",
            type: "item",
            icon: "heroicons-outline:document-report",
            url: "Reportes/PlanificacionOrdenCompra",
          },
          {
            id: "SeguimientodeProcesosPO",
            title: "Seguimiento de Procesos",
            type: "item",
            icon: "heroicons-outline:document-report",
            url: "Reportes/SeguimientodeProcesosPO",
          },
          {
            id: "TiemposMaquinas",
            title: "Tiempos de Máquinas",
            type: "item",
            icon: "heroicons-outline:document-report",
            url: "Reportes/TiemposMaquinas",
          },
        ],
      },
    ],
  },
  {
    id: "Graf",
    title: "Graficas",
    type: "group",
    icon: "material-outline:content_cut",
    translate: "GRAFICAS",
    children: [],
  }
];

export default navigationConfig;
